### ISSUE TITLE
Cloud functions y versión de Node.js en proyecto Burger Queen

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#1006]
Ayer tuve ayudantías (OH) con estudiantes de Bogotá. Habían varias con problemas para desplegar el proyecto de Burger Queen a Firebase, y la mayoría eran problemas parecidos con diferentes versiones de Node.js - tanto en Windows, MacOS y Linux.

El problema se origina en el hecho de que a muchas no les queda claro que la [subcarpeta `functions` del boilerplate](https://github.com/Laboratoria/bootcamp/tree/master/projects/04-burger-queen/functions) contiene exclusivamente código de las cloud functions y se considera un programa distinto, con su propio `package.json`, sus propias dependencias e inclusive con su propia versión de Node si fuera necesario. Además, este código en principio no se ejecuta ni en el cliente ni en nuestra computadora (a menos que hagamos pruebas unitarias de las cloud functions) si no en el servidor. Por otro lado, en la raíz del repo tendrán otro `package.json` con las dependencias y otras configuraciones del frontend, que será una interfaz construida con React, Angular, etc. Básicamente son dos programas, front end y back end. También es importante reforzar que pareciera que la mayoría de ellas no necesita usar cloud functions en este proyecto, lo cual causa todavía más confusión con el boilerplate.

He visto que muchas estudiantes habían instalado Node.js 8 para evitar problemas de billing con las cloud functions de Firebase pero después no podían usar las herramientas de Angular o React ya que se quejan que Node.js 8 es muy viejito. En ese contexto, comienzan con el enredo de `nvm`, `nvm-windows`, `WSL`,  `brew`, etc, ... que después deriva en temas de OS, permisos, shell, `PATH` , etc, ... y a esto se le suma la introducción de `yarn` para las que se inician con `react` :cold_sweat:

Aprovecho a compartir por acá algunas de mis recomendaciones con respecto a instalación de Node.js:

1. Que usen Node.js 12 en sus máquinas.
2. Si usan POSIX (GNU/Linux, MacOS, ...) que usen [`nvm`](https://github.com/nvm-sh/nvm) (instalando Node dentro de la cuenta de usuario y no global).
3. Si usan Windows 10, que usen [`Windows Subsystem for Linux (WSL)`](https://docs.microsoft.com/en-us/windows/wsl/install-win10), y una vez teniendo el susbsistema Linux ya tienen un sistema POSIX (punto 2).
4. Alternativamente en Windows 10 y anteriores, que usen [`cmder`](https://cmder.net/) (versión completa que incluye `git-for-windows`) en conjunción con [`nvm-windows`](https://github.com/coreybutler/nvm-windows).
5. En MacOS, si usan React es probable que usen [`yarn`](https://yarnpkg.com/), tendrán que tener `node` instalado via `brew` (node es dependencia de yarn), pero aún así pueden/deben usar `nvm` y asegurarse de que su `PATH` esté correctamente configurado para que gane la instalación en la carpeta de usuario (`nvm`).

## Preguntas

1. ¿Se han encontrado recientemente con este tipo de issues en otras sedes?
2. ¿Cómo recomiendan manejar la instalación de Node?
3. ¿Consideran que las cloud functions son necesarias en este proyecto? Si es así, ¿qué feature las necesita?

***

Ideas? :thinking: 

cc/ @Laboratoria/coaches

**Comment by merunga** [comment]
garicas @lupomontero por el detalle
en mi opinion no hay ningun feature q dependa de cloud functions, pero creo q la conversacion es si nos interesa que las conozcan. En ese caso deberian estar explicitamente mapeadas como OAs y torcer un poco el alcance del proyecto actual para forzar su uso

**Comment by raulingg** [comment]
> ¿Se han encontrado recientemente con este tipo de issues en otras sedes?

Yo tuve 2 o 3 experiencias ayudando a estudiantes con el tema de conflictos o issues al momento de instalar dependencias o actualizarlas. Todas ellas llevaban al tema de permisos sobre las carpetas y relacionado a la forma de instalación de Nodejs y ejecución de npm-scripts.

> Consideran que las cloud functions son necesarias en este proyecto? Si es así, ¿qué feature las necesita?

+1 contigo @lupomontero porque pienso que agrega más carga (knowledge, issues, setup) para las estudiantes como para los couches, y además podría restar espacio disponible para OA primarios del proyecto.

**Comment by unjust** [comment]
Cuando decidimos como van a manejar el version de node y su instalación - seria genial a tener los recomendaciones y/o instrucciones para Windows y Mac/Linux en un doc - tal vez un parte de README en Burger Queen.

**Comment by mfdebian** [comment]
Perdón por lo tarde, y poco aporte, pero confirmo que en SCL tampoco le hayamos valor al tema de las cloud functions en el proyecto BQ; Y muy de acuerdo con lo que mencionas @lupomontero, los OA de ese proyecto apuntan a los frameworks de desarrollo FE.
