### ISSUE TITLE
Actualizar objetivos de aprendizaje en proyectos todavía no estandarizados

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#1018]
En los últimos meses se han estado estandarizando los objetivos de aprendizaje de los proyectos, pero todavía faltan varios por revisar... creo este issue para hacer seguimiento general de este esfuerzo.

- [ ] [02-emergency-room](https://github.com/Laboratoria/bootcamp/tree/master/projects/02-emergency-room#3-objetivos-de-aprendizaje)
- [ ] [02-movie-challenge](https://github.com/Laboratoria/bootcamp/tree/master/projects/02-movie-challenge#4-objetivos-de-aprendizaje)
- [ ] [03-visitors](https://github.com/Laboratoria/bootcamp/tree/master/projects/03-visitors#4-objetivos-de-aprendizaje)
- [ ] [04-news-alerts](https://github.com/Laboratoria/bootcamp/tree/master/projects/04-news-alerts#4-objetivos-de-aprendizaje)
- [ ] [05-battleship](https://github.com/Laboratoria/bootcamp/tree/master/projects/05-battleship#3-objetivos-de-aprendizaje)
- [ ] [05-social-network-fw](https://github.com/Laboratoria/bootcamp/tree/master/projects/05-social-network-fw#3-objetivos-de-aprendizaje)
- [ ] [05-tic-tac-toe-rn](https://github.com/Laboratoria/bootcamp/tree/master/projects/05-tic-tac-toe-rn#3-objetivos-de-aprendizaje)

**Comment by unjust** [comment]
Hola @lupomontero hay alguno de estos que todavia necesita ayuda con el README?

**Comment by lupomontero** [comment]
Hola @unjust, perdona por la demora en contestar... (otra vez :see_no_evil:). Efectivamente todavía necesitamos ayuda. Pero ahora esta tarea es parte de #1050, que va a introducir una nuevo _formato_ para manejar los objetivos de aprendizaje. El viernes tenemos agendado un espacio, asi que aprovechemos a hablar de esto para ver cómo me puedes echar una mano.

Me tomo la libertad de cerrar este issue en favor de continuar la conversación en #1050
