### ISSUE TITLE
Agregar más opciones de despliegue del front-end en proyecto Burger Queen

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#1023]
Siguiendo de [este otro hilo](https://github.com/Laboratoria/bootcamp/pull/1017#issuecomment-720678893), parece que sería buena idea dar más opciones de despliegue para el front-end en este proyecto.

Por un lado está el despliegue de Firebase (`firebase deploy`) que se necesita para desplegar reglas de firestore, índices, y opcionalmente cloud functions, pero aparte de eso está el despliegue de la interfaz web, que por ahora sugiere usar Firebase Hosting y así usar un único comando de despliegue para front-end y back-end. Es para esta 2nda parte que sería interesante agregar opciones ya que la interfaz no tiene por qué estar alojada en Firebase, podrían usar GitHub Pages, un CDN, S3 Bucket, etc... cualquier servicio de alojamiento de assets estáticos.

Un tema a tener en cuenta es que probablemente hay docs de create-react-app, Angular y Vue sobre cómo desplegar tu app (interfaz web) en diferentes proveedores o escenarios, y podríamos apoyarnos en esos docs directamente.

cc/ @merunga @luucamay @mayrascript @fakel

**Comment by lupomontero** [comment]
cc/ @unjust

**Comment by unjust** [comment]
Perdon llegue tarde a la fiesta. 🎉 

Justo estaba usando netlify para desplegar un sitio con jekyll. Netlify tiene un web ui y un cli que fue un gusto para usar https://docs.netlify.com/cli/get-started/

Creo podemos tambien sugerir este servicio, hay un opcion gratis, pero todavia no se todas las limitaciones. He encontrado varios posts con la tema como desplegar React + Firebase app with Netlify. 
Y tienen documentation de varios build configs - https://docs.netlify.com/configure-builds/common-configurations/#javascript-spas

**Comment by unjust** [comment]
@lupomontero ahora quieres que haga un pull request con detalles de netlify?

**Comment by lupomontero** [comment]
@unjust, si te animas sería buenísimo :star:
