### ISSUE TITLE
Proyecto electivo de WordPress

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#1024]
Qué les parece la idea de tener un proyecto electivo de WordPress? Algo que implique armar un blog, una página personal, de una banda, un pequeño negocio, etc, ... algo basado en la típica página de freelo que requiere hacer una plantilla personalizada, elegir algunos plugins y armar el contenido... no para todas, pero como una opción de algo que no han visto y muchas de ellas seguro van a encontrar al salir del bootcamp... :thinking: 

cc/ @Laboratoria/coaches

**Comment by mfdebian** [comment]
Qué temón más polémico!! Jajaj, pero sí, @lupomontero muy de acuerdo con que a muchas estudiantes les pasa que en sus trabajos les toca enfrentarse a proyectos de WP y en el BC ni siquiera los mencionamos. Particularmente en Chile aún hay muchas empresas que siguen usando WP y la mayoría de empresas de diseño web suelen estar ocupando WP.

Tendríamos que capacitarnos en estos temas eso sí, personalmente he vivido toda mi experiencia de desarrollador muy desconectado de WP (y PHP, CPanel o en general todo ese ecosistema), creo que puede ser costoso en tiempo, pero de seguro sí añade valor a las estudiantes; Quizás pickear a algunx coach champion que pueda ir ayudándonos de a poco a probar esto e ir generando lineamientos para esto? #justAThought

**Comment by gabrieluizramos** [comment]
Buenisima idea!

Será que es más proveitoso utilizar Wordpress o agregar algo com Gatsby/Next, ya que las estudiantes aprenden React? Asi pueden aplicar sus conocimientos y aprofundar en React ya com algo estatico o con SSR?

O quizás ambos, ya que es algo electivo.

**Comment by dapino** [comment]
Estaría muy bueno, Wordpress es una buena herramienta, es sencilla de implementar y la curva de aprendizaje para desarrollar sobre WP no es muy pronunciada. 

Yo viví de desarrollar Themes para Wordpress durante varios años, y aún se siguen desarrollando e implementando Themes, plugins, complementos para esos themes, etc, es un mercado muy grande.

Varias estudiantes me han preguntado acerca de WP y también sobre como como montar un sitio web rápido donde puedan subir contenido y demás.

**Comment by lupomontero** [comment]
> Quizás pickear a algunx coach champion que pueda ir ayudándonos de a poco a probar esto e ir generando lineamientos para esto? #justAThought

@mfdebian: Parece que @dapino podría ser un cadidato :speak_no_evil: :joy: 

> Será que es más proveitoso utilizar Wordpress o agregar algo com Gatsby/Next, ya que las estudiantes aprenden React? Asi pueden aplicar sus conocimientos y aprofundar en React ya com algo estatico o con SSR?
>
> O quizás ambos, ya que es algo electivo.

@gabrieluizramos: ambos sería lo ideal... son "objetivos de aprendizaje" muy distintos. Si te animas a hacer una propuestas sería buenísimo abrir otro issue específicamente para eso y/o un PR con alguna propuesta concreta :wink:

**Comment by andrepfl** [comment]
Perdón por meter la cuchara speak_no_evil joy creo que **agrega mucho valor** el contar con un proyecto donde puedan aprender WP! En Chile se sigue ocupando un montón y siempre se pueden encontrar empresas que buscan estos talentos. También puede ser valioso para la modalidad de trabajo freelance donde varias PYMES y negocios les piden ayuda trabajando con WP.

**Comment by raulingg** [comment]
Una idea buena puede ser tener números de requerimientos en cuanto conocimiento o habilidades alrededor de wordpress demandado en los postulaciiones u ofertas que han tenido las estudiantes en sus sede.

Podemos partir por ahí? qué opinan?

**Comment by dapino** [comment]
Algunos temas que sugeriría para definir OAs serían: 
- Wordpress.com vs Wordpress.org
- Instalación: local (WAMP, XAMP, Local by Flywheel, etc), hosting, despliegue, cpanel...
- Administración:  tipos de posts, Taxonomías, usuarios/roles.
- Themes vs constructores visuales.
- Uso e instalación de plugins: SEO, seguridad, rendimiento.

- Desarrollo de Themes:
-- Plantillas: estructura de carpetas, estructura de archivos, estructura de plantilla, child themes
-- archivo functions
-- archivo style.css 

- Desarrollo de plugins.

- API REST de WordPress

- Woocommerce

**Comment by lupomontero** [comment]
Buenazo @dapino. Después de lo conversado en las últimas horas por Slack me he tomado la libertad de asignarte este issue :see_no_evil: 

Como referencia para la creación de proyectos nuevos, las 3 piezas a tener en cuenta son:

* `README.md`. Recomiendo comenzar por  el _Resumen del proyecto_ y los _Objetivos de aprendizaje_.
* Implementación modelo (yo recomendaría hacer la implementación modelo antes de dar forma completa al README y decidir el boilerplate). La implementación modelo nos permite darnos cuenta de los detalles, ... la diferencia entre imaginar un proyecto y de hecho construirlo - el demonio vive en los detalles.
* Boilerplate. Los archivos que queramos incluir además del README.

Acá te dejo también link al wiki donde se detalla la [anatomía de un proyecto](https://github.com/Laboratoria/bootcamp/wiki/Anatom%C3%ADa-de-un-proyecto).

**Comment by unjust** [comment]
Un opinion contrario... 😬 
Wordpress es un ecosystem aparte, más para PHP y plugins de que javascript. Sé que muchas personas buscan desarollador de Wordpress en anuncios de trabajo. Pero a mi como coach, tengo dudas que vaya a tener mucho ganas a aprenderlo para responder a preguntas y apoyarlxs bien

**Comment by lupomontero** [comment]
Es un buen punto lo que planteas @unjust ... :thinking: ... en principio lo estamos pensando como un proyecto electivo, que solo unas pocas tomarían, y tendríamos que organizar un grupo de coaches que se manejen con PHP/WordPress para poder ofrecer el proyecto a las estudiantes. Una primera tarea podría ser sondear el equipo de coaches para ver quienes están en posición de apoyar en caso de que probáramos el proyecto con el agún cohort.

cc/ @dapino

**Comment by lupomontero** [comment]
Por el momento me tomo la libertad de cerrar este issue en favor de #1056, como parte del piloto de extensión de bootcamp que estamos planeando para agosto...
