### ISSUE TITLE
Test incompleto en Algoritmo de Luhn

### ISSUE THREAD

**Issue by dsandovalm** [Laboratoria/bootcamp#1038]
Al ejecutar _npm test_ en el proyecto de Algoritmo de luhn, omite los tests porque aun no están escritos en _validator.spec.js_, solamente enunciados, marcados con .skip y con un comentario ( // escribe aquí tu test ) dentro de ellos.

Eso afecta mucho los resultados del test, arrojando un warning en los tests que aparecen como 'skipped' y en rojo los valores de coverage (dando 0 en la mayoria de porcentajes) por lo que obviamente nunca se cumplen los requisitos minimos de entrega para el proyecto.

**Comment by lupomontero** [comment]
Gracias por el feedback @dsandovalm :1st_place_medal: 

Ya vi el PR también :smile: Todo parece ok, así que en el próximo _release_ el boilerplate del proyecto incuirá tus cambios.
