### ISSUE TITLE
Nuevo proyecto "Chat app" para piloto de full stack

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#1055]
Como parte del [piloto de full stack](https://github.com/Laboratoria/bootcamp/issues/1058)...

## Chat app (real time, web sockets)

En este proyecto construirás un sistema de chat realtime (cliente y servidor) usando JavaScript. Este proyecto está pensado para hacer en equipo, 2-3 personas.

Los usuarios deben poder crear una cuenta, iniciar sesión, crear un canal, ver y responder mensajes en un canal, además de ver quiénes están conectados. Para el front-end recomendamos usar algún framework popular como React, Angular o Vue.

El principal objetivo de aprendizaje de este proyecto es tener una primera oportunidad de explorar WebSockets como alternativa a HTTP para comunicación _real time_ entre cliente y servidor.

OAs: Node.js, Express, Bases de datos, Autenticación, HTTP, WebSockets, React/Angular/Vue.

**Comment by oxfist** [comment]
Primera versión de OAs para el proyecto:
- Express - creación de un servicio web (nuevo)
- Express - manejo de rutas
- JavaScript - código asíncrono
- JavaScript - pruebas unitarias
- JavaScript - pruebas de integración
- Bases de datos - modelar problema/dominio en base de datos relacional (nuevo)
- Bases de datos - diagramar modelo de datos (nuevo)
- Bases de datos - obtención de datos a través de consulta SQL (nuevo)
- Bases de datos - inserción/edición/eliminación de datos a través de consulta SQL (nuevo)
- Bases de datos - utilización de índices y constraints (nuevo)
- Autenticación
- Autorización (nuevo)
- HTTP - request - response
- HTTP - verbs
- HTTP - cors
- WebSockets (nuevo)
- React/Angular/Vue
- CI/CD - construcción de pipelines (nuevo)
- CI/CD - despliegue de servicios en Heroku (nuevo)
- CI/CD - aplicación de TBD para integración continua (nuevo)
- CI/CD - validación de cobertura de pruebas en pipeline (nuevo)
- Desarrollo de producto - creación de historias de usuario (nuevo)
- Desarrollo de producto - aplicación de enfoque iterativo en historias de usuario (nuevo)

Aunque es esperado de los proyectos durante el BC la creación de historias de usuario no existe como un OA aparte, creo que aquí podría surgir una nueva categoría **Desarrollo de producto** donde esté mejor delimitado lo que se espera en primera instancia con las historias de usuario en sí y luego cómo aplicar un enfoque iterativo/independiente con ellas.

Los OAs que se agregarían faltaría descomponerlos bien y agregar sus respectivos links de referencia.

**Comment by oxfist** [comment]
## Principales historias de usuario
- Loguearse
  - **Yo como** _usuario-segmento_
   **Quiero** iniciar sesión
  **Para** conversar con las personas conectadas
- Crear cuenta
  - **Yo como** _usuario-segmento_
  **Quiero** crearme una cuenta de usuario
  **Para** participar en la comunidad
- Enviar chat en canal principal
  - **Yo como** _usuario-segmento_
  **Quiero** enviar un mensaje a todas las personas conectadas
  **Para** compartir intereses similares
- Crear un nuevo canal
  - **Yo como** _usuario-segmento_
  **Quiero** crear un canal privado de chat
  **Para** comunicarme solo con las personas que quiero

Para este proyecto un buen punto de partida sería entregar historias de usuario pre-hechas (en el _boilerplate_)  para enfocar el desarrollo inicial y poder jugar un rol de PO con las estudiantes para aplicar negociación de alcance, priorización, etc. En este caso _usuario-segmento_ habría que reemplazarlo por un tipo de usuario dependiendo de si la aplicación de chat tendrá una temática determinada _a priori_ o si dependrá de los equipos. Intencionalmente hay historias que quedarían fuera del _boilerplate_, ej. ver chats de otras personas, para que las estudiantes vayan retomando ese trabajo a medida que avanzan.
