### ISSUE TITLE
Nuevo proyecto "WordPress custom site" para piloto de full stack

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#1056]
Como parte del [piloto de full stack](https://github.com/Laboratoria/bootcamp/issues/1058)...

## WordPress custom site (blog, e-commerce)

En este proyecto te invitamos a que nos hagas una propuesta de qué te gustaría construir usando WordPress como plataforma. Podría ser cualquier cosa, desde un blog personal hasta una tienda online, siempre y cuando, como parte del proceso, te de la oportunidad de hacer una plantilla (`theme`) personalizada y por lo menos implementar un plugin específico para la aplicación.

El principal objetivo de aprendizaje de este proyecto es tener una primera experiencia con WordPress y el stack de LAMP, tanto como webmaster, así como _diseñador/desarrollador_ de themes y plugins.

OAs: LAMP, PHP, MySQL, WordPress, ...

**Comment by ssinuco** [comment]
- [ ] Instalar PHP, Apache/Nginx en máquina local
- [ ] Instalar MySQL en máquina local
- [ ] Instalar WordPress en máquina local
- [ ] Búsqueda de top 10 de plugins de WordPress para extraer de ellos los criterios de aceptación mínimos del proyecto

**Comment by lupomontero** [comment]
@ssinuco, crees que tendría sentido usar `docker` y `docker-compose` para el entorno de desarrollo? Existe la [imagen oficial de WordPress en Docker Hub](https://hub.docker.com/_/wordpress) así como [MySQL](https://hub.docker.com/_/mysql) y [ejemplos/tutoriales sobre cómo arrancar](https://docs.docker.com/samples/wordpress/). O por otro lado crees que tiene sentido que tengan que instalar y configurar PHP, Apache/Nginx/MySQL directamente sobre el metal?

**Comment by ssinuco** [comment]
@lupomontero me parece mejor lo que propones, creo que seria mas rapido y menos traumatico. Dejame lo reviso.

**Comment by ssinuco** [comment]
Primer borrador de Objetivos de aprendizaje relacionados a este proyecto:

PHP
- Uso de condicionales (if-else | switch | operador ternario).
- Uso de bucles (for | for..in | for..of | while).
- Uso de funciones (parámetros | argumentos | valor de retorno).
- Declaración variables
- Manipular arrays
- Manipular objects
- PHPUnit
- XDebug
- Composer


Wordpress

	Administración

	- Gestionar Users y Roles
	- Gestionar Posts
	- Gestionar Pages
	- Gestionar Comments
	- Gestionar Media Files
	- Gestionar Themes
	- Gestionar Menus
	- Gestionar Widgets
	- Gestionar Plugins

	Desarrollo:

	- Themes
	- Widgets
	- Custom Post Types
	- Plugins
	- Hooks: action y filter
	- Consumo API REST

	Despliegue
	- Hosting

**Comment by ssinuco** [comment]
- [ ] Averiguar un servicio de host para WordPress gratuito que no requiera tarjeta de crédito
- [ ] Explorar otras opciones de hosting: AWS Container, cPanel, WordPress gratuito
- [ ] Escribir un par de párrafos como primera narrativa del proyecto. Importante mencionar que lo que queremos es que las estudiantes armen una propuesta.
