### ISSUE TITLE
Imágenes no disponibles en el contenido para PA: "Box Model & Display" 

### ISSUE THREAD

**Issue by reloadercf** [Laboratoria/bootcamp#1060]
Hay algunas imágenes de este [contenido](https://github.com/Laboratoria/bootcamp/blob/v2.13.0/topics/css/01-css/02-boxmodel-and-display/README.md) que están caídas

**Comment by lupomontero** [comment]
Gracias por reportar esto @carlosroec.

Revisando el markdown, veo que hay varias imágenes alojadas en `subefotos.com`, y este servicio parece que ya no funciona :scream: ... En este caso el contenido fue [creado hace 4 años](https://github.com/Laboratoria/bootcamp/blame/main/topics/css/01-css/02-boxmodel-and-display/README.md)... así que no estoy seguro de si podremos conseguir las imágenes originales.

Antes de proponer una solución, me gustaría entender el grado de urgencia para solucionar esto. ¿Se está usando ahorita este contenido? Disculpa mi ignorancia :see_no_evil:, pero me suena que para el proceso de admisión usamos el contenido de [este otro repo](https://github.com/Laboratoria/admission-curriculum)?

cc/ @rocioalberdi @MaiaRojas @raulingg

**Comment by reloadercf** [comment]
@lupomontero te cuento una parte del proceso, Parte a travez del envío de un correo donde se invita a la postulante, dentro de los elementos que se envían a las postulantes de preadmisión  se les proporciona un [gitbook](https://laboratoria1.gitbook.io/preadmision/v/CDMX/) el cual todas las sedes mandan pero en la sección de [EL PROYECTO](https://laboratoria1.gitbook.io/preadmision/v/CDMX/a-trabajar/proyecto) incluyen contenido que las postulantes pueden acceder desde el LMS, ese contenido es precargado por alguna coach de cada sede. Parte de ese contenido incluyen: [Curso CSS: Unidad 1, CSS. Específicamente Box Model (Modelo de Caja)](https://lms.laboratoria.la/cohorts/cdmx-2021-05-prebootcamp-js-cdmx011/topics/css/01-css/02-boxmodel-and-display) y también [Manejo de Eventos](https://lms.laboratoria.la/cohorts/cdmx-2021-05-prebootcamp-js-cdmx011/topics/browser/02-dom/04-events) **Estos dos tópicos incluyen links caidos** 😱 pero en respuesta a la urgencia creo que todas las sedes usamos ese contenido en preadmisión y en mi experiencia pasada las postulantes (no todas pero si algunas) si acceden al contenido.

**Comment by lupomontero** [comment]
Gracias por el contexto @reloadercf :star: 

Continuando con la investigación :detective: ... parece que esto es un _issue_ que afecta a varios tópicos (`shell`, `css`, `intro-ux`, `scm` y `browser`). En toral hay `45` imágenes alojadas en `subefotos.com` (ver detalles más abajo).

Me temo que para resolver esto _completamente_ tendremos que revisar cada instancia y decidir si re-emplazar la imagen en cuestión o borrarla. Esto va a ser un proceso un poco tedioso, así que para no dejarlo atracado propongo que prioricemos las lecturas usadas en _pre-admisión_ (aka `preBootcamp`).

- [ ] `topics/css/01-css/02-boxmodel-and-display`
- [ ] `topics/browser/02-dom/04-events`

Más adelante, en vez de revisar solo las imágenes rotas, creo que ya nos tocá darle una vuelta completa a los tópicos y ver qué queremos _mantener_ de verdad y qué cosas podemos reemplazar por recursos externos... :thinking: 

cc/ @diegovelezg @rocioalberdi 

***

```sh
$ grep -r subefotos ./topics | wc -l
45
```

```sh
$ grep -r subefotos ./topics
./topics/shell/01-intro/01-intro/README.md:![teclas](https://fotos.subefotos.com/5b80f161eee85749b3825fc14406872eo.png)
./topics/shell/01-intro/01-intro/README.md:![run](https://fotos.subefotos.com/98de3a4aec5f117f023ba85addc08298o.png)
./topics/shell/01-intro/01-intro/README.md:![línea de comandos](https://fotos.subefotos.com/4fda00e92300cda89ff141f0265d6227o.png)
./topics/shell/_legacy/README.md:![plano](https://fotos.subefotos.com/31c6b9a7726517ce121b0e66f283deaao.png)
./topics/css/01-css/08-practical-cases/README.md:![Demo Menu vertical](https://fotos.subefotos.com/3b523ebdaaa3e207adb555eaa26b8351o.gif)
./topics/css/01-css/08-practical-cases/README.md:![Demo Menu horizontal](https://fotos.subefotos.com/9da8149c853131e7e7282a30c9dc37e6o.gif)
./topics/css/01-css/10-practice/README.pt-BR.md:[Applove](https://fotos.subefotos.com/1edc0aab51f1d624da4a24ab86129d87o.png).
./topics/css/01-css/10-practice/README.md:Sigue los pasos de tu profe para crear una réplica de la  web [Applove](https://fotos.subefotos.com/1edc0aab51f1d624da4a24ab86129d87o.png).
./topics/css/01-css/02-boxmodel-and-display/README.md:![box model](https://fotos.subefotos.com/e1001df7d218a9a8a8670d88628f0cc5o.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:![box model](https://fotos.subefotos.com/bf683e9aa7e08dcc951b9b9e529ae627o.gif)
./topics/css/01-css/02-boxmodel-and-display/README.md:![box model](https://fotos.subefotos.com/46cd99b85adea7f3106700cd9ffa473fo.png)
./topics/css/01-css/02-boxmodel-and-display/README.md: ![padding](https://fotos.subefotos.com/179d7bd111acebc38e6b29ed62a5522eo.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:![width](https://fotos.subefotos.com/ad307ef682632ca28282a778c74610b0o.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:![height](https://fotos.subefotos.com/4395164aa663621f860b4d12c2d8fcd5o.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:![content-box](https://fotos.subefotos.com/9958eea0026f6d90ae1cd9be0f47f2ebo.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:![display](https://fotos.subefotos.com/7ffd4c0c33fafb4d898a16a8935a0697o.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:![inline](https://fotos.subefotos.com/46ddc8db6addcac25aaf5d1b79275232o.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:![block](https://fotos.subefotos.com/0a7b2184ae765750e3929af6482473bfo.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:![inline-block](https://fotos.subefotos.com/7892f0763915a586528d36559d76a451o.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:  ![none](https://fotos.subefotos.com/54885d2a934503abd48eb254549f099fo.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:  ![hidden](https://fotos.subefotos.com/22776b343dd0dde50cf523b9544ad7d2o.png)
./topics/css/01-css/02-boxmodel-and-display/README.md:![Resumen Display](https://fotos.subefotos.com/5bddcb7ef810c7290e982d0ad17e4941o.png)
./topics/css/01-css/03-practice/README.md:![Vistas Banderas1](https://fotos.subefotos.com/8157f58d3d2dcfcf689ec56554097266o.png)
./topics/css/01-css/03-practice/README.md:![Vistas Banderas2](https://fotos.subefotos.com/304ad94ffc6b76d7366894e1d9646961o.png)
./topics/css/01-css/03-practice/README.md:![Vistas Banderas3](https://fotos.subefotos.com/ea2ba0950028f26c289e7ae55f2438d2o.png)
./topics/css/01-css/03-practice/README.md:![Vistas Banderas4](https://fotos.subefotos.com/ce40c790a0ddf23ff36a075bf91d59c6o.png)
./topics/css/01-css/07-practice/README.md:![La Cancha](https://fotos.subefotos.com/c8aebc7059f194f164e0c9c3f63421e6o.png)
./topics/css/01-css/07-practice/README.md:![6 cajas](https://fotos.subefotos.com/c0a08756744f401530d3eb8bb58c36e3o.png)
./topics/css/01-css/07-practice/README.md:![css float](https://fotos.subefotos.com/320e77be1fc814d1a92edbc43cb59caco.png)
./topics/intro-ux/00-que-es-uxd/00-que-es-uxd/README.md:![T-shaped skills](https://fotos.subefotos.com/96bdd078734baef5f177c55bc9c05a78o.png)
./topics/intro-ux/00-que-es-uxd/00-que-es-uxd/README.md:![Puestos relacionados a UX](https://fotos.subefotos.com/8e6469bf296f6e99f434ab723e68534do.jpg)
./topics/scm/01-git/02-install/README.md:  !['Paso 1, instalación de Git'](http://fotos.subefotos.com/dc926ac2d62764c9861d890a87cae1d1o.png)
./topics/scm/01-git/02-install/README.md:  !['Paso 2, instalación de Git'](http://fotos.subefotos.com/66ccdc66224e1b301c143e2f228c56d4o.png)
./topics/scm/01-git/02-install/README.md:  !['Paso 3, instalación de Git'](http://fotos.subefotos.com/6695c2d71e3574fea5a79d61ea8e8e11o.png)
./topics/scm/01-git/02-install/README.md:  ![Paso 4, instalación de Git](http://fotos.subefotos.com/3aeac78b635775f55e4365939b87d8e6o.png)
./topics/scm/01-git/02-install/README.md:  !['Paso 5, instalación de Git'](http://fotos.subefotos.com/febf4d79afaa6d625173dca24d290dc8o.png)
./topics/scm/01-git/02-install/README.md:  !['Paso 6, instalación de Git'](http://fotos.subefotos.com/3794e27ec38776180c13c14819fdc0f9o.png)
./topics/scm/01-git/02-install/README.md:  !['Paso 7, instalación de Git'](http://fotos.subefotos.com/7da9d7c8c7ee9eb92ef2cc548c0f0315o.png)
./topics/scm/01-git/02-install/README.md:  !['Paso 8, instalación de Git'](http://fotos.subefotos.com/93a5079b8524142b8e07fd97981afe38o.png)
./topics/scm/01-git/02-install/README.md:  !['Paso 9, instalación de Git'](http://fotos.subefotos.com/7ce940e5dec200b7203115b1ee22c6ffo.png)
./topics/scm/01-git/02-install/README.md:  !['Paso 10, instalación de Git'](http://fotos.subefotos.com/47a5605681eec98bd81c7f60489187e4o.png)
./topics/scm/01-git/01-git/README.md:!['versiones'](http://fotos.subefotos.com/e6ea20e7174abf68ba4a047eaa0d5373o.png)
./topics/browser/02-dom/06-practical-cases/README.md:![Mini Zoo](https://fotos.subefotos.com/33a270779462a9ffe98ae8c2b528087co.gif)
./topics/browser/02-dom/04-events/README.md:![flow-event](https://fotos.subefotos.com/c2bdbf4b16698bcaec0b705f4e422be2o.png)
./topics/browser/02-dom/10-guided-exercises/README.md:![Captcha](https://fotos.subefotos.com/299269b4ed8aac7e0a445f0c76355612o.gif)
```

**Comment by lupomontero** [comment]
@reloadercf: he abierto un PR que debería solucionar el problema de las imágenes rotas en las dos lecturas que están usando en `preBootcamp` ahorita. Te he agregado como _reviewer_ por si quieres echar un vistazo y dejar tu :heavy_check_mark:, si no, siendo _fixes_ igual procederé con el _merge_. Una vez integrado en `main` este cambio será incluído en el siguiente release (mañana :thinking:). Una vez que se haya hecho release de la currícula nos toca hablar con @MaiaRojas para que nos ayude a actualizar el contenido en los cohorts específicos que estén usando este contenido.
