### ISSUE TITLE
¿Cómo abordar temas de computer science?

### ISSUE THREAD

**Issue by ssinuco** [Laboratoria/bootcamp#1073]
Hay temas de computer science que vale la pena que las estudiantes conozca:
- Estructura de datos: arboles, grafos, colas, listas...
- Algoritmos: ordenamiento, busqueda...
- Notacion O Grande

La idea es buscar espacios/proyectos donde las estudiantes puedan ver estos temas.

**Comment by ssinuco** [comment]
@merunga te menciono para que revisemos este issue

**Comment by unjust** [comment]
Por ahora voy a cerrar esta issue. No es como no vale la pena, pero creo mejor proponemos cuales proyectos tienen estas temas y cambiar los readmes.
