### ISSUE TITLE
Battleship: Actualizar proyecto con Objetivos de Aprendizaje estandarizados y revisión general del enunciado

### ISSUE THREAD

**Issue by mfdebian** [Laboratoria/bootcamp#1130]
Desde #1067 se desprende que [este proyecto](https://github.com/Laboratoria/bootcamp/tree/main/projects/05-battleship) aún no tiene su estructura actualizada para seguir con el estándar que cumplen los demás, que básicamente consiste en que los Objetivos de Aprendizaje asociados al proyecto estén descritos en su archivo `data.yml` (que hoy no existe y habría que crearlo), como lo tiene, por ejemplo, el de [burger-queen](https://github.com/Laboratoria/bootcamp/blob/main/projects/04-burger-queen/project.yml); Y que el README del proyecto tenga la estructura que siguen también los demás (nuevamente, el ejemplo de cómo está hecho [en el proyecto burger-queen](https://github.com/Laboratoria/bootcamp/blob/main/projects/04-burger-queen/README.md#3-objetivos-de-aprendizaje)).

También cabe revisar de manera general el README para que el enunciado no contenga errores gramaticales, de redacción, estilo, etc... Y en el mejor de los casos, agregar también la sección "Criterios de aceptación mínimos del proyecto" que describa los requerimientos funcionales del proyecto en formato de _Historias de Usuaria_ ([ejemplo](https://github.com/Laboratoria/bootcamp/tree/main/projects/04-notes#5-criterios-de-aceptaci%C3%B3n-m%C3%ADnimos-del-proyecto)).

**Comment by unjust** [comment]
@mfdebian podemos cerrar este issue ?

Separe el proyecto de model en este otro issue:
https://github.com/Laboratoria/bootcamp/issues/1253
