### ISSUE TITLE
Actualizar atributo `track` en el parseo (build) de proyectos en la currícula.

### ISSUE THREAD

**Issue by mfdebian** [Laboratoria/bootcamp#1136]
Cuando parseamos los proyectos, se incluye la propiedad `track`, que [hoy en día están descritos como "ux" y "js"](https://github.com/Laboratoria/bootcamp/blob/main/scripts/build.js).

Estos deben ser actualizados para reflejar el [cambio actual en core](https://github.com/Laboratoria/core/blob/main/doc/models/Track.md),  donde los nombres son "Web Dev" y "UX". De hecho cabe preguntar, si es que serán llamados por su propiedad `name`, o más bien por `id` o incluso agregar una propiedad  tipo `slug`.

El cambio no pasa sólo por cambiar las strings descritas en nuestro script [`build`](https://github.com/Laboratoria/bootcamp/blob/main/scripts/build.js) sino que incluso esa _porción_ de información _debería_ ir en los `proyect.yml` de cada proyecto.

Este cambio también conllevaría crear en [`topics`](https://github.com/Laboratoria/bootcamp/tree/main/topics) su propio archivo `data.yml` que también describa a qué track pertenece cada tópico.

**Comment by lupomontero** [comment]
Esto ya está contemplado en #1283, así que tomo la libertad de cerrar este issue
