### ISSUE TITLE
Faltan traducciones de OAs al portugués

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/bootcamp#1140]
Estas traducciones faltan. Por ahora, para efectos de las hojas de tracking de OAS, he duplicado el título en castellano.
[Aquí llevo mi control](https://docs.google.com/spreadsheets/d/1wD_4l3k1II7xzcHoxSFKc0yyuH6i37KcBieAwfb_mi4/edit#gid=1897245508)

cc @moniyama @mfdebian @lupomontero @lalogf 

key | es
-- | --
ux/user-centricity/centricity | Diseñar un producto o servicio poniendo al usuario en el centro
ux/user-centricity/persistency | Tomar en cuenta las necesidades de los usuarios a lo largo de todo el proceso de diseño
ux/user-centricity/prioritization | Identificar y priorizar usuarios relevantes para el proyecto
ux/business/alignment | Alinear los objetivos del negocio con los del proyecto
ux/business/model | Entender el modelo de negocio
ux/business/goals | Considerar los objetivos del negocio durante el desarrollo del proyecto
ux/business/metrics | Definir métricas relevantes para validar el cumplimiento de los objetivos del negocio
ux/business/benchmark | Entender estado del negocio en relación con el mercado local y global
ux/research/planning | Planificar investigación basada en las necesidades del proyecto
ux/research/support | Elegir y sustentar el \# usuarios que participan en actividades de investigación
ux/research/guidelines | Crear y probar guía de actividades de investigación
ux/research/interview | Realizar entrevistas con usuarios empáticas y sin sesgos
ux/research/documentation | Documentar entrevistas y testeos
ux/research/adaptation | Adaptar plan de investigación de acuerdo a resultados obtenidos
ux/research/sources | Identificar y revisar distintas fuentes de información e inspiración relevantes para el proyecto
ux/research/test | Planear y ejecutar testeos de usabilidad de prototipos en distintos niveles de fidelidad
ux/research/analytics | Utilizar herramientas de analítica
ux/research/cuantitative-data | Analizar e interpretar data cuantitativa
ux/synthesis/weighing | Distinguir observaciones, data y/o respuestas que aportan valor al proyecto
ux/synthesis/patterns | Encontrar patrones en los resultados de la investigación
ux/synthesis/insights | Diferenciar entre insights, hallazgos y observaciones
ux/synthesis/mapping | Mapear experiencias de clientes a través de herramientas de síntesis como el Service Blueprint y/o el Customer Journey Map
ux/synthesis/features | Definir funcionalidades del producto o servicio
ux/synthesis/ideation | Generar múltiples ideas de solución al reto del proyecto
ux/synthesis/feature-prioritization | Priorizar posibles soluciones reto del proyecto basandose en los objetivos del proyecto, las necesidades del usuario y las factibilidad de implementación
ux/product-design/user-flows | Priorizar y proponer flujos de usuario que les ayuden a conseguir sus objetivos con el producto
ux/product-design/content | Identificar y priorizar contenidos relevantes y necesarios para el producto
ux/product-design/fidelity | Diseñar en distintos niveles de fidelidad
ux/product-design/interactivity | Crear prototipos de alta fidelidad que incluyan interacciones
ux/product-design/usability | Diseñar producto o servicio siguiendo mejores prácticas de usabilidad
ux/product-design/accessibility | Diseñar producto o servicio siguiendo mejores prácticas de accesibilidad
ux/product-design/visual-design | Seguir los principios básicos de diseño visual
ux/product-design/component-organization | Construir y mantener una librería de componentes y estilos organizada
ux/product-design/interface-guidelines | Entender y utilizar las guías de interfaces de iOS, Android y Material Design
ux/product-design/project-organization | Nombrar, organizar, agrupar las capas (layers) del diseño siguiendo buenas prácticas
ux/product-design/documentation | Documentar casos de uso para los distintos componentes de la interfaz
ux/product-design/naming | Utilizar nombres de elementos estándares para la plataforma en la que diseña
ux/product-design/handoff | Documentar requerimentos de diseño para equipo de desarrollo utilizando herramientas de handoff
ux/communication/presentation | Presentar y sustentar propuestas a clientes
ux/communication/negotiation | Negociar efectivamente con clientes
ux/communication/relationship-management | Manejar relaciones con clientes
ux/planning/monitor | Organizar y dar seguimiento a actividades a desarrollarse durante el proyecto
ux/planning/prioritization | Priorizar actividades a desarrollarse durante el proyecto
ux/planning/tools | Elegir las herramientas y métodos a utilizar de acuerdo a las necesidades del proyecto
angular | Angular
angular/components-and-templates | Components & templates
angular/structural-directives | Directivas estructurales (ngIf / ngFor)
angular/input-output | @Input \| @Ouput
angular/services | Creación y uso de servicios
angular/routing | Manejo de rutas
angular/observables | Creación y uso Observables.
angular/http-client | Uso de HttpClient
angular/styles | Estilos de componentes (ngStyle / ngClass)
react | React
react/jsx | JSX
react/components | Componentes y propiedades (props)
react/events | Manejo de eventos
react/lists-and-keys | Listas y keys
react/conditional-rendering | Renderizado condicional
react/lifting-up-state | Elevación de estado
react/hooks | Hooks
react/css-modules | CSS modules
react/routing | React Router
vue | Vue
vue/instance | Instancia de Vue.js
vue/data-and-methods | Datos y métodos
vue/components | Uso y creación de componentes
vue/props | Props
vue/directives | Directivas (v-bind \| v-model)
vue/iteration | Iteración (v-for)
vue/events | Eventos (v-on)
vue/computed-props-and-observers | Propiedades Computadas y Observadores
vue/routing | Routing
vue/classes-and-styles | Clases y Estilos
socket-io | Socket.IO
socket-io/client | Cliente JavaScript de Socket.io
socket-io/server | Servidor de Node.js de Socket.io
sql/tables | Creación y modificación de tablas
sql/crud | Operaciones CRUD (Create-Read-Update-Delete)
sql/drop | Borrado de tablas o bases de datos enteras con DROP
postgres | PostgreSQL
postgres/psql | Cliente de terminal psql
postgres/data-types | Tipos de datos
postgres/indexes | Índices
postgres/dump-restore | Respaldo y restauración (backup/restore)
mysql | MySQL
mysql/mysql | Cliente de terminal mysql
mysql/data-types | Tipos de datos
mysql/indexes | Índices
mysql/dump-restore | Respaldo y restauración (backup/restore)
mongodb/crud | Operaciones CRUD (Create-Read-Update-Delete)
mongodb/schemas | Modelos y esquemas de datos
mongodb/dump-restore | Respaldo y restauración (backup/restore)
slack | Slack
slack/slash-commands | Slash commands de Slack
php | PHP
php/data-types/primitive | Tipos de datos primitivos en PHP
php/data-types/arrays | Arrays en PHP (arreglos)
php/data-types/objects | Objetos en PHP
php/variables | Variables en PHP (declaración, asignación, ámbito)
php/control-structures | Estructuras de control en PHP (if, else, elseif, else if, while, do while, for)
php/functions | Funciones en PHP (params, args, return)
php/testing/phpunit | PHPUnit
php/testing/xdebug | XDebug
php/package-management/composer | Composer
wordpress | WordPress
wordpress/plugin-development/hooks | Hooks: action y filter
wordpress/plugin-development/administration-menu | Menús de administración
wordpress/plugin-development/shortcodes | ShortCodes
wordpress/plugin-development/settings | Configuraciones
wordpress/plugin-development/custom-post-types | Custom Post Types
wordpress/plugin-development/taxonomies | Taxonomías
wordpress/plugin-development/users | Usuarios
wordpress/plugin-development/cron | Cron
wordpress/plugin-development/wordpress-rest-api | WordPress REST API
wordpress/plugin-development/wordpress-apis | WordPress APIs
wordpress/plugin-development/wordpress-plugin-directory | Publicar en WordPress Plugin Directory

**Comment by moniyama** [comment]
Lo hice aquí #1138, excepto de UX

**Comment by unjust** [comment]
@mfdebian @unjust revisamos los traducciones pendientes de UX y ver cuales usamos en los proyectos frontend.

**Comment by lupomontero** [comment]
@mfdebian, @unjust: alguna novedad con respecto a este issue?

**Comment by mfdebian** [comment]
Sí! se han traducido ya la mayoría de OAs, por lo menos los de WebDev están revisados y al día, pero desde la apertura de este issue a hoy la currícula de UX fue actualizada, y está aún pendiente traducir los nuevos OAs de UX a portugués (no le habíamos dado prioridad hasta ahora porque no tenemos usuarias de esos OAs en portugués, pero por un tema de "orden" igual deben ser actualizados)

**Comment by lupomontero** [comment]
Gracias @mfdebian 💪

Tendría sentido dar este issue por cerrado y crear uno nuevo específicamente para lo que falta?

**Comment by mfdebian** [comment]
Le daré una revisada más en detalle  :microscope: y en caso de que no falte nada con respecto a este issue haré eso!

**Comment by unjust** [comment]
business, synthesis, communication, planning falta por completo en portugues.
Tache las que hay.

Dos preguntas:
* entonces queremos incluir todo que falta aqui a `pt.yml`, para tener los mismos OAs (no hay nada que NO queremos incluir)
* en la estructura de yaml, muchas de estas OAs no son hijos de `ux` - por ejemplo `research`, `planning`, `business` no son exactamente hijos (ej es `reasearch solo, no `ux/research`)... queremos corregir eso? 

key | es
-- | --
~ux/user-centricity/centricity | Diseñar un producto o servicio poniendo al usuario en el centro~
ux/user-centricity/persistency | Tomar en cuenta las necesidades de los usuarios a lo largo de todo el proceso de diseño
ux/user-centricity/prioritization | Identificar y priorizar usuarios relevantes para el proyecto
ux/business/alignment | Alinear los objetivos del negocio con los del proyecto
ux/business/model | Entender el modelo de negocio
ux/business/goals | Considerar los objetivos del negocio durante el desarrollo del proyecto
ux/business/metrics | Definir métricas relevantes para validar el cumplimiento de los objetivos del negocio
ux/business/benchmark | Entender estado del negocio en relación con el mercado local y global
ux/research/planning | Planificar investigación basada en las necesidades del proyecto
ux/research/support | Elegir y sustentar el \# usuarios que participan en actividades de investigación
ux/research/guidelines | Crear y probar guía de actividades de investigación
ux/research/interview | Realizar entrevistas con usuarios empáticas y sin sesgos
ux/research/documentation | Documentar entrevistas y testeos
ux/research/adaptation | Adaptar plan de investigación de acuerdo a resultados obtenidos
ux/research/sources | Identificar y revisar distintas fuentes de información e inspiración relevantes para el proyecto
~ux/research/test | Planear y ejecutar testeos de usabilidad de prototipos en distintos niveles de fidelidad~
ux/research/analytics | Utilizar herramientas de analítica
ux/research/cuantitative-data | Analizar e interpretar data cuantitativa
ux/synthesis/weighing | Distinguir observaciones, data y/o respuestas que aportan valor al proyecto
ux/synthesis/patterns | Encontrar patrones en los resultados de la investigación
ux/synthesis/insights | Diferenciar entre insights, hallazgos y observaciones
ux/synthesis/mapping | Mapear experiencias de clientes a través de herramientas de síntesis como el Service Blueprint y/o el Customer Journey Map
ux/synthesis/features | Definir funcionalidades del producto o servicio
ux/synthesis/ideation | Generar múltiples ideas de solución al reto del proyecto
ux/synthesis/feature-prioritization | Priorizar posibles soluciones reto del proyecto basandose en los objetivos del proyecto, las necesidades del usuario y las factibilidad de implementación
ux/product-design/user-flows | Priorizar y proponer flujos de usuario que les ayuden a conseguir sus objetivos con el producto
ux/product-design/content | Identificar y priorizar contenidos relevantes y necesarios para el producto
ux/product-design/fidelity | Diseñar en distintos niveles de fidelidad
~ux/product-design/interactivity | Crear prototipos de alta fidelidad que incluyan interacciones~
ux/product-design/usability | Diseñar producto o servicio siguiendo mejores prácticas de usabilidad
ux/product-design/accessibility | Diseñar producto o servicio siguiendo mejores prácticas de accesibilidad
~ux/product-design/visual-design~ | ~Seguir los principios básicos de diseño visual~
ux/product-design/component-organization | Construir y mantener una librería de componentes y estilos organizada
ux/product-design/interface-guidelines | Entender y utilizar las guías de interfaces de iOS, Android y Material Design
ux/product-design/project-organization | Nombrar, organizar, agrupar las capas (layers) del diseño siguiendo buenas prácticas
ux/product-design/documentation | Documentar casos de uso para los distintos componentes de la interfaz
ux/product-design/naming | Utilizar nombres de elementos estándares para la plataforma en la que diseña
ux/product-design/handoff | Documentar requerimentos de diseño para equipo de desarrollo utilizando herramientas de handoff
ux/communication/presentation | Presentar y sustentar propuestas a clientes
ux/communication/negotiation | Negociar efectivamente con clientes
ux/communication/relationship-management | Manejar relaciones con clientes
ux/planning/monitor | Organizar y dar seguimiento a actividades a desarrollarse durante el proyecto
ux/planning/prioritization | Priorizar actividades a desarrollarse durante el proyecto
ux/planning/tools | Elegir las herramientas y métodos a utilizar de acuerdo a las necesidades del proyecto

**Comment by lupomontero** [comment]
Una pregunta @diegovelezg, qué tan urgente o realista es que se abran cohorts de UX en portugués? Pregunto porque quizás esto se puede despriorizar en favor de otras coas que tengamos más urgentes... :thinking:

**Comment by diegovelezg** [comment]
No vemos que vaya a suceder al menos en el siguiente semestre

**Comment by lupomontero** [comment]
En ese caso, habría que identificar qué objetivos de eaprendizaje de UX se usan en los proyectos de WebDev y traducir esos en el corto plazo. Lo demás puede quedar sin traducción, y en el futuro, si se fuera a abrir cohorts de UX en portugués, en ese caso recién abriría un issue para trackear esa necesidad, una vez que existe en el mundo real :stuck_out_tongue_winking_eye:

**Comment by unjust** [comment]
Y amate todo aqui https://github.com/Laboratoria/bootcamp/pull/1287 con la ayuda de Google translate.
Fue mas facil que decidir / separarlos

**Comment by mfdebian** [comment]
@unjust este issue debería ya cerrarse o aún falta algo?
