### ISSUE TITLE
Ocultar proyectos WIP de la pagina de curriculum

### ISSUE THREAD

**Issue by merunga** [Laboratoria/bootcamp#1159]
Desde la presentacion de https://curriculum.laboratoria.la/es/js , esta página se ha convertido en la fuente de referencia para los equipos a la hora de decidir qué proyectos ofrecer.
Hay uno en particular (visitors) q aparece en la pagina pero que [todavia no cuenta](https://github.com/Laboratoria/bootcamp/pull/1118) con las mismas caracteristicas q el resto de proyectos.
Quizas para no confundir habria q quitar estos proyectos q todavia están en proceso de la página o por lo menos marcarlos claramente como WIP.

@mfdebian @lupomontero

**Comment by mfdebian** [comment]
Hace todo el sentido, se ocultarán los que aún estén en WIP del deploy de la plataforma!
