### ISSUE TITLE
Actualizar (y reemplazar) video de Michelle en proyecto cipher

### ISSUE THREAD

**Issue by mfdebian** [Laboratoria/bootcamp#1195]
Actualmente el video que aparece en el README (en ES) del proyecto `cipher` que hizo Michelle, en su momento, está muy desactualizado y contiene un par de imprecisiones, y el de PT no tiene un video realizado por nosotras.

Necesitamos actualizarlos para que reflejen mejor el algoritmo utilizado en el proyecto, y que venga de nosotras.

Como pasos a seguir, se sugiere:

- [x] Encontrar alguna(s) coach(es) que quiera(n) re-grabar el video (tanto en ES como en PT)
- [x] Generar un guión preciso y correcto (y traducirlo a PT)
- [x] Grabar los videos
- [x] Editarlos (pedirle ayuda a Vane y/o Gianfranco?)
- [ ] Reemplazar los videos actuales por los nuevos en sus respectivos README

Issue relacionado: #798

**Comment by mfdebian** [comment]
@reloadercf @JulianaAmoasei Serán las coaches que nos acompañarán a grabar los videos, nos toca entonces ahora escribir `[el guión](https://docs.google.com/document/d/1vSb94gUrqbVWLQV9Twl60q0s3jkAWuP_zwAMD-X-vJM/edit)`.

**Comment by mfdebian** [comment]
@unjust el estado sigue siendo el mismo reportado en el comentario de más arriba, debemos armar el guión para que Carlos y Juliana puedan grabar el video!

**Comment by unjust** [comment]
@mfdebian  pregunto porque vamos a empezar con los proyectos 1 la semana de 20 de Sept, entonces no creo este seria listo por eso...

**Comment by mfdebian** [comment]
@unjust La verdad tampoco sé si es que logremos tenerlo para esa fecha, quizás podríamos ponernos un deadline, si para el 16 de Sept. no tenemos el video (por lo menos el que es en español) para agregarlo al README, vamos descartando que pueda estar integrado ya para DEV001, te parece?
