### ISSUE TITLE
Modificar package.json dependencies vs devDependencies

### ISSUE THREAD

**Issue by nicolaz888** [Laboratoria/bootcamp#1201]
Hola!

En relación a los package.json de los proyectos que lo traen en el esqueleto, creo que es buena idea que vengan con devDependencies ya que lo adecuado es que algunas dependencias solo sean de desarrollo por ejemplo testing, gh-pages, etc

Saludos!

**Comment by mfdebian** [comment]
¡Gracias @nicolaz888!

Creo que me falta un poquito de contexto/conocimiento, siempre lo he pensado como "si es de la etapa de desarrollo (_y no prod_) va en devDependencies", pero me toca investigar un poco más para ver en qué afecta el hecho de que movamos algunas dependencias; Tengo entendido que afecta a la hora de tener la intención de _publicar_ un paquete, y que también existen las peerDependencies y las optionalDependencies, voy a investigarlo un poquito más a profundidad para que, a la hora de realizar un cambio, sea lo más correcto posible.

Aprovecho de preguntar por aquí también, ¿Qué opinas @lupomontero?

Nuevamente mil gracias @nicolaz888 :rocket:

**Comment by lupomontero** [comment]
Gracias por la sugerencia @nicolaz888. Te animas con un PR modificando alguno de los proyectos?

Acabo de revisar los `package.json` de los proyectos y creo que este cambio aplicaría a los siguientes:

- [ ] https://github.com/Laboratoria/bootcamp/blob/96c1f775c4b78e2d5d67175cdc54bb2f53b5e47a/projects/01-cipher/package.json#L15
- [ ] https://github.com/Laboratoria/bootcamp/blob/96c1f775c4b78e2d5d67175cdc54bb2f53b5e47a/projects/01-card-validation/package.json#L15
- [ ] https://github.com/Laboratoria/bootcamp/blob/96c1f775c4b78e2d5d67175cdc54bb2f53b5e47a/projects/02-data-lovers/package.json#L15
- [ ] https://github.com/Laboratoria/bootcamp/blob/96c1f775c4b78e2d5d67175cdc54bb2f53b5e47a/projects/02-emergency-room/package.json#L15
