### ISSUE TITLE
OA's generales sin title

### ISSUE THREAD

**Issue by mfdebian** [Laboratoria/bootcamp#1209]
Actualmente existen algunos OAs _generales_, o que engloban otros OAs _específicos_, que no tienen un `title` en los archivos [es.yml](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/es.yml) o [pt.yml](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/pt.yml).

En el caso de los `title` de estos OAs más _generales_ (o _conceptos_), son el nombre con el cual luego aparecen en la plataforma, por ejemplo, para al OA general `scm`, su `title` es: _Control de Versiones (Git y GitHub)_

Y luego así se ve en la plataforma: 

![Screenshot_2022-08-04_17-46-25](https://user-images.githubusercontent.com/12631491/182958481-94f240e9-6f4f-4aea-b8c7-150e6c8b55b5.png)

Entonces otros OAs _generales_ como `user-centricity` o `product-design` que no tienen un `title` asociado, se ven así:

![Screenshot_2022-08-04_17-48-31](https://user-images.githubusercontent.com/12631491/182958750-99975d52-3a85-403b-b004-3076cd6017ee.png)

Y también conllevan problemas para @diegovelezg a la hora de armar los dashboards de Bootcamp que consumen esta data.

Deben identificarse todas las ocurrencias de eso y arreglarlos.

**Comment by unjust** [comment]
Un poco confuso Las que no tienen `title` como propiedad son muy generales, son los encabezados de objetivos nidos.  Queremos agregar un `title:` a esos?

```
html: HTML
css: CSS
browser: Web APIs
browser/dom: DOM (Document Object Model)
js: JavaScript
ux: UX (User eXperience)
firebase: Firebase
express: Express.js
http: HTTP
auth: Autenticación
webops: WebOps
cicd: Integración Continua/Entrega Continua
db: Bases de datos
sql: SQL
mongodb: MongoDB
postgres: PostgreSQL
mysql: MySQL
react: React
vue: Vue
angular: Angular
slack: Slack
php: PHP
wordpress: WordPress
```
Tambien como dices, no hay una entrada de OA (un encabezado) para `user-centricity` o  `product-design` tal cual para asociar un titulo. (En verdad, `user-centricity` OAS son abajo `UX`.) Estos tienen OAs nidos pero falta un encabezado:
```
user-centricity (es UX ?)
business
research
synthesis
product-design
communication
planning
```

**Comment by mfdebian** [comment]
@unjust exacto, así como dices, la idea es que esos OAs más generales, los encabezados y que nestean los demás, tengan también su `title` en los archivos `es.yml` y `pt.yml`.

Esos que enlistas aquí:
```
user-centricity
business
research
synthesis
product-design
communication
planning
```
Son todos a los que les falta title?

Con respecto a tu pregunta sobre `user-centricity`, es un OA que hace alusión a la UX, pero hay dos OAs más específicos que hacen la diferenciación:
Web-Dev: 
```
user-centricity/centricity:
  title: Diseñar y desarrollar un producto o servicio poniendo a las usuarias en el centro
```
UX:
```
user-centricity/user-oriented:
  title: Involucrar usuarias y tomar en cuenta sus necesidades a lo largo de todo el proceso de diseño
```
Un poco más de contexto sobre eso en este issue #1203
