### ISSUE TITLE
OAs de Notes incluyen Frameworks, pero no eran reflejada en la Mapa de OAs.

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1211]
No se si es un bug en un parte o ya arregló

El proyecto Notes https://github.com/Laboratoria/bootcamp/tree/main/projects/04-notes habla de frameworks y en verdad contiene los OAs de frameworks en su yml https://github.com/Laboratoria/bootcamp/blob/main/projects/04-notes/project.yml#L35

Pero en nuestro cohort no encontramos los OAs en la mapa
![Screen Shot 2022-08-05 at 2 43 32 PM](https://user-images.githubusercontent.com/92090/183149612-0a3183c5-c0c9-44ac-bf94-1f3b93489f45.png)

**Comment by unjust** [comment]
Creo es algo vencido porque al menos en el typeform se parecen.

![Screen Shot 2022-08-08 at 10 49 38 AM](https://user-images.githubusercontent.com/92090/183476218-e32f671b-6fa4-461e-85ee-2bedbfeceba1.png)

**Comment by lupomontero** [comment]
@unjust, pudiste solucionar esto? Imagino que @diegovelezg es la persona que te puede dar un poco de :bulb: en este tema...

**Comment by unjust** [comment]
Investigue en los typeforms porque ya no estamos usando la Mapa de OAs. En el typeform los OAs de frameworks estan para el proyecto Notes. 👍 

Gracias @lupomontero
