### ISSUE TITLE
Revisa links de los READMEs en los proyectos

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1220]
Habia links rotos en los topics que corregimos con #1170.

Seria bueno correr md-links para chequear todo los links de los proyectos.

**Comment by mfdebian** [comment]
Como comentario: para solucionar el issue #1170 se ejecutó el proyecto `md-links` de @lupomontero que se encuentra en [el siguiente fork](https://github.com/lupomontero/md-links/tree/lupomontero), en la rama `lupomontero`
