### ISSUE TITLE
Problema en README de MdLinks

### ISSUE THREAD

**Issue by fakel** [Laboratoria/bootcamp#1228]
https://github.com/Laboratoria/bootcamp/commit/74e1c33df8d961b795d5b7d842863c3744766c41#r84515351

Se agrego una linea de "opcion" en el readme relativo al JS Api, la opción "stats", pero el api sólo recibe la opción "validate" ya que el resultado del api es el insumo del cli para poder sacar esas estadísticas con "stats" directo en el "cli"

**Comment by unjust** [comment]
Si good catch. [Agregue mi 2 cents](https://github.com/Laboratoria/bootcamp/commit/74e1c33df8d961b795d5b7d842863c3744766c41#r85740436).

**Comment by mfdebian** [comment]
veo que al final el culpable era yo! jejeje oopsie
<img src="https://media.giphy.com/media/80TEu4wOBdPLG/giphy.gif" />
