### ISSUE TITLE
Aplica ediciones de DEV001 a README cipher (Proyecto 1) - objetivos generales, checklist etc

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1233]
En DEV001 hicimos algunos cambios al readme cipher (y card validation):

https://github.com/Laboratoria/DEV001-cipher/pull/1

* Un parte de Objetivos Generales
* Un checklist para considerar si estan lista para Project Feedback
* Mover los OAs hacia abajo en el readme
* Nombrar un HIto 1 y HIto 2 en vez de Hacker edicion

Podemos hablar y aplicarlos aqui.

**Comment by mfdebian** [comment]
@unjust Este issue debería ser cerrado en vista que se ha mergeado #1237? o faltan aún cosas? :grin:
