### ISSUE TITLE
Agrega reglas/configuracion de eslint para ayudar en Project Feedback

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1244]
Queremos agregar algunas reglas de eslint en el Proyecto 1 y adelante que va a ayudar recomendar/enforzar buenas practicas

Por ejemplo:
* uso de const/let
* comparison estricta
* indentación

Conversamos que serian aqui!

Recuerda que se levanto esta tema tambien (algo para limitar de uso de innerHTML en un bucle) pero no puedo ubicar un issue...

**Comment by mfdebian** [comment]
Antes de mandar formalmente un PR con los cambios, me gustaría preguntarles un par de cosas, primero, busqué las siguientes reglas con los siguientes valores:
```
    "no-var": "error",
    "prefer-const": "error",
    "eqeqeq": "error",
    "indent": ["error", 2],
```
`no-var` es sobre no utilizar la palabra reservada `var` para declarar variables, mostrándolo como error; En el editor se ve así y recomienda lo siguiente:

![no-var](https://user-images.githubusercontent.com/12631491/198124733-9e671cf0-9a99-440f-b9c8-9db44714bc19.png)

`prefer-const` es sobre no utilizar `let` para declarar variables que luego no van a ser reasignadas, mostrándolo como error; En el editor se ve así y recomienda lo siguiente:

![prefer-const](https://user-images.githubusercontent.com/12631491/198125304-e1320519-704e-4eed-9b55-3e1584e04243.png)

`eqeqeq` es sobre utilizar los 3 caracteres para los operadores de comparación para que sean type-safe, mostrando como error cuando no se utilizan; En el editor se ve así:

![eqeqeq](https://user-images.githubusercontent.com/12631491/198125737-9b28792a-35f1-4d1f-b430-d357cc3972cc.png)

`indent` es para asegurar que se estén utilizando los espacios de indentación declarados, en este ejemplo deberían ser 2, mostrando como error cuando no se cumple; En el editor se ve así:

![indent](https://user-images.githubusercontent.com/12631491/198126254-5b1d656d-fca4-4ed2-9f26-148c564d9f67.png)

La primera pregunta es, les parecen estas reglas o sienten que faltaría alguna más?

La segunda es, asumiendo que ocupamos estas, les parece que está bien que muestren error? por ejemplo la de usar `const` en vez de `let` quizás podría ser sólo un warning? o la de indentación? qué opinan?

La tercera es, para qué proyectos les parece pertinente dejar estas reglas? es algo que queremos dejar sólo para los primeros proyectos? Cuántos? Serían los proyectos de nivel `01` y `02`?

Con respecto a lo de dejar de utilizar `innerHTML` en el Bootcamp, estoy 100% de acuerdo, pero creo que debería venir primero el cambio "cultural" dentro de la organización para que todxs lxs coaches dejen de usarlo (y entender el por qué) antes de pensar en agregar alguna regla así, y no al revés, no sé qué opinan!

cc/ @lupomontero @merunga

**Comment by lupomontero** [comment]
> [...] les parecen estas reglas o sienten que faltaría alguna más?

Me parece un buen punto de partida.

>  [...] les parece que está bien que muestren error? por ejemplo la de usar const en vez de let quizás podría ser sólo un warning? o la de indentación? qué opinan?

Si queremos que de verdad presten atención al estilo, y de verdad nos ayude en los project feedbacks teniendo código estandarizado a nivel de estilo, creo que prefiero que sean _errores_, y que _revienten_ :bomb: :fire: 

> qué proyectos les parece pertinente dejar estas reglas? es algo que queremos dejar sólo para los primeros proyectos? Cuántos? Serían los proyectos de nivel 01 y 02?

Creo que solo deberían afectar a los proyectos de niveles 1 y 2, donde ya incluimos `eslint` pero sin mucha configuración. En el caso de [`social-network` ya se incluye una configuración que extiende la de `airbnb-base`](https://github.com/Laboratoria/bootcamp/blob/v5.4.0/projects/03-social-network/.eslintrc#L8), que es bastante restrictiva, y en los proyectos siguientes esperaría que sean ya las propias estudiantes las que _deciden_ su propia guía de estilo (configuración de linter).

> Con respecto a lo de dejar de utilizar innerHTML en el Bootcamp, estoy 100% de acuerdo, pero creo que debería venir primero el cambio "cultural" dentro de la organización para que todxs lxs coaches dejen de usarlo (y entender el por qué) antes de pensar en agregar alguna regla así, y no al revés, no sé qué opinan!

La verdad no estoy seguro sobre este tema de _dejar de utilizar_ o _prohibir_ `innerHTML`... :thinking: ... en muchos casos (por lo general?) es preferible el uso de `document.createElement` y compañía, que nos ofrecen más flexibilidad, además de referencias a los nodos sin tener que usar selectores a posteriori, pero también hay casos donde hace más sentido usar `innerHTML` y dejar que el browser se encargue de parsear (para subárboles que se expresan más fácilmente en HTML y no requieren de mucha manipulación dinámica).

**Comment by unjust** [comment]
Gracias @mfdebian para mover la conversación. Estoy en acuerdo con @lupomontero:

Preferimos errores, con Proyecto 1 y 2 porque tenemos un config bien basico. 
No quiero prohibir `innerHTML` - nada estricta como asi, pero mas que levantar un warning o algo si hacen en bucle (para data lovers en particular). Voy a buscar como podemos hacer eso...
