### ISSUE TITLE
Mejoramos instrucciones/READMEs de contributing, deployment, scripts

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1249]
Podemos hacer algunas revisiones si son user friendly - personas pueden encontrar el info (hay varios lugares) y son traducido en portugues tambien.

**Comment by unjust** [comment]
ok voy a ver el contenido de wiki tambien y espero tener un PR la semana que viene.

**Comment by mfdebian** [comment]
update 11/11:

Ivy revisará el archivo de contributing y qué info de nuestra wiki puede ser 'reciclado' para ello.

Alpi se encargará del archivo de deployment y scripts.

Se revisará si será pertinente dividir este issue en otros issues más pequeños con respecto a cada sección en particular.

**Comment by mfdebian** [comment]
En la conversación de nuestro daily, hemos decidido "romper" este issue en los 3 issues que lo componen, procederé a cerrar este issue en favor de estos 3:

- Contributing: #1265 
- Deployment #1266 
- scripts/README.md #1267
