### ISSUE TITLE
Cambio de image in semantic HTML topics 

### ISSUE THREAD

**Issue by moniyama** [Laboratoria/bootcamp#1250]
Olá, 
Gostaria de sugerir uma mudança na imagem que está nos [topics de HTML semântico](https://curriculum.laboratoria.la/pt/topics/html/02-html5/02-semantic-html). 

Na imagem, a tag `<main>` está dentro da tag `<section>`, e isso causou uma certa confusão nas estudantes, já que o oposto (section dentro da main) é o mais usual.

Isso foi identificado por uma estudante e trazido a equipe pelo coach @guilhermependezza

**Comment by lupomontero** [comment]
Totalmente de acuerdo... hasta ahora no me había dado cuenta... :see_no_evil: 

cc/ @mfdebian @unjust
