### ISSUE TITLE
Proyectos sin package.json rompen el script create-cohort-project

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1256]
@DeysiVergara vio eso y puede dar mas detalle.

**Comment by unjust** [comment]
@GenesisMauries puedes agregar tus screenshots?

**Comment by GenesisMauries** [comment]
Tratando de crear un proyecto para bootcamp (labnotes) pero tengo este error 
![error](https://user-images.githubusercontent.com/39414582/202246827-384f99dc-7b12-48f1-b9a3-a4d248c38c7d.jpg) Se crea la carpeta del proyecto con el archivo yml 
![project](https://user-images.githubusercontent.com/39414582/202246938-e23e42c4-0e15-489c-b7b8-b532940d9f59.png)

**Comment by mfdebian** [comment]
Muchas gracias @unjust @GenesisMauries y @DeysiVergara 

Creo que lo que deberíamos hacer, en vez de _agregar_ archivos `package.json` a proyectos que no los necesitan, es modificar nuestra función [`addBootcampInfo`](https://github.com/Laboratoria/bootcamp/blob/838167325c332fae521a704ed2cd27c885962135/scripts/create-cohort-project.js#L94) para que realice un check de si existe en primer lugar un `package.json` asociado, y que sólo se ejecute en case de que sí exista, creo que sería el approach más correcto :smile:

**Comment by unjust** [comment]
@mfdebian 
creo puede generar uno si no existe para tener la metadata si no? quieres que lo haga?

**Comment by mfdebian** [comment]
La razón por la cual optaría por no agregar nuevos `package.json` a los proyectos que hoy en día no los tienen, es (aparte de que no los necesitan) porque, por ejemplo para proyectos como `notes` o `burger-queen` las estudiantes van a estar haciendo uso de comando como el de `create-react-app` el cual generará su propio `package.json` que de todas formas sería el que quedaría asociado al proyecto finalmente

**Comment by mfdebian** [comment]
@GenesisMauries fixed! :star: mil gracias por levantar el error!! :pray:
