### ISSUE TITLE
CUR : Identificador único para cada proyecto, independiente del idioma

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/bootcamp#1259]
Necesitamos un identificador para cada proyecto sin importar su idioma o versión.

Esto nos va a permitir trabajar mejor con montones de datos sociados a proyectos y que queremos ver sin importar el idoma. Hoy me tengo que hacer una pirueta de datos innecesaria y tediosa.

Tiene que ver son office hours, sprint y project checkout, project feedback y OAs, etc etc etc

@mfdebian @unjust

**Comment by mfdebian** [comment]
gracias @diegovelezg :pray: en primer lugar decir que se entiende 100% tu pain y es algo que queremos solucionar; en segundo lugar comento que este issue ya había sido identificado aquí: #1193 y a su vez en él se detallan los issues asociados pertinentes al repo de [curriculum-parser](https://github.com/Laboratoria/curriculum-parser/) de donde provendría la solución, te parece si este issue lo cerramos en favor del issue que te comento? para que no tengamos duplicados?

y aprovecho de comentar que si bien está trackeado de hace un rato, la máquina del día a día nos ha pasado un poco por encima  no hemos podido tener chance de solucionarlo, pero es parte del gran cambio para la currícula versión 6.0, mapeada desde hace unos meses :pray:
