### ISSUE TITLE
CURR: Data Lovers, ¿disclaimer para datos de HP?

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/bootcamp#1272]
No sé qué tan al tanto estén las demás pero la autora de HP es reconocida por comentarios transfóbicos.

Recientemente recibimos este comentario de una estudiante:

_Estamos en el proyecto de data lovers y una de las opciones de data es sobre Harry Potter. He estado sintiendo tensión en el bootcamp cuando se menciona o se sugiere la existencia de JK Rowling, o cuando alguien habla mal de ella. Por lo que he notado creo que es un tema político, que hay opiniones divididas y que opinar de una u otra manera (todas legítimas) puede lastimar directamente o hacer sentir incómodas o inseguras a varias compañeras. No se me ocurre una posible solución (tampoco creo que se deba quitar esa data en particular), pero tal vez es algo que deberían tener en cuenta para evitar algún conflicto en el futuro._

¿Quizás podríamos considerar alguna manera de poner un pie de página o algo a modo de disclaimer para situaciones así?, ¿qué opinan?

cc @mfdebian @unjust  @SamanthaPenilla

**Comment by mfdebian** [comment]
Mil gracias por levantarlo @diegovelezg. Voy a preguntar a algunas BC Managers a ver si es un tema recurrente o más bien fue anecdótico a ese cohort; En caso de que sea algo que se repita harto y esté impactando negativamente la experiencia de las estudiantes buscaré a @SamanthaPenilla para ver qué pasos seguir. :raised_hands:

**Comment by diegovelezg** [comment]
Más allá de la frecuencia, sí me parece que en tèrminos generales, podríamos pensar en un lugar estándar en la estructura para este tipo de consideraciones (notas, observaciones, descargos de responsabilidad, etc.).

En este caso en particular, creo que las estudiantes trans y las autistas que estén al tanto de las barbaridades que dijo se pueden sentir afectadas/insultadas.

**Comment by mfdebian** [comment]
¡Me parece @diegovelezg !

Las BC Managers me comentan que no suele ser tema y hasta ahora no ha generado una mala experiencia, pero de todas formas cada _dataset_ del proyecto viene con su README, voy a buscar a Sam P. para preguntarle cómo podemos conformar ese disclaimer de que Laboratoria no avala ni acepta las opiniones de la autora, para que de cara a las estudiantes quede clarísima desde el comienzo nuestra postura, ¿Te parece?

**Comment by diegovelezg** [comment]
Perfecto! solamente busco que nos "curemmos en salud" y no en enfermedad. Además, como sueño con que nuestro repertorio de proyectos solamente crezca, tambi´ñen me pareció importante pensar en una manera estándar de poner alg´`un tipo de descargos de responsabilidad.

:+1:

**Comment by mfdebian** [comment]
Buenísimo @diegovelezg! :metal: 

Conversamos con @SamanthaPenilla y quedamos en el siguiente disclaimer:

> De acuerdo a los principios de convivencia armónica y diversidad como valor intrínseco que orientan nuestra política de diversidad e inclusión, Laboratoria no condona ni avala los comentarios de la autora de la data utilizada en este dataset del proyecto `data-lovers`.

Te parece mando un PR con ese cambio? o le agregarías/quitarías algo más? :blush:
