### ISSUE TITLE
CUR : prep (MVP) para DEV004

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/bootcamp#1282]
- Agregar los estimados de tiempo (aunque sea hardcoded)
- Revisar estructura de readmes (objetivos geneales y objetivos de aprendizjae específicos)
- CA mínimos y hitos adicionales/popcionales

 Deadlines:
- P1 : lunes 16 de enero
- P2 : viernes 20 de enero
- P3:  lunes 30 de enero

**Comment by icarito** [comment]
@merunga - @MaferAlmeida me pregunta "si podemos continuar con lo que tenemos del proyecto Data Lovers o si hacemos algún cambio?"

**Comment by diegovelezg** [comment]
@mfdebian ojo que este se refiere a "hardcodear". No vamos a ahcer que dependa del 1277 ¿no? Por eso le puse MVP y, si bien solamente menciono esos 3p, debería ser para todo ya que estamos
