### ISSUE TITLE
CUR : proyecto UX preadmisión

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/bootcamp#1290]
# Contexto
Los proyectos DEBEN estar en al repositorio "oficial" de Laboratoria. No pueden vivir en universos paralelos que dificulten transparencia, control de versiones/m ejoras/etc.

Por otro lado, estamos estandaraizando y unificando todo el contenido "oficial" para preadmisión en los GitBooks que publicamos desde [este repositorio](https://github.com/Laboratoria/preadmision)

# Necesitamos
- Mover el proyecto (no reto) de UX para preadmisión desde [este CODA](https://coda.io/d/Pre-admision-UX_dO5Y5-95AFt/Bienvenida_sugW7#_lur07) que debe desaparecer al [repo oficial](https://github.com/Laboratoria/bootcamp)
- No sé si @lisperaza quiere aprovechar de revisar antes de hacerlo.

Esto debe quedar listo para la preadmisión del siguiente cohort de UX que creo que ni siquiera está programado ¿o sí @OfeliaR ?

cc @mfdebian @unjust

**Comment by lisperaza** [comment]
Hola! @diegovelezg prefiero mantenerlo tal cual para el turno 2 de UX005 para mantener igualdad de condiciones entre ambos turnos, pero si hay varios ajustes que me gustaría hacer para el UX006.

**Comment by lisperaza** [comment]
Ya cloné el repo y agregué el proyecto (está en WIP aún, solo quería aprender cómo hacerlo), no sé si tenía que crear un branch, Diego el lunes te busco para aclarar unas dudas de la estructura del Gitbook + proyecto.
