### ISSUE TITLE
Configurar BQ API para ser mas facil correr los e2e

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1293]
**Problema:** Hay menos estudiantes (y coaches) tomando BQ API, reduciendo la diversidad de perfiles
**Hipotesis:** Aun hay bloqueos grande en cumplir y acompañar el proyecto, lo mas grande es e2e tests con mongo. Si entregamos el proyecto mas directo para hacer e2e con mongo, mas estudiantes pueden realizar el proyecto (con menos coaching.)
**Medir:** En un cohort en particular, medimos si hay incremento de estudiantes que toman y los sprints que usan (quiza buscar cuanto fue de e2e). Por ejemplo en DEV001 solo tuvimos 1.

-----
Ayer estuve con @fakel ayudando un estudiante por una hora para configurar su e2e con [jest-mongodb](https://github.com/shelfio/jest-mongodb)

Hay dos puntos dificil (como yo entiendo):
- hay que buscar como llamar `globalSetup` de `shelf` en el `globalSetup` de proyecto. No encuentro una manera extensible para los dos `globalSetup` puede coexistir y correr en orden.
- el comando para spawn el proceso tiene errores (creo en algunas OS de Windows)

Pensamos que seria mejor limitar la decisión de base de datos a `mongo-db` y entregar el proyecto con un implementación de `globalSetup` con `jest-mongodb`.

O si no, al menos una pagina mas de documentación porque para dejar eso al memoria y guia especifica de coaches toma mucho energia y tiempo de nosotros.

Usamos este trabajo como ejemplo de un proyecto de estudiante:
https://github.com/gabriela-pzambrano/DEV001-burger-queen-api/commit/65cb9583768a3493f36ff9738f1d0a3913d4121d#diff-a61361d28e86e6e0e0714c3553c789edbee0e9cff4fd3ba31e497697ed100f5cR3

Y este linea [para windows](https://github.com/Shirley-Aguilar-Aguilar/LIM017-burger-queen-api/commit/a62c4a2223125cdb700915dce58476e0285c7c32#diff-a61361d28e86e6e0e0714c3553c789edbee0e9cff4fd3ba31e497697ed100f5cR111)

Hable con @merunga que seria bueno ofrecer un version mongo y un version MySQL. 
Pero prioridad con mongo primero.

**Comment by unjust** [comment]
Seria bueno corregir / verificar algunos de estes puntos listado aqui https://github.com/Laboratoria/bootcamp/issues/1072

**Comment by merunga** [comment]
El problema de por qué el proyecto no venia originalmente configurado, era porque la estudiante debia decidir q DB usaba. Pero en el caso de mongo, yo siempre he usado [mongodb-memory-server](https://www.npmjs.com/package/mongodb-memory-server) para los tests E2E.
