### ISSUE TITLE
DL con broken image

### ISSUE THREAD

**Issue by moniyama** [Laboratoria/bootcamp#1296]
Hola!
No se si ya lo habeis visto, pero la imagen del preambulo del proyecto `data-lovers` esta rota... 

Tampoco sé si puedo abrir un issue sobre eso AJJAJAJAJJA 

Lo siento por no corrigir ahora. Puedo hacerlo más tarde (Quitarlo o cambiar/fix el link del image)

**Comment by mfdebian** [comment]
OMG :scream: tienes tú la imagen que estábamos ocupando @moniyama ? :grimacing:

**Comment by moniyama** [comment]
no la tengo, @mfdebian! Creo que era una image del antiguo lms o algo similar (de un profile para mostrar datos)..

**Comment by mfdebian** [comment]
qué opinan si ponemos una imagen como esta?

![Screenshot_2023-02-10_15-58-39](https://user-images.githubusercontent.com/12631491/218175296-823c75ce-4ae9-47f2-a4c5-ca08d2477778.png)

**Comment by unjust** [comment]
Tampoco recuerdo el imagen original. Creo la imagen que elegiste, @mfdebian, esta bien :)
