### ISSUE TITLE
Agregar títulos de páginas en UI

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#1323]

**Comment by mfdebian** [comment]
@lupomontero a modo de consulta, esto es algo que ya se hace hoy en día en otros proyectos de Laboratoria, no? como para basarnos en ese comportamiento, además, los títulos deberían responder a SEO, en ese caso, será bueno comunicarnos con gabo para establecer esos títulos o es algo que podemos hacer de manera más intuitiva nomas? qué opinas tú?

**Comment by lupomontero** [comment]
Si @mfdebian, la idea es abstraer la implementación actual que usamos en `bootcamp.laboratoria.la` en `@laboratoria/react` y rehusar desde ahí.

**Comment by mfdebian** [comment]
Se probó la implementación de la función `setPage` desde `@laboratoria/react` como se propone, y funciona, pero entonces avanzar con este issue ahora depende de dos cositas:

- [ ] Que efectivamente esté correcto y se apruebe la propuesta en el [PR de `@laboratoria/react`](https://github.com/Laboratoria/react/pull/14)

- [ ] Con @unjust creemos que sería bueno que se involucre gabo (o alguien) del equipo de comms. para crear los títulos y descripciones para que respondan a buenas prácticas de SEO y accesibilidad (y no sea algo que hacemos por intuición). ya le escribí a gabo, pero justo anda de vacaciones :see_no_evil: tendremos que esperarlo un poco.

**Comment by unjust** [comment]
Ahora que el componente `setPage` esta expuesto en @laboratoria/react, el siguiente paso seria usarlo [en un componente](https://github.com/Laboratoria/bootcamp/blob/main/src/components/App/index.jsx) de curricula, con algunas ideas de titulos (quiza de gabo)?

**Comment by mfdebian** [comment]
mergeando [este PR ](https://github.com/Laboratoria/bootcamp/pull/1390) se cerraría el issue de agregar `titles`, pero, para ningún componente/ruta hasta ahora hemos agregado el atributo `description`, para aquello voy a abrir un segundo issue para que podamos ir trackeando su completitud.

Si quieren ver cómo queda, [aquí](https://bootcamp-e078f--pr1409-titles-5dm70jub.web.app/es/) hay un deploy hecho por firebase que durará hasta el 23 de junio.
