### ISSUE TITLE
Typescript con React / OAs de Typescript

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1361]
Para salir con perfiles mas diversos, queremos agregar Typescript tambien to proyectos que tiene React.

Empezamos con BQ API Client para DEV004.

* Agregamos al README la opción a desarollar React+TypeScript
* Agregamos guia/version o recursos como agregar Typescript con React 
   * https://create-react-app.dev/docs/adding-typescript/
   * https://dev.to/nx/react-vite-and-typescript-get-started-in-under-2-minutes-56f
* OAs de Typescript (independiente de Angular)

**Problema:** Diversificación de perfiles, para tener egresadas que puede postular a contratos con Typescript
**Hipotesis:** Si agregamos Typescript al React en un proyecto, salimos con mas que saben Typescript (no solo las que usan Angular)
**Experimento:** Agregamos Typescript a BQ API Client - al readme o un guia, empezando con DEV006.
**Resultado:** Un grupo de egresadas que tienen OAs de React + Typescript.

**Comment by merunga** [comment]
#1398
