### ISSUE TITLE
Nuevo proyecto Nivel 1 para PF descentralizado

### ISSUE THREAD

**Issue by ssinuco** [Laboratoria/bootcamp#1363]
**Problema:** 

Descentralización los PF, es decir que una estudiante pueda agendar un PF con cualquier coach de Laboratoria y no esté limitada a agendar únicamente con las coaches asignadas a su cohorte.  

**Hipótesis:**

Para que la descentralización pueda ser posible, los PF deben tener un formato y agenda estándar y las coaches deben tener lineamientos claros y objetivos sobre cuándo marcar o no marcar un objetivo de aprendizaje. Para lograr esto entonces se debe mejorar los criterios de aceptación de los proyectos y cerrarlos mas sus posibles soluciones.

**Experimento:** 

Crear un nuevo primer proyecto como alternativa a credit card validation y cipher :

- Que elimine la complejidad que suele tener y la distracción que producir el algoritmo de lunh y la fórmula del cifrado cesar
- Que tenga criterios de aceptación claros y detallados para reducir la ambigüedad y subjetividad en el marcado o no marcado de un OA durante el PF
- Que tenga test de integración para probar cada criterio de aceptación

**Resultado:** 

Se espera aplicar este proyecto para DEV009. Se pretende que el PF de este proyecto sea en parte descentralizado.

Implementacion esta https://github.com/ssinuco/01-text-analyzer/

**Comment by unjust** [comment]
El proyecto ya esta parte de curricula, necesito crear nuevo issue para seguir los resultados de experimento
