### ISSUE TITLE
Documentar los hitos o caminos de proyecto Markdown Links, para hacer el proyecto mas alcanzable por estudiantes que se dificulta el proyecto completo.

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1371]
En DEV001 cortamos el proyecto en varios hitos o partes para que las no tiene mucho tiempo o entendimiento como hacer el proyecto

Hicimos por algunos grupos:
1. todo el proyecto API + Cli
2. solo trabajar con un archivo (y no directorio) para quitar la recursividad
3. concentra en el API y no hacer el CLI (o al menos un cli basico que solo llama mdlinks con argumentos fijos)

Hay que documentar estes caminos en alguna manera - en el README o documento adicional de README. Podemos nombrarlos Hitos o Versiones... hay que decidir eso.

**Problema:** Los coaches necesitan cambiar md-links para responder a las niveles y tiempos de cada estudiante. No son bien definidas y necesitamos repetir, comunicar las versiones mucho entre el equipo y con ellas.

**Solucion:** Escribimos los caminos como parte del proyecto para tener claridad cuales son las opciones.

**Resultado:** Menos confusion de los caminos disponibles, mas claridad para ellas cual version estan eligiendo. Conversamos con coaches para ver si hay mas satisfacción y facilidad presentar los opciones. Quiza podemos medir los Sprint Checkouts y los Sprints que toman con las versiones.

**Comment by Davichobits** [comment]
@merunga @ssinuco @unjust dejo [aquí](https://docs.google.com/document/d/1v2P2OBB5FTRvqOrRbY2T4TtbV-PkkWHvXGRjCFcrT7c/edit?usp=sharing) el documento compartido con el borrador de los hitos
