### ISSUE TITLE
Las herramienta de Replit están dando problemas en preadmisión.

### ISSUE THREAD

**Issue by Davichobits** [Laboratoria/bootcamp#1387]
Replit últimamente está dando problemas de memoria. Al parecer, es una nueva característica de Replit. La memoria ahora es limitada y para acceder a más memoria hay que tener la versión de paga.

Hemos probado varias alternativas y la que más nos ha convencido ha sido  [Glitch](https://glitch.com/) 

Sugerimos hacer el cambio para evitar inconvenientes en futuras preadmisiones

**Comment by unjust** [comment]
Ok! En verdad los trivias chocan con la memoria maxima de Replit? O es mas de espacio con imagenes y archivos?

Si es asi, podemos cambiar el Trivia para asegurar Glitch.

**Comment by mfdebian** [comment]
Voy a compartir por acá también los features del tier free de glitch, y también de otra alternativa llamada stackblitz:

Glitch:

- Projects and code are public by default
- Full-stack apps that sleep after 5 minutes
- Unlimited static sites that are always on
- Github import/export and Prettier support

Stackblitz:

-  Unlimited Public projects & GitHub repos
-  StackBlitz Codeflow Beta for Public repos
-  Community support

:shrug: 

De igual forma, estoy 100% de acuerdo con el comentario de @unjust, no importa qué plataforma escojamos, si en ella las postulantes van a estar cargando fotos o videos que ocupen todo el almacenamiento de su proyecto, les va a arrojar error, quizás nos toca conversar sobre poner explícitamente en el enunciado que esa es una práctica que **no** deben hacer (además de cambiar la plataforma).
