### ISSUE TITLE
Al ejecutar el script para generar un repo para una cohort, generar un config file para explaindev

### ISSUE THREAD

**Issue by merunga** [Laboratoria/bootcamp#1391]
El archivo debería llamarse `explaindev.json` en el root del repo y su contenido deberia ser el sgte
```json
{
  "project": "<NOMBRE DEL PROYECTO>",
  "cohort": "<COHORT>"
}
```

**Comment by unjust** [comment]
@mfdebian comentaste que este ya existe? No lo veo.
Creo este archivo tiene que vivir en cada repo de proyecto que generamos.

**Comment by mfdebian** [comment]
En el daily comenté que me parecía que ambos datos, el de el cohort y el del proyecto, ya se podían rescatar desde la URL a un proyecto creado con `create-cohort-project`, (porque el cohort estará en la ruta, y el proyecto dentro del `package.json`) peeeero en realidad luego me di cuenta que no :no_good: porque de hecho hay proyectos, como el de [`notes`](https://github.com/Laboratoria/bootcamp/tree/main/projects/04-notes) que no tienen un `package.json` creado por el script :stuck_out_tongue_closed_eyes: entonces no era realmente válido eso, pero la pregunta que sí le hice a merun por slack, es la de si es que es necesario quizás agregar un tercer atributo de `lang` al archivo `explaindev.json` de manera de darle al bot de antemano el lenguaje en el cual debería estar creando ese mensaje en slack!

**Comment by unjust** [comment]
Voy probando algunas casos localmente.

**Comment by merunga** [comment]
@mfdebian  le llevo la pregunta del idioma al equipo de explaindev. Reabrimos si es necesario
