### ISSUE TITLE
Tutorials para Glitch y Stackblitz

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1399]
Como @DeysiVergara comento en #1397 - hay que hacer tutoriales (videos?) para estes plataformas.

**Comment by DeysiVergara** [comment]
He probado mejor la colaboración en stackblitz y no permite trabajar a la par, al momento que se realizan cambios al mismo tiempo, no junta ambos cambios, si no que pregunta con que versión te quieres quedar. Puede ser fastidioso para las estudiantes que no permita una colaboración mas fluida.

**Comment by mfdebian** [comment]
Mil gracias @DeysiVergara, nos quedamos con Glitch nomas entonces?

**Comment by DeysiVergara** [comment]
Si, porque entre que replit estuvo fallando, codesandbox cobra para tener trabajo en equipo, stackblitz trabaja en equipo pero no sincroniza, lo deje solo en glitch. A los dos turnos de PA que tuvimos les fue bastante bien con glitch, no tuvieron problemas.
