### ISSUE TITLE
create-cohort-project script does not work with job-application project

### ISSUE THREAD

**Issue by moniyama** [Laboratoria/bootcamp#1401]
Hola!

El script no crea el project job-application.
Es creado localmente una copia del proyecto, pero todos los archivos son mantenidos (español y portugués), ocurre un error porque no hay el archivo `proyect.yml` y así, no sube en github

![image](https://github.com/Laboratoria/bootcamp/assets/52083679/c05c485a-47d2-476e-bd72-564014b3f409)

**Comment by merunga** [comment]
@mfdebian revisé si habia sido mi commit de explaindev, pero no está relacionado

**Comment by mfdebian** [comment]
Hola @moniyama! efectivamente, crear ese proyecto con `create-cohort-project` no es uno de sus casos de uso, en ese sentido es un proyecto "especial", que no tiene asociado OA's de `web-dev` del Bootcamp, por tanto es presentado de otra manera por parte del equipo de life skills! :raised_hands:  tengo entendido que así ha sido hasta ahora en todos los cohorts!
