### ISSUE TITLE
Actualizar README de BQ API Client con ultimas recomendaciones sobre uso de mock API

### ISSUE THREAD

**Issue by merunga** [Laboratoria/bootcamp#1406]
Actualmente en el readme se hace referencia a nock, mockoon y json server, pero la recomendacion actual es usar [este  mock](https://github.com/Laboratoria/burger-queen-api-mock/) basado en json-server.
Sólo eso debería detallarse en el README y nada más

**Comment by unjust** [comment]
@merunga me preguntaria un poco el mismo en https://github.com/Laboratoria/bootcamp/issues/1396

Pero en mi opinion es mejor si introducimos este recurso mejor, como primero con un link de json server y decir que pueden forkear el repo si necesario, y por ultimo usa el API ya hecho.

Igual cuando agregamos que pueden hacer su propio content con OpenAI, este mock va a ser mas como ejemplo.
