### ISSUE TITLE
BQ API Client con Typescript (React)

### ISSUE THREAD

**Issue by unjust** [Laboratoria/bootcamp#1407]
Para que las eligen BQ API Client con React, deberian tener la oportunidad aprender Typescript.
Queremos empezar eso con DEV006.

Para agregar al proyecto, necesitamos:
- OAs de typescript
- Guia o recursos como bootstrap este tipo de proyecto ([vite + react + ts](https://dev.to/nx/react-vite-and-typescript-get-started-in-under-2-minutes-56f))
- proyecto de modelo

Problema: Muchas usan React por la ultima proyecto, pero perdimos la aprendizaje de Typescript que normalmente solo viene con Angular. 
Hypothesis: Agregando React + Typescript al proyecto BQ API Client, tenemos mas perfiles con Typescript.

**Comment by merunga** [comment]
@unjust dejé un PR pequeño.
No me gustó mucho el recurso q usa nx
Propuse este: https://itnext.io/create-react-v18-typescript-project-with-vite-d0d602e4a60e

**Comment by merunga** [comment]
@marianaLz @suckak @Adrian0617 
aca esta [el PR](https://github.com/Laboratoria/bootcamp/pull/1408) con los cambios propuestos al README

Y aca el guideline de como iniciar un proeycto con [vite + react + ts](https://itnext.io/create-react-v18-typescript-project-with-vite-d0d602e4a60e) typescript a tu proyecto
