### ISSUE TITLE
Text Analyzer: test getAverangeWordLength

### ISSUE THREAD

**Issue by Freihart512** [Laboratoria/bootcamp#1490]
Basado en esta [conversación](https://claseslaboratoria.slack.com/archives/C058GP6K9NY/p1689863347835969) una estudiante reporta que el cálculo de la prueba está incorrecto, porque el total de caracteres de que la prueba considera está tomando en cuenta los caracteres especiales ( 2 comas y un punto)  pero la realidad es que de manera logica tal como la estudiante reporta ese total no debería considerar esto dado que no son parte de las palabras

**Comment by ssinuco** [comment]
La prueba es correcta. No se debe modificar porque el README advierte de la situacion que indicas. Se especifica lo siguiente:

```
Nota: para simplificar las funcionalidades, definiremos las palabras como un grupos de caracteres separados por espacios. Por ejemplo las palabras del texto de entrada ¡Si, Tú puedes hacerlo! son cuatro:

    ¡Si,
    Tú
    puedes
    hacerlo!
```

Si implementas las funcionalidades especificas, entonces si debes modificar la prueba. Esto tambien se especifica en el README

`Puedes habilitar las pruebas unitarias y en end to end de estos casos en los archivos [test/analyzer.spec.js](https://github.com/Laboratoria/bootcamp/blob/main/projects/01-text-analyzer/test/analyzer.spec.js) y [read-only/test/e2e/app.spec.js](https://github.com/Laboratoria/bootcamp/blob/main/projects/01-text-analyzer/read-only/test/e2e/app.spec.js). También tendrás que ajustar las pruebas ya existentes de las funcionalidades requeridas.`

**Comment by unjust** [comment]
Han hablado que el README no fue ambigua.
