### ISSUE TITLE
Text Analyzer: evento keyup no es adecuado si se mantiene la tecla presionada

### ISSUE THREAD

**Issue by jmontes50** [Laboratoria/bootcamp#1494]
Una estudiante se dio cuenta que l escribir en el textarea planteado si se mantiene presionada la tecla y se escribiran varios caracteres pero no serán contabilizados, probablemente se pueda considerar cambiar al evento input o change para evitar esto.

**Comment by unjust** [comment]
@jmontes50 gracias por llevarlo. Te provoca hacer un cambio para arreglarlo con pull request?

**Comment by jmontes50** [comment]
Lo pongo!, gracias!
