### ISSUE TITLE
Bug: script create-cohort-project can't  add OAS

### ISSUE THREAD

**Issue by reloadercf** [Laboratoria/bootcamp#1506]
The next img by  @AlexisJoselyn print the error
![image (13)](https://github.com/Laboratoria/bootcamp/assets/6140157/d69c1ec8-33f4-44e7-b479-3b5a79d0a4ae)
then I try run the script and the result is likewise in my computer.
<img width="997" alt="Screen Shot 2023-07-31 at 17 08 30" src="https://github.com/Laboratoria/bootcamp/assets/6140157/87b3c717-695e-46f0-8196-8ddd609f4d85">

**Comment by unjust** [comment]
Me parece porque los objetivos ahora estan en 10 (un numero de 2 digitos) el regex no funciona.

Cambie linea 170 a
`  line => /^## \d\d\. Objetivos de aprendiza(je|gem)/i.test(line),` y ahora si.
