### ISSUE TITLE
chore(text-analyzer): Test oas-css

### ISSUE THREAD

**Issue by AlexisJoselyn** [Laboratoria/bootcamp#1518]
¡Hola!, estaba desarrollando Text Analyzer y traigo dos puntos respecto a los test:oas-css.

**1.** Hay una diferencia con el readme, ya que se agregó  _**Todos los selectores CSS de class se usan mas de una vez (60 ms)**_, pero no está especificado en el readme. 

**Aquí la lista del readme que no incluye ese test:**
![image](https://github.com/Laboratoria/bootcamp/assets/88864157/a1e3d664-20d7-4013-ad81-58881eeea082)

**2.** Se me complicó poder pasar específicamente ese test , CSS no es mi fuerte, pero entendí que una clase debería estar en más de un elemento. Considero que esto está bien amplio a interpretación, probé con muchas formas y no me pasaba el test. Me toco ir a probar con consolelog en el archivo del test y solo me funcionó cuando las etiquetas ul y li tienen la misma clase y solo una clase por etiqueta.

**Aquí el error:** 
![image](https://github.com/Laboratoria/bootcamp/assets/88864157/7806bbb0-1974-4b41-a4ab-992977b7c817)

**Aquí el ejemplo en HTML con el que me funcionó:**
![image](https://github.com/Laboratoria/bootcamp/assets/88864157/f4c73a75-814c-42bb-a7ef-096295635e32)

**Aquí pasa el test:**
![image](https://github.com/Laboratoria/bootcamp/assets/88864157/df45ac02-ce83-4ff5-ad63-59777e992885)

**_Gracias, quedo atenta a un hilo por si hay comentarios para el punto 2._**

**Comment by unjust** [comment]
@AlexisJoselyn diria que punto 1 esta implicito en que los selectores de class estan usando en los lis, proque seria usado mas que una vez. 
Punto 2 diria que solo necesario tener el class en los `li` y no en el `ul`. Con eso pasaba igual?
Eso es como interpreto estes puntos, a ver si @ssinuco piensa que hay otro interpretacion.

**Comment by ssinuco** [comment]
Se agregó la prueb " Todos los selectores CSS de class se usan mas de una vez (60 ms), " porque en teoria una clase CSS debe ser definida para ser reutilizada, se que esto es polemico pero se agrego para conversarlo con las estudiantes.

El test pasaria efectivamente si usas class para <li> y el estilo de <ul> lo cambias usando el selector css por elemento.

**Comment by AlexisJoselyn** [comment]
Hola @unjust sobre esto _"Punto 2 diria que solo necesario tener el class en los li y no en el ul. Con eso pasaba igual?"_ Sí pasa, pero se romper el test html.
![image](https://github.com/Laboratoria/bootcamp/assets/88864157/10861d20-3576-4c37-ac7c-23cf2b211380)

**Comment by unjust** [comment]
Ahora me pregunto cual class deberia usar el `ul`? No se si este es necesario. @ssinuco ?

**Comment by ssinuco** [comment]
> Hola @unjust sobre esto _"Punto 2 diria que solo necesario tener el class en los li y no en el ul. Con eso pasaba igual?"_ Sí pasa, pero se romper el test html. ![image](https://user-images.githubusercontent.com/88864157/259180504-10861d20-3576-4c37-ac7c-23cf2b211380.png)

@AlexisJoselyn este si es un bug. Tendriamos que eliminar esa prueba. Te animas a hacer un PR con eso?

**Comment by ssinuco** [comment]
> Hola @unjust sobre esto _"Punto 2 diria que solo necesario tener el class en los li y no en el ul. Con eso pasaba igual?"_ Sí pasa, pero se romper el test html. ![image](https://user-images.githubusercontent.com/88864157/259180504-10861d20-3576-4c37-ac7c-23cf2b211380.png)

@AlexisJoselyn ese tests se eliminó en el ultimo commit. Pudes actualizar tus pruebas de Text Analyzer con la ultima version por fa? probarlo y contarnos si se arreglo?

**Comment by AlexisJoselyn** [comment]
@ssinuco acabo de revisar el último commit de text-analyzer y sigue apareciendo.
![image](https://github.com/Laboratoria/bootcamp/assets/88864157/9966cbf5-53a5-4579-b218-5082a4cfaec6)

@reloadercf tú también tienes los últimos cambios ¿cierto?, me ayudas a corroborar esto, por favor.

**Comment by ssinuco** [comment]
@AlexisJoselyn , estuve revisando en detalle el ultimo commit y la prueba se elimino del archivo `oa-css.spec.js` y no del archivo `oa-html.spec.js`. Lo que reportas efetivamente seria un bug. ¿Te animas a hacer un PR donde se elimine esa prueba para corregirlo?

**Comment by AlexisJoselyn** [comment]
@ssinuco claro que sí. 
Entonces envío un PR quitando este test _it(ul tiene atributo "class"')_

**Comment by ssinuco** [comment]
Si, yo creo que esa es ala solucion. Tienes otra en mente @AlexisJoselyn ?

**Comment by AlexisJoselyn** [comment]
Creo que quitarlo sería lo más sencillo, porque lo otro que se me ocurre es mantenerlo y especificar el test de CSS en el readme para que no se crucen.

**Comment by ssinuco** [comment]
@AlexisJoselyn eliminalo por favor.

**Comment by unjust** [comment]
@AlexisJoselyn en tu pull request pr favor describas bien el bug exacta. Nos cuenta cuando podemos revisarlo!

**Comment by AlexisJoselyn** [comment]
@unjust envié el PR con esta rama _AlexisJoselyn:chore/issue-1518/delete-unit-test-oas-html_
Me comentas si todo ok,, por favor.
