### ISSUE TITLE
Ethical Hacking

### ISSUE THREAD

**Issue by jaiment** [Laboratoria/bootcamp#197]
Hola Comunidad.

¿Existe dentro de la curricula el tema **Ethical Hacking**?
Estoy seguro que debe haber infinidad de temas alrededor de esto, aquí algunos que sugiero:

- Hacking a un RESTful service, cuando tiene o no un JWT.
- Expirar sesiones de usuario.
- SQL Injection.
- Captcha y técnicas para prevenir robots.

Saludos!
c.c. @chamodev  @lupomontero

**Comment by indie-rok** [comment]
Que buena idea!

Yo recuerdo que con un fin de semana y esta web aprendí las bases

https://www.hackthissite.org/

**Comment by lizzie136** [comment]
Hola, esto sería un track diferente al de JS, al menos como lo veo. Me parece super genial. 
Podrían incluirse los _preventive_ como captcha y otras técnicas de prevención que no son __ethical hacking__, pero si son securidad de código.

**Comment by giancorzo** [comment]
Algunos de estos tópicos se podrían rescatar para bootcamp cuando veamos como hacer request y cómo usar APIs.

@ivandevp quizá puedas rescatar alguna de las ideas de aquí

**Comment by lupomontero** [comment]
De hecho, en educación continua también sería chévere tener un curso sobre seguridad que pueda incluir este tipo de cosas. @ivandevp, @chamodev: qué opinan?

**Comment by jaiment** [comment]
Vi este diagrama y me pareció útil incluirlo:

![servlet](https://user-images.githubusercontent.com/6313964/31024808-da0781a4-a505-11e7-9b1d-39159877c645.png)

**Comment by lupomontero** [comment]
... años después... :see_no_evil: 

Esto sería súper interesante como tema para charla ([LimaJS](https://github.com/lima-js/limajs.org#c%C3%B3mo-proponer-una-charla) :wink:), un blog post o una serie de videos en YouTube... pero con toda sinceridad creo que en este momento, en el contexto del Bootcamp de Laboratoria quizás quede un poco fuera de _scope_... :thinking: 

Thoughts?

cc/ @Laboratoria/bootcamp-coaches

**Comment by merunga** [comment]
En el track de FE de Lima, copiandonos de el track de UX, estamos creando una dinámica semanalde  _Lightning talks_ para lograr 2 cosas:
- que las chicas ganen minutos de exposición, hablando en público
- conversar de temas muy importantes de la "cultura" de la programación, pero que quedan despriorizados. Como por ejemplo _ethical hacking_. Aca esta la [lista WIP de temas a exponer](https://docs.google.com/spreadsheets/d/1HUqoVw4-_nKOqWk7Phwk3kGI0_f7jUpNE_sEQagIrWU/edit#gid=2065202259)

**Comment by lupomontero** [comment]
@merunga, cómo les ha ido estos meses con los _Lightning talks_? En caso haya sido, o esté siendo una experiencia positiva, sería chévere ver si es algo que podemos replicar en las demás sedes e incluir formalmente como una _herramienta_ para la ejecución del Bootcamp.

@Laboratoria/bootcamp-coaches: han probado este tipo de dinámicas en otras sedes aparte de Lima?

**Comment by merunga** [comment]
Desde el equipo de formacion consideramos que los lightning talks funcionan super bien, no tanto para poner sobre la mesa temas para discutir, sino mas bien para exponerlas a las estudiantes a la experiencia de exponer en publico.

De las retrospectivas con las estudiantes, ellas tb reconocen que es un experiencia que les "incomoda" pero que es super importante.

**Comment by lupomontero** [comment]
@merunga: podrían compartir de alguna forma la fórmula que están usando para ver cómo podemos replicarla? Esto lo están haciendo tanto en common core como en el track de JS? Y en el track de UX? :thinking: (cc/ @lalogf)

@nerdale, @rafaelbcerri, @CatalinaGuerrero, @OfeliaR: están haciendo algo así en sus sedes? Qué les parece la idea de replicar la dinámica de _lihtning talks_?

**Comment by lupomontero** [comment]
@merunga, te animarías a abrir un issue sobre este tema en el repo de `curricula-ejecución` (:lock:) y continuamos la conversación por ahí?

**Comment by gaposx** [comment]
> Esto lo están haciendo tanto en common core como en el track de JS? Y en el track de UX? 🤔 

Me adelanto a @lalogf, esto se viene ejecutando desde hace ya algunos BCs en el track de UX. Sobre CC, en LIM sólo los tenemos en los tracks.

**Comment by lalogf** [comment]
Como dice @gaposx los lightning talks se vienen dando en el track de UX en todas las sedes hace ya varios BC. La idea era que las estudiantes practiquen más su habilidad para hablar en público y de paso que investiguen temas que sean de su interés o necesidad y se pueda armar un espacio de conversación con el resto de estudiantes y los coaches.

**Comment by merunga** [comment]
@lupomontero :arrow_up:

**Comment by lupomontero** [comment]
Gracias a todxs por los comentarios :black_heart: 

Cierro este issue en favor de https://github.com/Laboratoria/curricula-ejecucion/issues/74
