### ISSUE TITLE
09-paradigms: añadir operador de propagación (spread operator) en unidad 6

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#347]
En la unidad 6 tenemos una lectura sobre `Object.assign`, y en ese contexto quizás tenga sentido introducir el _spread operator_ como alternativa más elegante para componer objetos.

cc/ @carlosroec @rodrwan

**Comment by rodrwan** [comment]
Me gusta mucho esta idea, además, el spread operator, cada día se ve más en librerías nuevas. Y viene de perilla para los siguientes cursos como react y redux. Habría que ver una forma sutil de incluir este operador en esa lección.

**Comment by lupomontero** [comment]
@rodrwan: te animas a hacer una propuesta? La idea sería convertir la _parte_ [Object.assign()](https://github.com/Laboratoria/curricula-js/tree/09-paradigms/09-paradigms/06-composition/03-object-assign) en algo tipo _Object.assign() y el operador de propagación_...

**Comment by lupomontero** [comment]
Se cierra este issue por _inactividad_...
