### ISSUE TITLE
Propuesta de ejercicio a incluir en currícula

### ISSUE THREAD

**Issue by IntiDev** [Laboratoria/bootcamp#421]
<MemoLab> (memorama)

Ejercicio que utiliza CSS, DOM & EVENTOS. Es un pequeño proyecto (incremental) que se trabajó con las chicas en los repasos. Me parece que es un muy buen ejercicio ya que involucra muchas cosas. 

**Les dejo la liga del github pages para que lo prueben:** https://intidev.github.io/proyecto-MemoLab/
**Este es la liga del repositorio:** https://github.com/IntiDev/proyecto-MemoLab

Sigo trabajando en afinar detalles, quedo al pendiente de su feedback. SALUDOS

**Comment by AnaSalazar** [comment]
@IntiDev , excelente propuesta. 

Hay algo que quieras agregar o complementar??

Cómo creerías tú que sería la mejor manera de que se vaya trabajando?

**Comment by lupomontero** [comment]
@IntiDev: gracias por compartir! Sería buenísimo acompañar el ejercicio con una lectura y/o enunciado con instrucciones. Si te animas a hacerlo lo puedes presentar como un pull request a la rama (branch) del curso que corresponda.

💪

**Comment by IntiDev** [comment]
@AnaSalazar Se me ocurrió agregar una especie de marcador :thinking: además de que se podría hacer más dinámico la forma de distribuir las imágenes. También podría trabajarse como el ejercicio de los pandas :sweat_smile:, tal vez 3 versiones para que vayan aplicando los conocimientos adquiridos. ¿Qué opinas?

@lupomontero Me agrada la idea, trabajaré en la propuesta del ejercicio.

**Comment by AnaSalazar** [comment]
@IntiDev A mi me encanta la idea de que sea como el de los pandas, para que vaya incrementando la complejidad según la lección que estén viendo. 

En cuanto tengas la propuesta del ejercicio lo ejecutamos! 💪

**Comment by lupomontero** [comment]
Ha pasado un montón de tiempo desde que se abrió este issue :see_no_evil:  y ha llovido mucho desde entonces :cloud_with_rain: ...

He vuelto a revisar esta propuesta, en particular la [interfaz de la implementación modelo que está publicada en GitHub Pages](https://intidev.github.io/proyecto-MemoLab/) (no hay README) y me parece que podría rescatarse y plantearse como una nueva propuesta de proyecto en el contexto actual del common core de nuestro bootcamp. Quizás hasta podría ser una alternativa a Data Lovers... :thinking:

cc/ @Laboratoria/bootcamp-coaches

**Comment by shirley-startary** [comment]
Estoy super de acuerdo que hayan multiples proyectos para el bootcamp, y que no solo sea uno proyecto, si no una gama de opciones.

**Comment by FabianBravoA** [comment]
> Estoy super de acuerdo que hayan multiples proyectos para el bootcamp, y que no solo sea uno proyecto, si no una gama de opciones.

De hecho, creo que es una necesidad de suma urgencia, varias generaciones han pasado y ya hay una gran cantidad de estudiantes que están buscando proyectos de generaciones pasadas para *inspirarse*. Ir renovando las temáticas manteniendo los objetivos de aprendizaje es sumamente necesario.

**Comment by lupomontero** [comment]
@shirley-startary, @FabianBravoA: Alguno de ustedes (o ambos) se animarían a armar una propuesta de `README.md`, _boilerplate_ e implementación modelo para este proyecto?

**Comment by lupomontero** [comment]
Cierro este issue en favor de #1008 donde se está preparando un PR para finalmente introducir este proyecto :tada:
