### ISSUE TITLE
Project: Cipher - Add Error Cases to the Tests

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#575]
Me tomo la libertad de mover este issue abierto por @levhita en el repo provisional que se usó para _probar_ el reto en el chapter de developers:

> We should add an example of error testing in the boilerplate.

Ver: https://github.com/Laboratoria/cipher/issues/3

**Comment by lupomontero** [comment]
@levhita, @indie-rok o @AnaSalazar, se animarías con esto?

**Comment by AnaSalazar** [comment]
Hola @lupomontero , no me queda claro que es lo que se quiere o a que me debo animar con esto?! 😅
