### ISSUE TITLE
topics(css): mover mini retos fuera de tópico

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#604]
Con respecto a las siguientes _partes_:

* [01-css/11-code-challenges](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css/01-css/11-code-challenges)
* [02-responsive/06-code-challenges](https://lms.laboratoria.la/cohorts/lim-2018-05-bc-core-am/courses/css/02-responsive/06-code-challenges)
* [03-frameworks/07-code-challenges](https://lms.laboratoria.la/cohorts/lim-2018-05-bc-core-am/courses/css/03-frameworks/07-code-challenges)

Quizás estos _retos_ deberían ir en la carpeta `projects`, como proyectos _secundarios_ o menores en los niveles 1 ó 2. Qué piensan?

cc/ @ivandevp

**Comment by lupomontero** [comment]
Esto no es un tema específico del reto 1, así que por ahora lo voy a desasociar del milestone [Bootcamp: Project 1 Go live - 2018-1](https://github.com/Laboratoria/curricula-js/milestone/44) y lo paso al siguiente: [Bootcamp: Project 2, Pre release - 2018-1](https://github.com/Laboratoria/curricula-js/milestone/46).

Se trata de una de esas cosas que _sería chévere si..._, pero no son urgentes. Antes de proceder con esto me gustaría el feedback de @ivandevp.

**Comment by ivandevp** [comment]
Acabo de revisar el issue #571. Si entiendo bien, `Level 0` son los temas de pre-admissión que deben estar disponible, en dicho caso dejaría ahí solo lo referente de `01-css`. Consideraría que `level 1` debería involucrar a `02-responsive` porque recuerdo que en GDL mencionaron que sería bueno asociar este concepto desde el inicio. Y `03-frameworks` tal vez lo dejaría como `level 2`. ¿Qué opinan?

**Comment by brecabal** [comment]
Pienso que podemos moverlos amproject, pero siento que todo está para el nivel 1 , quizás framework novel 2, pero es bastante sencillo una vez que manejan lo anterior, si estpoy de acuerdod e moverlo a project, pero yo dejaría todo para el nivel 1, creo que es algo de lo que  aprendimos del bootcamp pasado

**Comment by lupomontero** [comment]
Yo diría que `01-css` y `02-responsive` en level 1 y `03-frameworks` en level 2, de ahí simpre podemos moverlos...

Se animan a ir moviendo los enunciados a la carpeta `projects/`?

💪 🎸

**Comment by lupomontero** [comment]
@brecabal, @nerdale: alguna novedad con respecto a este issue?

**Comment by lupomontero** [comment]
@brecabal, @nerdale: he sacado este issue del milestone [Bootcamp: Stage 2, Go live - 2018-1](https://github.com/Laboratoria/curricula-js/milestone/47) para poder cerrarlo. Así que este issue queda pendiente sin fecha concreta (baja prioridad). Cómo lo ven?

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue por inactividad.
