### ISSUE TITLE
Detallar (descubrir?) indicadores de performance y validación de aprendizaje para curso React

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#64]
Qué data nos puede ayudar a medir performance y validar aprendizaje?

Hay que explorar las APIs de GitHub, Slack, ... para cómo podemos "medir":

* participación dentro de las sesiones presenciales
* actividad en GitHub (escribiendo código, comentando, creando issues, ...)
* actividad en slack/discourse/so (haciendo y/o contestando preguntas)
* que alcanzaron los objetivos de aprendizaje

**Comment by merunga** [comment]
Este es un tema todavía demasiado abierto como para ponerlo en el repo, pero si quiero dejar aqui plasmado cuáles son las herramientas con las que podemos contar, para empezar a:
- primero a llevar un historico de avance de las alumnas a través de indicadores concretos
- automatizar algunas tareas de scoring de rendimiento para sumar al escalamiento

En este minipost vamos a tratar dos posibles estrategias complementarias de recopilacion de informacion para evaluar a las alumnas.

Primero vamos a arrancar con los facts: valores concretos y precisos obtenidos a través de APIs

## APIs
### Github
Github ofrece desde hace poco la v4 de su api basada en graphql (si les interesa saber por qué gh abandono REST a favor de GraphQL, pueden leerlo [aqui](https://githubengineering.com/the-github-graphql-api/))

La [nueva API de github](https://developer.github.com/v4/), permite averiguar mas o menos lo que queramos. Por ejemplo, dado un usuario podemos averiguar:
- repos propios o ajenos en los que participa, con los commits, issues, pull requests, etc que haya creado
- a quien sigue, quienes lo siguen, stars, watches, etc
- todos sus comentarios 
- ...

Realmente les recomiento que revisen la documentacion de la api, que mas alla de q la usemos o no, es un buen ejemplo de evolucion en el mundo de las apis profesionales.
Y aquellos q no les alcance, hay un [explorer](https://developer.github.com/v4/explorer/) donde uno puede explorar la api usando [graphiql](https://github.com/graphql/graphiql)

### Slack
En slack los administradores de equipo tienen acceso a las [estadísticas](https://get.slack.help/hc/en-us/articles/218407447-Review-team-activity-and-statistics) del mismo.

Luego todas esos datos tb pueden accederse a través de la [API de slack](https://api.slack.com/methods):
- [Channel history](https://api.slack.com/methods/channels.history): Todos los mensajes del canal con timestamp, usuario creador y reactions
- [Group history](https://api.slack.com/methods/groups.history): idem channels
- [Reaction list](https://api.slack.com/methods/reactions.list): dado un usuario, todas las reacciones con timestamp, tipo de reaccion y tipo e indetificador del contenido al cual se reaccionó.
- [Reminder list](https://api.slack.com/methods/reminders.list): dado un usuario, todos los recordatorios creados, con timestamp

### Discourse
Github es la herramienta perfecta para administrar el código, slack es una gran herramienta para comunicación y conversaciones grupales, pero ninguno de las dos son herramientas especialmente diseñadas como foros de discusión y resolución de preguntas.

Es por eso que tb aquí detallo por encima [discourse](http://www.discourse.org/): discourse no es otra cosa más q un motor de foros de discusión. Al igual q el tradicional phpBB es open source, pero a diferencia de este y otros, es mucho mas moderno y mas alineado con la "tendencia" establecida por stackoverflow. He elegido discourse por los siguientes motivos: open-source, alto nivel de madurez y soporte de la comunidad, muy popular, tiene API, existe un SaaS por si no queremos complicarnos la vida con el self-hosting.

Las entidades principales q maneja discourse son las siguientes:
- **topics**: estas pueden ser preguntas, discusiones, ideas, etc, q inician un thread. Estan asociadas al usuario que las creo
- **replies**: estan son las respuestas de un usuario a un topic u otro reply
- **likes**
- **solutions**: si un reply soluciona (cierra) o no el topic
- **badges**: se van asignando a los usuarios a medida q van haciendose usuarios recurrentes.

Y cuenta ademas otras entidades mas comunes como uploads, groups, direct messages

Aquí se pueden ver una pagina con [estadisticas de ejemplo](https://try.discourse.org/u/codinghorror/badges) de un usuario y aqui se puede visitar la [documentacion completa de la api](http://docs.discourse.org/)

### Conclusión APIs
Personalmente creo que con un mashup de todo esto podemos medir:
- participacion digital
- colaboración
- capacidad de autogestion (issues, milestones, projects...)
- y creo lo mas importante de todo, la evolución de las estudiantes mientras van creando su "reputacion", que suele ser un motor muy importante de la colaboración.

## Score cards
Los KPIs q podamos extraer con la info q nos proporcionan las APIs nos dan informacion cuantitativa del desempeño de las alumnas. Ahora vamos a revisar una posible herramienta que nos permita realizar una evaluación cualitativa del desempeño de las estudiantes.

### Code reviews
En el curso de react hemos planteado un formato de leccion + workshop con code reviews semanales, ademas de un code review final. Creo q estas sesiones mano a mano, es lo mas parecido a un examen q tendremos.
Propongo que establezcamos una primera version de un score card para code review, que los reviewers deberan completar luego de cada sesion de review.
Puntos a evaluar pueden ser:
- code quality: semantica, modularizacion y stadarizacion de estilos (q el codigo se pueda leer sin demasiado esfuerzo)
- testeability: si el codigo esta escrito de una manera q es testeable
- avance: comparativa desde el ultimo review
- autogestion, planeamiento y priorizacion: si hay actividad en issues, en la asignacion, se cumplen los deadlines de milestones, la cantidad de issues asignados a cada mientro del equipo es "pareja", si el avance de todos los miembros del equipo es parejo, etc. Tienen claros cuales son los problemas mas importantes por resolver? los saben priorizar y asignarles un responsable?
- funcionalidad: si efectivamente el producto se va acercando al objetivo final
- comunicacion interna y externa: como se conforma el equipo? un lider y dos workers, o de una manera mas distribuida. Como se expresan durante las sesiones

### En el aula / durante las clases
No se si es necesario hacer un score card para esto, pero si quizas estaria bueno determinar a priori que necesitamos q las alumnas hagan durante las clases presenciales. Luego puntuarlas en esos aspectos y ademas tenerlo en cuenta la hora de preparara las clases:
- participacion
- asistencia
- colaboracion
- proactividad
- trabajo en equipo
- capacidad de solucion de problemas

### Producto / Demo
Y finalmente  hay una parte del producto. Para el dia de la demo, los "jueces" tendran tb un score card, que les permitan evaluar los equipos segun una serie de criterios prestablecidos:
- calidad de la solucion (si se cumplen los objetivos del entregable del curso)
- calidad de la presentacion (si las alumnas pueden comunicar su proyecto de una manera clara y profesional)
- factor sorpresa (todo lo que los equipos agreguen por cuenta propia a la solucion o la presentacion, que les confiera un valor diferenciador con el resto)

## Conclusion General
Queda en el tintero definir el peso de cada uno de esos puntos en la "nota final", creo q eso ya depende integramente en qué es lo que queramos premiar o castigar. Y tb analizar si hay datos q nos gustaria tener, pero q no estaríamos capturando

@CaroLaboratoria @chamodev @lupomontero que opinan? Alcanza? Esta lo suficientemente claro? Comentarios?

**Comment by lupomontero** [comment]
Cierro este issue por inactividad... en un futuro no muy lejano comenzaremos a explorar como el API de GitHub nos puede ir proporcionando información de la cual podamos discernir algunos indicadores útiles. Para ello abriremos nuevos issues, en este repo o dónde corresponda.
