### ISSUE TITLE
topics(webpack)

### ISSUE THREAD

**Issue by merunga** [Laboratoria/bootcamp#722]
Siguiendo la linea de babel la idea seria traducir parte de la documentacion oficial.
Podría ser suficiente con la seccion de conceptos: https://webpack.js.org/concepts/

Tb podriamos incluir la seccion sobre configuracion: https://webpack.js.org/configuration
Pero tiene secciones bien pesadas, con mucha API:
- https://webpack.js.org/configuration/output/
- https://webpack.js.org/configuration/module/
- https://webpack.js.org/configuration/resolve/
- https://webpack.js.org/configuration/optimization/
- https://webpack.js.org/configuration/entry-context/
- https://webpack.js.org/configuration/watch/

comentarios @lupomontero

**Comment by lupomontero** [comment]
Al igual que con Babel (#721 ), me parece buena idea las traducciones. Sabes si existe ya algún esfuerzo de internacionalización y/o traducción al español?

Creo que por ahora me limitaría a la sección de conceptos.

Quién se animaría a echar una mano en este esfuerzo?

cc/ @Laboratoria/developers

**Comment by FabianBravoA** [comment]
Misma respuesta que con el #721

**Comment by lupomontero** [comment]
Cierro este issue ya que el consenso es que dirijamos a nuestras estudiantes directamente a la docuementación oficial, y en caso que no haya traducción sumarnos al esfuerzo abierto que ya exista (oficial o no). En este momento no consideramos una prioridad producir este tipo de contenido :cry: 

Como alternativa siempre estamos abiertos a que alguien proponga un jugoso blog post sobre el tema en el blog de [Laboratoria Developers](https://medium.com/laboratoria-developers) :wink:
