### ISSUE TITLE
topics(eslint)

### ISSUE THREAD

**Issue by merunga** [Laboratoria/bootcamp#744]
Personalmente creo q eslint es una de las mejores herramientas con las que contamos en javascript. Es tanto una herramienta para garantizar la calidad del codigo, para hacer mas facil el trabajo en equipo e inclusive aprender aspectos nuevos del lenguaje que desconocias.

Y asi como lo hicimos con los tests en el anterior BC, quizas seria bueno ir metiendo desde temprano este concepto, por lo menos en el track de FE.

Entonces, analogamente a lo que hicimos con babel, que opinan de traducir un poco de eslint?
las paginas que yo traduciría:
- https://eslint.org/docs/user-guide/getting-started
- https://eslint.org/docs/user-guide/configuring
- https://eslint.org/docs/user-guide/command-line-interface
- https://eslint.org/docs/rules/

y opcionalmente
- https://eslint.org/docs/user-guide/formatters/
- https://eslint.org/docs/user-guide/integrations

y adicionalmente una referencia y ejemplo de configuracion de [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb)

comentarios?

@lupomontero

**Comment by lupomontero** [comment]
Me parece una inciativa con un montón de valor para toda la comunidad hispanohablante de usuarios de JavaScript :balloon: 

Para este tipo de esfuerzos podríamos pedir también una mano a las comunidades como LimaJS y Mozilla Perú (entre otras)...

Qué opinan? :thinking: 

cc/ @Laboratoria/bootcamp-coaches @Laboratoria/developers

**Comment by tzkmx** [comment]
En lo personal yo no tenía más que la idea general de los linters hasta hace mucho tiempo, pero luego conocí [standard](https://standardjs.com/) a través de los vídeos de [FunFunFunction](https://www.youtube.com/watch?v=BMUiFMZr7vk&list=PL0zVEGEvSaeEd9hlmCXrk5yUyqUag-n84). Y como evita el bikeshedding, me encantó porque es como el nuevo webpack que no tienes que configurar nada y comienzas a mejorar tu estilo tanto con la corrección automática como con las ayudas que el editor te va indicando tus áreas de oportunidad.

Recién llegué a un equipo donde no usaban ningún linter y pues `standard` así representó la primera oportunidad de empezar a manejar un estilo consistente. No les encanta la idea de quitar los puntos y coma, pero lo importante es que como equipo estamos manejando un estilo en común. Igual está por ahí semistandard, o las reglas de airbnb.

Mi punto es **donde Roma, haz como los romanos**, y conocer herramientas de linting, la que sea para empezar, es importante porque no es hasta la revisión por otro humano, donde obtienes feedback, y evitar lo más posible el trabajo que te distraiga de lo más importante que es: brindar soluciones.

Y entonces pues sí, yo les propondría tomar en cuenta standard (o semistandard, porque las reglas de estilo de laboratoria sí ponen semicolons) como un primer paso, y ya luego entrar en que diferentes equipos tienen diferentes reglas y entonces como tienes que trabajar la configuración del linter (te haya sido dada o tengas que tomar decisiones) para que el estilo no sea oooootra carga más al desarrollador, sino lo que en realidad es: una ayuda para leer tu código y el de los demás, que es lo que vas a hacer la mayor parte del tiempo.

Ah! Y la documentación de standard ya está avanzadísima en la traducción al español. De hecho @cruzmayra me comentaba que muchas de las reglas están en línea con las normas de estilo de Laboratoria, BTW.

**Comment by lupomontero** [comment]
Disculpen por la demora en contestar a este issue... :see_no_evil: 

Desde hace ya un tiempo estamos incluyendo `eslint` en casi todos nuestros _boilerplates_ de proyecto y estamos contentos con los resultados, así que por el momento no sentimos la necesidad de _crear_ o _traducir_ contenido sobre linters. Lo que sí podríamos plantearnos más adelante es considerar `standard` y `prettier` en alguno de los _boilerplates_. Si alguien se anima porfa abran un nuevo issue o PR. Por ahora, en ánimo de limpiar el tracker, me tomo la libertad de cerrar este issue.

Como referencia, esta es la configuración de `eslint` que usamos en los primeros proyectos del Bootcamp:

https://github.com/Laboratoria/bootcamp/blob/master/projects/01-cipher/.eslintrc

Acompañado de una tarea como `npm-script` `pretest`:

https://github.com/Laboratoria/bootcamp/blob/master/projects/01-cipher/package.json#L8
