### ISSUE TITLE
Nuevos topics

### ISSUE THREAD

**Issue by merunga** [Laboratoria/bootcamp#745]
De mi stack personal, otros topics que considero pueden ser interesantes y de los q podria hacerme cargo:
- [eslint](https://github.com/Laboratoria/curricula-js/issues/744)
- jest, para complementar el topic de testing
- react advanced (context api, hooks :fire: , lazy loading, reconciliation, ...)
- react testing (con jest, react-test-renderer y enzyme)
- react-native + expo
- e2e testing: cypress (web) & detox (mobile)
- graphql + apollo
- serverless framework
- mongodb (o nosql en general)
- electron

Y ya si queremos ser exhaustivos en React, 2 frameworks q me encantan
- next.js
- gatsby (como ejemplo de static site generator)

comentarios?

**Comment by lupomontero** [comment]
Gracias por todas las propuestas @merunga :tada: 

Creo que son temas super interesantes para _complementar_ el contenido del Bootcamp, pero quizás sean más de interés general y por ende puede tener sentido plantearlos como blog posts (en medium de Laboratoria Developers), videos en YouTube o píldoras para hacer _live coding_ en el salón.

Qué opinan?

cc/ @Laboratoria/bootcamp-coaches @Laboratoria/developers

**Comment by lupomontero** [comment]
@merunga, retomando este issue... creo que en el planteamiento actual de la currícula quizás esto nos queda ahora fuera de scope, por lo menos la idea de producir contenido sobre estos tópicos.

Por otro lado, un pequeño update a los puntos que planteabas (hace ya más de 6 meses :see_no_evil:).

***

>     * [eslint](https://github.com/Laboratoria/curricula-js/issues/744)

El issue #744 sigue abierto y etiquetado com `help-wanted` :wink: 

***

>     * jest, para complementar el topic de testing

Ya estamos usando `jest` en la mayoría de proyectos, pero todavía falta `cipher` (ver #840). Si alguien se anima con #840 sería un primer paso y podríamos incluir un videito y/o links a recursos en readme del proyecto, que además es el primero en el Bootcamp... :thinking: ...

Por otro lado, creo que también nos podemos apoyar en el blog de Laboratoria Devs para cubrir algunos de estos temas. Por ejemplo:

* https://medium.com/laboratoria-developers/testing-primer-encuentro-d8258ca7abd3
* https://medium.com/laboratoria-developers/arquitectura-de-interfaces-web-parte-1-a41053c2a1f2

***

>     * react-native + expo

A día de hoy tenemos el proyecto [Tic tac toe con React Native](https://github.com/Laboratoria/curricula-js/tree/master/projects/05-tic-tac-toe-rn)... quizás alguien se anima con un videito introductorio que podamos incluir en el `README.md`

***

>     * mongodb (o nosql en general)

Desde hace ya un tiempo tenemos el proyecto [`bq-node`](https://github.com/Laboratoria/curricula-js/tree/master/projects/05-bq-node), ... quizás ese sea el lugar de agregar algo de info (links, texto, video, ...).

***

>     * react advanced (context api, hooks fire , lazy loading, reconciliation, ...)
>     * react testing (con jest, react-test-renderer y enzyme)
>     * e2e testing: cypress (web) & detox (mobile)
>     * graphql + apollo
>     * serverless framework
>     * electron
>     * next.js
>     * gatsby (como ejemplo de static site generator)

Se aceptan propuestas de blog posts para https://medium.com/laboratoria-developers :wink:

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue que está parado hace tiempo y que además en el contexto actual de la currícula ya no tiene tanto sentido... :speak_no_evil: 

Para propuestas de nuevos proyectos o tópicos porfa abran nuevos issues :wink: 

cc/ @juanjordan
