### ISSUE TITLE
Prework review/update. Both, castellano and portugues

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/bootcamp#786]
Hola! @lupomontero @rafaelbcerri @danielasarzosa @rocioalberdi @CaroLaboratoria @vanessapinheiro 

Como saben, parte del contenido del pretrabajo de selección está desactualizado respecto al bootcamp (ES5 a ES6). Eso nos ha obligado a poner un mini taller durante la preadmisión (desperdicio).

Por otro lado, dado que São Paulo estuvo ejecutando un bootcamp de transición, ha tenido casi total independencia respecto a la traducción y contenido, con ayuda de @ivandevp y @MaiaRojas .

Ahora nos toca asegurarnos de que el contenido es consistente con nuestro BC actual, por lo que vengo a pedir lo sgte:

- @lupomontero por favor revisar el contenido actual y sugerir las ediciones/cambios pertinentes, https://github.com/Laboratoria/curricula-js/tree/v1.x/01-intro
- @rafaelbcerri estar atento a lo que diga @lupomontero para revisar7actualizar la traducción a portugués https://github.com/Laboratoria/curricula-js/tree/pt/01-intro
- @rocioalberdi @danielasarzosa @CaroLaboratoria ver cómo manejamos este cambio con todos los procesos corriendo a la vez (OMG).

¿Tiene sentido? Si es así, ¿podemos ponernos un deadline?

Gracias!!

**Comment by rafaelbcerri** [comment]
Para mi hace muy sentido actualizar el contenido para ES6. Aquí en São Paulo hicimos el pretrabajo con ES5 y solamente hicimos un mini taller de ES6 en lo comienzo del Bootcamp

**Comment by diegovelezg** [comment]
@lupomontero este es el issue que te comenté. De hecho, la revisión debería incluir los quiz y ejercicios (están groseramente literales respecto al contenido, creo) cc @rocioalberdi @CaroLaboratoria

**Comment by lupomontero** [comment]
Pregunta tonta (:see_no_evil:)... en el _pre-trabajo_ de admisión seguimos usando `v1.x/01-intro`? Si es así, yo recomendaría pasar a usar:

1. Las dos primeras unidades del tópico de [JavaScript](https://github.com/Laboratoria/curricula-js/tree/master/topics/javascript)
2. La primera unidad del tópico de [CSS](https://github.com/Laboratoria/curricula-js/tree/master/topics/css)
3. La primera unidad del tópico de [HTML](https://github.com/Laboratoria/curricula-js/tree/master/topics/html)

Esto implicaría:

1. Comunicarles a las estudiantes que sólo se espera que vean "esas" unidades.
2. Ver como afecta esto al "tracking" y "evaluación" que hace el equipo de admisión

Si no, siempre podemos revisar/actualizar la rama `v1.x`...

Qué piensan?

cc/ @arku @rafaelbcerri

**Comment by lupomontero** [comment]
Otra alternativa a medio/largo plazo es crear un _tópico_ específico de admisión... :thinking:

**Comment by rafaelbcerri** [comment]
Hey!

So I have no ideia where the content from _prework_ is coming from, I only know that Paloma and Regina were reviewing [this file](https://docs.google.com/document/d/1FWmfVrgYx0p9oglRKcZm8LJmdswLIiccWlxa9IngaPc/edit?ts=5c6c447a#heading=h.855lne3lb9y4) that were used for SAP001.

Right now, Paloma and I are translating the the branch `v2.x` to Portuguese ([pt-v2.x](https://github.com/Laboratoria/curricula-js/tree/pt-v2.x)). We have finished the translation of `CSS` and `HTML` and we are going to start the `JavaScript` translation, so after it we can create a _preadmission_ content using theses contents that you =).

The only problem of it, is that the _prework_ and the _preadmission_ contents will be a little different, be I don't think it is a big deal. What do you think?

cc/ @lupomontero @diegovelezg

**Comment by CaroLaboratoria** [comment]
Hola a todos,

Aporto con un par de cosas:

1) Sobre: "Comunicarles a las estudiantes que sólo se espera que vean "esas" unidades": Creo que sería genial. Las estudiantes se pierden muchísimo en el contenido para el desarrollo del proyecto dentro del LMS, lo que en mi opinión genera mucha ansiedad en esta etapa. Hay cosas como 

2) Sobre "Ver como afecta esto al "tracking" y "evaluación" que hace el equipo de admisión: hasta el minuto no hacemos un tracking del contenido que consumen,  si no que evaluamos el resultado al que llegan con el contenido. Son 3 las instancias que tenemos ahora en este línea: Quiz, ejercicios y proyecto trivia. Sumado a otros parámetros de observación del Jedi, se obtiene el algoritsmo. @rocioalberdi 

3) @rocioalberdi Puedes aclararnos el mix que existe en el contenido de Brasil para el prework y para preadmisión y en qué ramas están por ahora?

**Comment by rocioalberdi** [comment]
Hola a todos!

Les cuento un poco el tema del contenido del prework en Brasil.

Actualmente el contenido de la unidad 00 del prework está en la rama de Brasil. 
https://github.com/Laboratoria/curricula-js/tree/pt/01-intro/00-introduction

El contenido de la unidad 01 que se visualiza en el LMS esta en la rama de Maia. Esto paso así, porque hubo un cambio de contenido en esa unidad que alteraba el prework con contenidos de pre-admisión, por eso la unidad 01 del prework es un poco diferente a la que tenemos en la currícula. 
https://github.com/MaiaRojas/curricula-js/tree/rocio/01-intro

@MaiaRojas me corriges si estoy en lo correcto?

**Comment by rafaelbcerri** [comment]
Oooh!! Now I understand how the things are working 😄 
Thanks for explaining @rocioalberdi I was very confused with it hahaha

But wouldn't be good to have a prework content inside the `pt` branch, so everything about the prework would be there and if we need to update any translation or content, everyone would know where to do it?

**Comment by lupomontero** [comment]
@rafaelbcerri: when do you expect to complete the translation of the `javascript` _topic_ (at least the first two units)? I guess the answer to that question would determine what makes more sense...

On the other hand, all the _equivalent_ content in `v2.x` has already been updated to ES6+ :wink:

**Comment by rafaelbcerri** [comment]
@lupomontero I believe we finish it until next Friday. Thanks for updating the content to ES6+ 🙌 

Right now I'm going to focus on this translation, so maybe we can create an unified branch before next São Paulo Bootcamp 🚀

**Comment by rafaelbcerri** [comment]
@lupomontero how can we create the content for the preadmission, to test it? We have already translated the `html`, `css` and almost all units from `javascript`. It would be good to test theses contents, to be sure that they are working fine 😃

**Comment by MaiaRojas** [comment]
> @lupomontero how can we create the content for the preadmission, to test it? We have already translated the `html`, `css` and almost all units from `javascript`. It would be good to test theses contents, to be sure that they are working fine

Se podría  crear una nueva carpeta para subir solo las unidades que se van a necesitar. :)

**Comment by rafaelbcerri** [comment]
@MaiaRojas I created two folders: [preadmission-content](https://github.com/Laboratoria/curricula-js/tree/pt-v2.x/topics/preadmission-content) and [preadmission-exercises](https://github.com/Laboratoria/curricula-js/tree/pt-v2.x/topics/preadmission-exercises). Can you deploy them, so we can test it?

**Comment by MaiaRojas** [comment]
@rafaelbcerri , I already uploaded it in cohort test:
[LMS](https://lms.laboratoria.la/cohorts/test/courses)
![image](https://user-images.githubusercontent.com/25912510/58493237-1ca15e80-8138-11e9-959b-3c974bd1762b.png)

**Comment by lupomontero** [comment]
See related: https://github.com/Laboratoria/curricula-js/issues/847

**Comment by lupomontero** [comment]
Este issue finalmente ha pasado a mis prioridades confirmadas para este mes (agosto 2019)... así que pronto iré compartiendo updates por acá.

**Comment by chamodev** [comment]
Gracias @lupomontero. Sugiero abordar esto con un marco del _improvement board_ i.e. dejar claro cuál es la condición actual, cuál sería el next target condition y la visión largo plazo. Son muchas cosas que hay que abordar aquí, pero es importante entender el roadmap. ¿Qué hacemos antes de agosto 30? ¿Qué hacemos antes de sep 30? ?Qué tendremos para fin de año?

@rocioalberdi @raulingg

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue ya que la primera revisión sobre este contenido ya se completó hace unas semanas y ha quedado plasmado tanto en este repo como en [`admission-curriculum`](https://github.com/Laboratoria/admission-curriculum/), y es lo que se está actualmente usando en el proceso de selección.

Para el futuro (a medio plazo) volveremos a iterar sobre este material en base a la nueva propuesta que se haga del proyecto de la Trivia de preadmisión en el contexto del trabajo que está haciendo el squad de objetivos de aprendizaje, teniendo en cuenta _todos_ los proyectos.
