### ISSUE TITLE
topic(react): deprecar nuestra documentacion en favor de traduccion oficial

### ISSUE THREAD

**Issue by merunga** [Laboratoria/bootcamp#796]
Dado que ya se hicieron públicos los esfuerzos de traducción al español de `react`, creo que estaria bueno linkear de frente a la documentación oficial, que está actualizada (incluye hooks!) y revisada: [es.reactjs.org](https://es.reactjs.org/)
@lupomontero

**Comment by diegovelezg** [comment]
Se cae de maduro esto.

**Comment by lupomontero** [comment]
Totalmente de acuerdo! Les parece si en futuros _releases_ de la currícula omitimos el _tópico_ de `react`? Habría que ver si hay referencias a estas lecturas desde el _tópico_ de `redux` u otros... y actualizar links en proyectos que mencionan `react` para siempre apuntar a la documentación oficial.

Como referencia, también está la traducción de la documentación oficial en portugués:

https://pt-br.reactjs.org/

Alguien se anima a hacer esta limpieza?

cc/ @lizzie136 @juanjordan @FabianBravoA @rafaelbcerri

**Comment by lupomontero** [comment]
Habiendo pasado ya varios meses desde que se abrió este issue, creo que dado que no estamos manteniendo los _tópicos_ de [`react`](https://github.com/Laboratoria/bootcamp/tree/master/topics/react) y [`redux`](https://github.com/Laboratoria/bootcamp/tree/master/topics/redux), ni usándolos como parte del Bootcamp, propongo las siguientes opciones:

1. Borrar _tópicos_ de `react` y `redux` de este repo
2. Extraer, modernizar y convertir contenido relevante a _blog posts_ en https://medium.com/laboratoria-developers
3. Hacer mantenimiento y modernizar _topicos_ (esta opción creo que realmente no es una opción :speak_no_evil:)

Si alguien se anima con la opción `2` genial. Si no creo que no queda otra que proceder con la pimera opción para evitar estar cargando contenido desactualizado con dependencias desactualizadas...

Thoughts?

cc/ @Laboratoria/bootcamp-coaches
