### ISSUE TITLE
Frameworks Js red social

### ISSUE THREAD

**Issue by Jonhks** [Laboratoria/bootcamp#797]
Tengo una duda y quizá ya se hablo de esto pero no encuentro donde. En la red social este bootcamp solo va a correr una vez y el bootcamp anterior siento que nos funciono muy bien ese proyecto porque la primera vez se hizo sin frameworks ( js )  y después se hizo con React, vue y angular ( En CDMX). Entonces mi duda es, si solo se va a correr una vez, no valdría la pena lanzarlo con la opción de frameworks? O Si esto tiene una razón especifica? También me llama la atención porque después de la Red Social viene Marckdown y después Burguer. Siento que solo tendrían ese proyecto (Burguer) para practicar frameworks. En lo personal creo que saber manejar una librería o framework les aporta mucho. No se si me di a entender

@merunga, @lizzie136, @FabianBravoA, @juanjordan @lupomontero

**Comment by florenciasilva** [comment]
Como opinión personal, ya que el bootcamp que Jonh menciona fue en el que fuí estudiante, me sirvió muchisimo iterar sobre el proyecto de Red Social y poder tener un primer acercamiento a React con algo que ya sabía como funcionaba en VanillaJS.

**Comment by diegovelezg** [comment]
Lo que comenta @florenciasilva es, justamente, la razón por la que lo hicimos el BC anterior. La intención era que la complejidad viniera solamente por el lado del FW y no (PROYECTO NUEVO + FRAMEWORK).

Esta vez, pensamos que BQ como está hoy y en el momento que está planeado, está bien para incorporar FWs.

No creo que sea buena idea meter FWs en la Red Social (3er proyecto) @Jonhks . No por ahora al menos.

**Comment by Jonhks** [comment]
Perfecto, muchas gracias por la respuesta @diegovelezg !

**Comment by lupomontero** [comment]
... llego tarde a la fiesta... pero aprovecho a compartir una idea un poco loca... :stuck_out_tongue_winking_eye: 

Entiendo que algunxs sienten que _rehacer_ un proyecto originalmente Vanilla usando un framework puede ser una experiencia valiosa de aprendizaje por sí misma... pero al mismo tiempo no sé si el proyecto de la red social es el adecuado para ese fin... les parecería muy _loco_ ofrecerles más adelante, en los electivos,  la opción de _rehacer_ su [`cipher`](https://github.com/Laboratoria/curricula-js/tree/master/projects/01-cipher) o [`data-lovers`](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers) usando un framework? Siempre como algo opcional... como _electivo_ junto a a [`bq-node`](https://github.com/Laboratoria/curricula-js/tree/master/projects/05-bq-node) y [`tic-tac-toe-rn`](https://github.com/Laboratoria/curricula-js/tree/master/projects/05-tic-tac-toe-rn)... :thinking: 

cc/ @merunga @lizzie136 @FabianBravoA @juanjordan

**Comment by merunga** [comment]
Ya que estamos en la linea de las ideas locas, aprovecho para compartirles otra idea media loca relacionado con esto

En lima, del feedback del ultimo bootcamp, en la retro de bq el comentario generalizado fue _"si los FW estan tan buenos, por qué esperamos a las ultimas 4 semanas para verlos? por que no comenzamos con esto?"_.

Entonces estamos evaluando cuan factible seria mover ciertos conceptos de FE a CC, y asi red social no tengan que rehacerlo con FW, sino directamente hacerlo con FW.

En resumen: VanillaJS y Browser seria parte de pre-admision y CC, y ya FW y Node seria parte del Track como "especializaciones" desde el comienzo (y ojala en un futuro backend)

Nuestra hipotesis es que los frameworks y librerias nos obligan a incorporar buenas practicas (modularizacion, linting, lifecycles, componentes, manejo de estados, consumo de servicios, empaquetado, tecnicas avanzadas de testeo, lectura e interpretación de documentación tecnica, etc) que repercuten de manera positiva en la manera en la que programamos **en general**, por lo que una mas prolongada exposición a estas herramientas cumplirian tanto el objetivo de especializacion, como de mejora de capacidades tecnicas generales.

Hay muchas aristas del tema, pero actualemente estamos en la etapa de mapeo de conceptos y matcheo de cada uno de ellos a la paleta de proyectos y viendo si este escenario es factible

opiniones, comentarios, warnings?

**Comment by lupomontero** [comment]
@merunga, no me parece mala idea... :thinking: ... ni tan loca :stuck_out_tongue: 

Por otro lado, esta reflexión simpre nos lleva a una contradicción :yin_yang: ... por un lado los frameworks ayudan a seguir buenas prácticas, proveen un entorno más o menos _completo_ y ahorran trabajo; pero al mismo tiempo pueden ocultar o distorsionar el cómo funcionan las cosas y por qué... esto me hace acordar a la ya legendaria batalla entre Vanilla y jQuery como vehículo de aprendizaje...

Llegado a este punto, no sé si tenemos _data_ como para poder decir opción A es mejor que B, ... así que me atrevería a proponer que hagamos el experimento de forma consciente y medible para de acá a una iteración más poder contestar estas preguntas con más sustancia.

Me refiero a que estoy de acuerdo con probar cualquiera de las propuestas, o incluso todas en paralelo, siempre y cuando hagamos el esfuerzo de plantear el _experimento_, la o las _hipótesis_ que queremos verificar/rechazar y los indicadores sugeridos para poder evaluar el experimento después.

Las opciones que se me ocurre podemos probar/comparar:

1. Red Social Vanilla ([como está ahorita](https://github.com/Laboratoria/curricula-js/tree/master/projects/03-social-network#4-consideraciones-generales))
2. Red Social Vanilla o FW (la estudiante elige)
3. Red Social FW
4. Proyecto electivo: Re-implementa tu `cipher` o `data-lovers` usando un FW

cc/ @Laboratoria/bootcamp-coaches 

***

Escribir buen código (completo, entendible y mantenible) sin framework es más difícil, pero escribir mal código es igual de fácil con o sin framework :speak_no_evil:.

**Comment by merunga** [comment]
gracias @lupomontero por el feedback
Estoy sigue estando en la categoria de "proyecto" y durante las proximas semanas, antes del comienzo de LIM010, vamos a tomar la decisión sobre qué hacemos.

De todas maneras, de ejecutarlo va a ser la opcion 2. Inclusive actualmente tenemos chicas que nunca ven FW e implementan sus proyectos de BQ en VanillaJs (un 20% aprox).

**Comment by lupomontero** [comment]
Gracias @merunga, creo que queda claro para la próxima iteración de Lima.

Me encataría saber cómo les gustaría plantearlo en las demás sedes...

cc/ @Jonhks @florenciasilva @FabianBravoA @lizzie136 @juanjordan @rafaelbcerri

**Comment by rafaelbcerri** [comment]
Me gusta de la idea del Red Social com FW pero no se si no sería mucho contenido, porqué acá en Brasil las estudiantes quedaram mucho estresadas com Firebase. Y no se se Firebase + Frameworks seria mucho

**Comment by lupomontero** [comment]
Después de consultar con la almohada creo que voto por la opción `2`:

* `Red Social Vanilla o FW (la estudiante elige)`

Esto implicaría un PR modificando el `README.md`, que por ahora dice esto en la sección de [Consideraciones generales](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/03-social-network#4-consideraciones-generales):

> La lógica del proyecto debe estar implementada completamente en JavaScript (ES6+), HTML y CSS smiley. Para este proyecto **no está permitido utilizar frameworks o librerías de CSS y JS**.

cc/ @Jonhks @florenciasilva @FabianBravoA @lizzie136 @juanjordan @rafaelbcerri
