### ISSUE TITLE
Usar operación de modulo en vez de residuo para Caesar Cipher

### ISSUE THREAD

**Issue by Xpktro** [Laboratoria/bootcamp#798]
Durante mis sesiones de Office Hours en medio del proyecto de una de las estudiantes, llegó a mi atención el detalle particular que el proceso de descifrado no llegaba a funcionar correctamente para offsets negativos. 

Tras comprobar que la fórmula que se estaba usando era _efectivamente correcta_, y luego de algún rato de estar revisando posibilidades llegué a encontrar un sutil detalle que está afectando a la implementación propuesta.

Como parte de la fórmula se utiliza el operador `%` y se refiere a él como el _residuo_. Si bien esto es correcto, la implementación del cifrado de sustitución (Caesar) requiere el uso de **la operación de módulo, que tiene una definición distinta.** Y era la que estaba causando esta frustrante discrepancia a la hora de probar el descifrado (que es un cifrado con desplazamiento negativo). [1]

Entiendo que el propósito final del proyecto no implica para la estudiante el conocer los detalles que subyacen a la aritmética modular, pero estaría bueno indicarlo como algo que se tendrá que enfrentar y ofrecer, de la misma forma en la que se ofreció la fórmula original, una implementación _lista para usar_ de la operación módulo. [2]

En mis pruebas, el uso de la función de módulo resolvió mágicamente el problema de los offsets negativos y me dejó una larga y agradable sonrisa por el resto del día :)

```
const mod = (n, m) => ((n % m) + m) % m;

const substitutionCipher = (string, offset) => 
  string.split('').map((letter, index) => 
    String.fromCharCode(
      mod(letter.charCodeAt(0) - 65 + offset, 26) + 65
    )
  ).join('');

const offset = 123456;
const ciphered = substitutionCipher('ABCXYZ', offset);
const deciphered = substitutionCipher(ciphered, -offset);

console.log(ciphered, deciphered);
// IJKFGH ABCXYZ
```

[1] https://rob.conery.io/2018/08/21/mod-and-remainder-are-not-the-same/
[2] https://stackoverflow.com/a/17323608

**Comment by lizzie136** [comment]
Mucha de la confusión es por cómo se menciona en el video de Michelle como
“módulo” y eso puede que ese otro de esos recursos que requieren
actualizarse.
AFAIK no tenemos operador modulo en JavaScript, solo [Remainder](
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Remainder)

**Comment by jpcode** [comment]
En otros lenguajes el % funciona como módulo, en el caso de Javascript es "signed remainder", para efectos de valores positivos no hay diferencia entre estos operadores, pero en caso de los negativos si, e incluso cambiado el signo de factor arrojará resultados distintos, lo que se conoce en primaria como : Por defecto, Por exceso. Las razones por las diferencia entre lenguajes es por 2 cosas principales: temas prácticos y performance(pero esto si requiere un deep dive aburrido :p).

Saludos.

**Comment by juanjordan** [comment]
Gracias Moises! recuerdo q conversamos de esto en el último Nodeschool. Me parece q no queda otra que replantear el contenido que presentamos a las estudiantes luego de tener esta aclaración, y tenerlo de conocimiento en todos los cohorts para no perpetuar está confusión.

Te animas a enviar un PR agregando tu función de módulo a https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/01-cipher#recursos-y-temas-relacionados?

También podemos considerar grabar un nuevo video con la fórmula actualizada. 🎥

**Comment by lupomontero** [comment]
Gracias @Xpktro, @lizzie136, @jpcode y @juanjordan por los comentarios! :rocket: 

Esto es totalmente cierto... :see_no_evil: 

Quién se anima con un PR (rama `v2.x`) y un nuevo videito... :wink:

**Comment by lupomontero** [comment]
@all-contributors please add @Xpktro for suggesting ideas

**Comment by lupomontero** [comment]
@all-contributors please add @Xpktro for suggesting ideas

**Comment by unjust** [comment]
El resultado de eso es vamos a actualizar el readme con constraints al `offset` para ser numeros positivos y aclarar que estamos usando residuo y no modulo en si. Vamos a agregar un nuevo video en el issue #1195
