### ISSUE TITLE
topics(JavaScript) Remover control de flujos no tan usados en favor de otras opciones no mencionadas

### ISSUE THREAD

**Issue by juanjordan** [Laboratoria/bootcamp#808]
Leyendo https://github.com/Laboratoria/curricula-js/tree/6da61e8497244682c4c0f93c9578380eafe36ca7/topics/javascript/02-flow-control/01-conditionals-and-loops he encontrado que mostramos la existencia de:
- `do...while`
- `break`

pero no mencionamos
- `for...in`
- `for...of`
- `[].forEach`

Si hacemos una búsqueda en todo GitHub para `do..while` y luego para `[].forEach` vemos que hay muchos más resultados para el último:

- `do..while` (28K): https://github.com/search?l=JavaScript&q=%22do+while%22&type=Code
- `[].forEach` (7M): https://github.com/search?l=JavaScript&q=%22forEach%22&type=Code

Se que no es la mejor data pero me gustaría iniciar una conversación al respecto. ☮️

**Comment by lupomontero** [comment]
Gracias por abrir el issue @juanjordan!

Totalmente de acuerdo que deberíamos incluir `for ... in`, `for ... of` y mencionar el concepto de delagar el control de flujo a funciones, tanto a través de métodos de `Array.prototype` como usando recursión, `Promise.all`, ...

Por otro lado, como referencia, en la [unidad de _arreglos_](https://github.com/Laboratoria/curricula-js/tree/master/topics/javascript/04-arrays/03-filter-map-sort-reduce) se habla de `.filter`, `.map` y `.reduce`, y en el _tópico_ de FP hay una [lectura sobre recursividad](https://github.com/Laboratoria/curricula-js/tree/master/topics/functional/05-flow-control/01-recursion).

Te animas a proponer un PR?

cc/ @merunga @lizzie136 @FabianBravoA @rafaelbcerri

**Comment by juanjordan** [comment]
👍 @lupomontero, voy a tratar de encontrar el tiempo para enviar el PR _pero si alguien más se anima a ayudarnos sería genial_, quería compartir otro punto también:

Me parece super importante mencionar la delegación de tareas y demás opciones ya que este _topic_ está disponible para las estudiantes desde Pre-admisión y he notado que en el momento que entienden la sentencia `for` entran en una zona de comfort y se les complica considerar otras herramientas. Algo que he empezado a llamar "for-itis".

He podido ver esta "for-itis" hasta en las entrevistas de Job Application (meses después de Pre-admisión)

Entonces, parte de la intención de esta conversación es la de crear conciencia y actualizar este _topic_ con alternativas para darle visibilidad a estas y reducirle la importancia a `for`. De repente algunas estudiantes encontrarán más cómodo usar `[].forEach` (u otros métodos) desde un comienzo.

Me imagino en el PR podemos hacer referencia (y énfasis de la importancia) a las otras secciones que mencionaste @lupomontero

**Comment by lupomontero** [comment]
Súper buen punto @juanjordan :+1: 

Les parece si dejo el issue abierto pero sin asignar a nadie (todavía) y etiquetado como `help-wanted`?

@juanjordan: :crossed_fingers: ... si encuentras el tiempo :wink:

**Comment by rafaelbcerri** [comment]
Yo no se ayuda, pero año pasado muchas estudiantes hubieran muchas dudas sobre `for ... in`, `for ... of` entonces creamos una pequena parte sobre eso en LMS, [aqui está el cotenido](https://github.com/Laboratoria/curricula-js/tree/pt/02-basic-programming/03-arrays/03-array-iteration).

**Comment by lupomontero** [comment]
@rafaelbcerri, gracias por compartir :yellow_heart: 

Creo que tendría sentido integrar estas cosas dentro de la [lectura más genérica sobre estructuras repetitivas e iteración](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/javascript/02-flow-control/01-conditionals-and-loops) como plantea @juanjordan. Su lectura nos sirve como referencia :smile: 

Los comentarios que haría sobre la [lectura en portugués](https://github.com/Laboratoria/curricula-js/tree/pt/02-basic-programming/03-arrays/03-array-iteration):

* Acotaría que `for ... in` está diseñado para iterar sobre las _propiedades enumerables_ de un _objeto_ y se considera mala práctica usarlo para iterar _arrays_. En el caso de los _arrays_ funciona porque en JavaScript los _arreglos_ son _objetos_, y por defecto sus propiedades enumerables son los índices de los elementos. Consideremos lo siguiente:

```js
> const a = ['a', 'b', 'c'];
undefined
> for (let i in a) { console.log(i); }
0
1
2
undefined
> a.foo = 'bar'
'bar'
> for (let i in a) { console.log(i); }
0
1
2
foo
undefined
```

* Aprovecharía a revisar el _estilo_ de los snippets para que se adecúen a la [guía de estilos que tratamos de usar en Laboratoria](https://github.com/Laboratoria/developers.laboratoria.la/#javascript).
* Agregaría links a documentación oficial (MDN).
* No sé si también menionaría [`Symbol.Iterator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator), que es lo que hay detrás de `for ... of`... :thinking: 

Qué piensan ustedes?

**Comment by shirley-startary** [comment]
Hola @juanjordan, @lupomontero; Estoy muy de acuerdo que incluyamos métodos/temas más actuales como  `for .. in` y `for ... of`, métodos de arreglos etc.
Pero por otro lado, considero que no debemos quita los temas más viejitos, ya que son la base del lenguaje, y tomando en cuenta que muchas de las estudiantes comienzan desde cero, estos temas son un poco más amigable al inicio.
Es mi humilde opinión.

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue por inactividad (desde Nov 2019). De todas formas pronto se estarán revisando todos los tópicos para la versión `v3.x` de la currícula, así que tendremos en cuenta los comentarios de este hilo. Gracias todxs por los comentarios.
