### ISSUE TITLE
links no funcionan en la seccion javascript capitulo de asincronia

### ISSUE THREAD

**Issue by YolandaRib-4** [Laboratoria/bootcamp#809]
Estaba revisando el LMS y dí con este enlace acerca de los ejercicios en el capítulo de asincronia pero no funciona. 

![image](https://user-images.githubusercontent.com/47006006/55428529-7d505880-5546-11e9-914e-686a14f3b86a.png).

Adjunto el enlace.

https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/javascript/08-async/06-practice

**Comment by lupomontero** [comment]
@YolandaRib-4: muchas gracias por reportar esto :star2: y disculpa por la demora en contestar :see_no_evil: 

He estado revisando y parece que estos ejercicios estaban alojados en otro repo que parece haber cambiado y que ha quedado _deprecado_... así que creo que nos toca ver si simplemente los quitamos para evitar confusión, o si los re-emplazamos con nuevas propuestas... :thinking: 

@all-contributors please add @YolandaRib-4 for reporting bug

cc/ @Laboratoria/bootcamp-coaches

**Comment by lupomontero** [comment]
Cierro este issue ya que la parte en cuestión ya se ha quitado de la [unidad de asincronía del _tópico_ de JavaScript](https://github.com/Laboratoria/bootcamp/tree/master/topics/javascript/08-async).

Gracias otra vez @YolandaRib-4 por reportar este problema :1st_place_medal:
