### ISSUE TITLE
project(data-lovers): Archivos "extraños" en carpeta de identidad gráfica

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#838]
En la sección [Resumen del proyecto](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers#2-resumen-del-proyecto) hay un [link a recursos de identidad gráfica para algunas de las fuentes de datos](https://drive.google.com/open?id=1eeWFqrWpy-OYOH4EHDckFGunyrm9iNeE). Este link apunta a una carpeta de Google Drive, y en esta carptea hay varios archivos y carpetas que no sé qué son: `trivia-final`, `Desktop.rar`, `Documento sin título`? Me parece que estos archivos no deberían estar ahí... :thinking: 

![image](https://user-images.githubusercontent.com/110297/58035888-61514800-7aef-11e9-8257-4aae61540c04.png)

Veo que @bosqueinvierno es la _propietaria_ de la carpeta:

![image](https://user-images.githubusercontent.com/110297/58035905-7201be00-7aef-11e9-8982-2e0c1ab7d819.png)

@bosqueinvierno, podrías porfa clarificar qué son esos archivos y si no deberían estar ahí borrarlos de esa carpeta?

**Comment by bosqueinvierno** [comment]
Ni idea qué hacían esos archivos ahí, porque ni siquiera eran míos. Me da la impresión que alguna estudiante los puso ahí por error. Los archivos ya fueron borrados.

**Comment by lupomontero** [comment]
Gracias @aguzro! :rocket: 

Una última consulta, puedes confirmar qué contiene la carpeta `trivia-final`? No parece estar relacionado con el proyecto `data-lovers` :stuck_out_tongue_winking_eye:

**Comment by lupomontero** [comment]
Hola @aguzro,

Veo que la carpeta `trivia-final` todavía aparece dentro de la carpeta de _recursos de identidad gráfica_... podrías porfa confirmar qué es esa carpeta y si la podemos borrar?

Por otro lado, podrías también hacer esta carpeta de _recursos de identidad gráfica_ sea _read-only_ para evitar que se pongan cosas por equivocación?

Gracias :muscle:

**Comment by aguzro** [comment]
Hola @lupomontero, la carpeta ya es _read-only_, no sé por que motivo siguen apareciendo archivos (he corroborado la configuración de la carpeta varias veces ya).
Agradecería si esos recursos pudieran moverse directamente al repositorio del proyecto. También, considerando la evolución que ha tenido el proyecto, no sé si las estudiantes utilizan esos recursos (hay algunos que incluso han desaparecido de la carpeta). Muchas estudiantes realizan el diseño visual del proyecto en base a su propia investigación o gusto, por lo que los recursos serían irrelevantes.
