### ISSUE TITLE
project(card-validation): Re-escribir proyecto de validación de tarjeta de crédito en formato actual

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#839]
Desde hace tiempo tenemos pendiente _re-escribir_ el [proyecto de validación de tarjeta de crédito](https://github.com/Laboratoria/curricula-js/tree/master/projects/000-FIXME/01-card-validation) extraído de la versión `1.x` de la currícula.

La idea es que este proyecto sea una alternativa a [`cipher`](https://github.com/Laboratoria/curricula-js/tree/master/projects/01-cipher) como primer proyecto del Bootcamp. Esto daría más opciones a nuestras estudiantes.

El proyecto necesita un nuevo `README.md` con la estructura que usamos actualmente así como un _boilerplate_ y una _implementación modelo_.

Quiénes se animan con esta _tarea_ :stuck_out_tongue_closed_eyes: 

cc/ @Laboratoria/bootcamp-coaches

**Comment by FabianBravoA** [comment]
¿Puede ser otro? siento que es un poco fome comparado al cipher. Podría
ofrecerme en caso de que si.

**Comment by mfdebian** [comment]
Hola, me estoy atreviendo a contestar un thread de currícula por primera vez, para contar que en SCL tenemos ganas! Como comenta Fabian, al parecer (yo no lo alcancé a conocer) el proyecto estaba un poco fome (comparado con cipher), por lo que intentaremos darle alguna vuelta para hacerlo más entretenido, dinámico o llamativo. ¿Se puede? Soy un poco nuevo y no conozco por completo el conducto regular aún para levantar un tema como este.

¡Saludos a todes!

**Comment by gaposx** [comment]
Hola! me apunto a la iniciativa de preparar el proyecto como alternativa a Cipher.

**Comment by lupomontero** [comment]
@FabianBravoA , @mfdebian, @gaposx: :+1: 

Se animan para conversar entre ustedes y hacer una propuesta conjunta? :ghost: 

Hoy también conversé con @juanjordan y @florenciasilva, quienes también podrían estar interesadxs en participar.

De hecho, conversando con ellxs me pareció que tiene sentido aclarar que **no tiene nesariamente que ser el proyecto de _validación de tarjeta de crédito con algoritmo de Luhn_, podría ser cualquier otra propuesta de SPA que sea de _scope_ y _objetivos de aprendizaje_ equivalentes al [`cipher`](https://github.com/Laboratoria/curricula-js/tree/master/projects/01-cipher)** :wink: . En realidad la intención de este esfuerzo es crear un proyecto (enunciado/boilerplate/impl. model) que sirva como alternativa al [`cipher`](https://github.com/Laboratoria/curricula-js/tree/master/projects/01-cipher), como primer proyecto del Bootcamp.

**Comment by mfdebian** [comment]
@gaposx , @juanjordan , @florenciasilva ¿Me dan sus nombres en Slack para agregarles a un chat para que empecemos a revisar este tema?

¡Saludos a todes!

**Comment by gaposx** [comment]
Enviado por slack ;)

Saludos!

**Comment by juanjordan** [comment]
@juan

**Comment by lupomontero** [comment]
Hola @mfdebian, @gaposx, @florenciasilva y @juanjordan,

Cómo van con este tema? Alguna novedad? Lxs puedo apoyar con alguna cosa?

**Comment by mfdebian** [comment]
¡Hola Lupo!

Sí, creemos que nos podrías apoyar con la identificación de los objetivos de aprendizaje y contenidos específicos, te agrego al channel de Slack

**Comment by lupomontero** [comment]
Hola @mfdebian, con respecto a los objetivos de aprendizaje, creo que deberían de ser _los mismos_ o muy parecidos a [los de `cipher`](https://github.com/Laboratoria/curricula-js/tree/master/projects/01-cipher#3-objetivos-de-aprendizaje), ya que la idea es que este proyecto sea una _alternativa_ al cipher como primer proyecto del Bootcamp.

**Comment by RuthSalvador** [comment]
Hola! @juanjordan quería saber si tenían algún avance de este proyecto, ya que me gustaría revisarlo. Me cuentan! gracias

**Comment by mfdebian** [comment]
¡Hola @RuthSalvador!

La verdad es que hasta ahora no hemos podido avanzar con este proyecto, personalmente quería poder tomarlo con l@s demás, pero lamentablemente hasta ahora no hemos tenido el tiempo para poder hacerlo (enverdad hablo por mi, pero me imagino que a l@s demás les pasó lo mismo), pero sí lo tengo muy presente. Hay un chat de Slack para el desarrollo del proyecto que se llama **proy_tarjetacred**, te puedes integrar, sería genial! Me encantaría poder retormarlo ahora que hay una nueva Coach en SCL y podré tener un poco más de tiempo.

**Comment by lupomontero** [comment]
Hola todxs!

@RuthSalvador ya se animó a proponer un PR (_draft_) con una propuesta para este proyecto: https://github.com/Laboratoria/bootcamp/pull/870 :muscle: :yellow_heart: :rainbow: 

Les parece si continuamos la conversación directamente sobre [el PR](https://github.com/Laboratoria/bootcamp/pull/870)? :wink:

**Comment by RuthSalvador** [comment]
Pueden darle seguimiento a esto en el PR #870

**Comment by lupomontero** [comment]
Cierro este issue en favor de #870
