### ISSUE TITLE
project(cipher): Reemplazar mocha/chai/nyc con jest

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#840]
Esto es una discusión/propuesta que ya ha ocurrido varias veces en persona conversando con varixs coaches. Les parece si nos lanzamos a reemplazar mocha/chai/nyc con [jest](https://jestjs.io/) en el boilerplate de [`cipher`](https://github.com/Laboratoria/curricula-js/tree/master/projects/01-cipher)?

Creo que en paralelo sería una buena oportunidad para revisar las [lecturas de la unidad de testing del tópico de JavaScript](https://github.com/Laboratoria/curricula-js/tree/master/topics/javascript/11-testing) y también actualizar los ejemplos usando jest... :thinking: 

cc/ @Laboratoria/bootcamp-coaches

**Comment by shirley-startary** [comment]
Hola, estoy totalmente de acuerdo que es necesario hacerlo, yo me apunto a realizar el PR con los cambios en el Boilerplate, y conversamos sobre los cambios que sean necesarios en el LMS

**Comment by lupomontero** [comment]
Buenazo @shirley-startary!! :rocket: :star: 

Te he asignado al issue :wink: 

Quedo a la espera de PR. Si tienes cualquier consulta o pregunta no dudes en escribir por acá o buscarme en Slack...

**Comment by betsyvies** [comment]
Hola! Me sumo a la iniciativa, es más agregaría añadir eslint (airbnb) y usar module para exportar e importar funciones en vez de tenerlas como métodos del objeto window, así las acercamos a una forma más real de trabajo.
Espero sus comentarios. @lupomontero

**Comment by shirley-startary** [comment]
Acabo de mandar el PR, aunque requiero ayuda ya que el travis lo está bloquedando, @lupomontero

**Comment by merunga** [comment]
Creo q en esos proyectos el plus de mocha y chai, es q son librerias q corren nativamente en el navegador... con jest se podria intentar hacer lo mismo con cosas como [jest-browser](https://www.npmjs.com/package/jest-browser) pero es un poco raro.

Luego en relacion a lo que comenta @betsyvies me parece genial incluir ES modules desde el comienzo y dejar de usar el global. Nuestra experiencia usand ES modules en red social, en las 3 instancias donde lo hemos aplicado a funciona muy bien y las estudiantes los aman.
Pero si ademas de ES modules queremos usar jest necesitariamos ademas incluir babel para poder soportar ES modules en los tests :dizzy_face: este problema no existe con mocha/chai.

Lo que si podemos hacer sin mucho esfuerzo es configurar desde los primero proyectos, un `eslint` mas util, que tb creo q es de gran ayuda tanto para las estudiantes como para nosotres los coaches que tenemos q hacer muchas horas de code review.

**Comment by lupomontero** [comment]
> Creo q en esos proyectos el plus de mocha y chai, es q son librerias q corren nativamente en el navegador...

@merunga, esa fue la motivación inicial... pero teniendo en cuenta que es su primer proyecto del Bootcamp, me parece más importante la _simplicidad_ de `jest` vs `mocha` + `chai` + `sinon` + `nyc`, y creo que manejar dos entornos (browser y node) distrae del foco principal de aprendizaje, que es familiarizarse con ejercitar el código desde los tests... :thinking: 

El PR de @shirley-startary, está casi a punto... (ver #877)... lo que creo que queda pendiente es terminar de decidir una configuración de `eslint` para tanto `cipher` como `card-validation` (cc/ @RuthSalvador #870), que será una alternativa a `cipher`, y `data-lovers`. Yo propongo adoptar `ES2018` y `type="module"` (ES Modules) nativos en el navegador (como se está haciendo en `social-network`).

```json
{
  "env": {
    "browser": true
  },
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "extends": "eslint:recommended"
}
```

Esto va a requerir algunos cambios pequeños en enunciado y boilerplates para dejar de hablar de _exportar sobre el objeto window_ :speak_no_evil:, y empezar a hablar de `import`/`export` desde el principio...

Otra opción más _opinionated_ podría ser directamente usar `airbnb-base` como guía de estilos en vez de `eslint:recommended`, que es lo que usamos internamente en @Laboratoria a día de hoy (`airbnb` para proyectos con React, y `airbnb-base` para todo lo demás).

Si nadie del equipo de @Laboratoria/bootcamp-coaches se opone yo me animo a mandar PR con los cambios correspondientes en los tres proyectos (`cipher`, `card-validation` y `data-lovers`), y también consideraría el proyecto de la Trivia de preadmisión (cc/ @betsyvies).

Thoughts?

**Comment by lupomontero** [comment]
Para ir avanzando me he tomado la libertad de integrar el PR de @shirley-startary reemplazando `mocha` + `chai` + `nyc` por `jest` (ver #877).

@merunga: crees que tiene sentido mantener `mocha` en `cipher` (y por ende `card-validation`)?

Todavía queda ver si alguien se opone a la propuesta de `ES2018` y `type="module"` para `trivia`, `cipher`, `card-validation` y `data-lovers` (ver [comentario anterior](https://github.com/Laboratoria/bootcamp/issues/840#issuecomment-535695239)).

cc/ @Laboratoria/bootcamp-coaches

**Comment by merunga** [comment]
hola @lupomontero yo estoy a full de acuerdo con unificar el uso de jest y ES modules en todos los proyectos.

Esto no se si ya se esta teniendo en cuenta, pero recordar q como jest corre en node y node no soporta modules de manera nativa, todos lo boilerplates deben incluir la configuracion de babel para poder importar los modules desde los tests.

Se puede tomar como referencia los [`package.json`](https://github.com/Laboratoria/LIM010-social-network/blob/master/package.json) y [`.babelrc`](https://github.com/Laboratoria/LIM010-social-network/blob/master/.babelrc) de `social-network`
