### ISSUE TITLE
i18n: Integrating both langs (es and pt) into a single branch

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#847]
This has been in the pipeline for a while and I believe there is consensus with regards to bringing _all_ translations into a single branch. This is being proposed for many reasons, among them:

* Better visibility of both translations
* Easier to track changes and integrate between translations
* Single build/release/deploy system (in the works)
* Many more...

So, down to the nuts and bolts. As it stands today, this basically boils down to a single decision: _how do we organize the file structure_.

Two main options:

## Isolated (either from root or per project/topic)

The simplest option would be to separate the two langs at the root directoy, each having its own complete subtree with projects and topics.

Pros: no changes to `curriculum-parser`.
Cons: duplicates boilerplates, source code, solutions, ...

Example 1. Isolating langs at the repo's root directory.

```
.
├── es
│   ├── projects
│   └── topics
└── pt
    ├── projects
    └── topics
```

Example 2. Isolating transalations per project/topic

```
.
├── projects
│   └── 01-cipher
│       ├── es
│       │   └── README.md
│       ├── pt
│       │   └── README.md
│       └── README.md
└── topics
```

## Shared dirs

On the other hand, we could take a different approach and instead have both translations inside the same project/topic structure and thus would allow us to share the same dirs and source files such as project boilerplate and excercise solutions and avoid maintaining duplicated files.

Pros: would not affect existing URLs of spanish translation (default lang), prevents duplication, easier to track changes between versions
Cons: requires [minor change in `curriculum-parser`](https://github.com/Laboratoria/curriculum-parser/blob/develop/lib/course.js#L248).

Example 3: Shared dirs
```
.
├── projects
│   └── 01-cipher
│       ├── README.md
│       └── README.pt-BR.md
└── topics
```

My initial inclination is towards the second option (example 3: shared dirs)... :thinking: 

Thoughts?

cc/ @rafaelbcerri @merunga @lalogf 

***

Things to be translated:

* [ ] Main [`README.md`](https://github.com/Laboratoria/bootcamp/blob/master/README.md)

## Projects

* [ ] [Cipher](https://github.com/Laboratoria/bootcamp/tree/master/projects/01-cipher)
* [ ] [Data lovers](https://github.com/Laboratoria/bootcamp/tree/master/projects/02-data-lovers)
* [ ] [Social Network](https://github.com/Laboratoria/bootcamp/tree/master/projects/03-social-network)
* [ ] [Burger Queen](https://github.com/Laboratoria/bootcamp/tree/master/projects/04-burger-queen)
* [ ] [Markdown Links](https://github.com/Laboratoria/bootcamp/tree/master/projects/04-md-links)
* [ ] [Burger Queen Node](https://github.com/Laboratoria/bootcamp/tree/master/projects/05-bq-node)
* [ ] [Tic-tac-toe React Native](https://github.com/Laboratoria/bootcamp/tree/master/projects/05-tic-tac-toe-rn)

## Topics

NOTE: Topics need to be reviewed _first_ as the spanish version is not _ideal_ or up to date. This content is intended to be shared with applicants during the admission process.

* [x] [Browser](https://github.com/Laboratoria/bootcamp/tree/master/topics/browser)
* [x] [CSS](https://github.com/Laboratoria/bootcamp/tree/master/topics/css)
* [x] [HTML](https://github.com/Laboratoria/bootcamp/tree/master/topics/html)
* [x] [JavaScript](https://github.com/Laboratoria/bootcamp/tree/master/topics/javascript)
* [x] [SCM](https://github.com/Laboratoria/bootcamp/tree/master/topics/scm)
* [x] [Shell](https://github.com/Laboratoria/bootcamp/tree/master/topics/shell)

**Comment by rafaelbcerri** [comment]
Integrating braches will be awesome :tada: It will help us a lot with the translation and to create topics together! 

I really like the **Shared dirs** option, the _pros_ that Lupo wrote will make my life as translator much easier and faster :rocket: And I will be happy to help with changes in curriculum-parser

**Comment by lupomontero** [comment]
Hi @rafaelbcerri, any news wrt this issue? When do you think we could expect the first PR with a project readme in portuguese? :speak_no_evil:

**Comment by rafaelbcerri** [comment]
Hey!
Just to be sure before writing the PR, we will use the *Shared dirs* option, right? @lupomontero

**Comment by lupomontero** [comment]
Hi @rafaelbcerri, yes. Let;s go ahead with the _shared dirs_ option. :rocket:

**Comment by lupomontero** [comment]
Things to be translated:

## Projects

* [ ] [Cipher](https://github.com/Laboratoria/bootcamp/tree/master/projects/01-cipher)
* [ ] [Data lovers](https://github.com/Laboratoria/bootcamp/tree/master/projects/02-data-lovers)
* [ ] [Social Network](https://github.com/Laboratoria/bootcamp/tree/master/projects/03-social-network)
* [ ] [Burger Queen](https://github.com/Laboratoria/bootcamp/tree/master/projects/04-burger-queen)
* [ ] [Markdown Links](https://github.com/Laboratoria/bootcamp/tree/master/projects/04-md-links)
* [ ] [Burger Queen Node](https://github.com/Laboratoria/bootcamp/tree/master/projects/05-bq-node)
* [ ] [Tic-tac-toe React Native](https://github.com/Laboratoria/bootcamp/tree/master/projects/05-tic-tac-toe-rn)

## Topics

NOTE: Topics need to be reviewed _first_ as the spanish version is not _ideal_ or up to date. This content is intended to be shared with applicants during the admission process.

* [ ] [JavaScript](https://github.com/Laboratoria/bootcamp/tree/master/topics/javascript)
* [ ] [HTML](https://github.com/Laboratoria/bootcamp/tree/master/topics/html)
* [ ] [CSS](https://github.com/Laboratoria/bootcamp/tree/master/topics/css)
* [ ] [Shell](https://github.com/Laboratoria/bootcamp/tree/master/topics/shell)
* [ ] [SCM](https://github.com/Laboratoria/bootcamp/tree/master/topics/scm)

**Comment by lupomontero** [comment]
The first big milestone wrt this issue has been [today's release of v2.4.0](https://github.com/Laboratoria/bootcamp/releases/tag/v2.4.0), which includes the Portuguese version for the first 6 topics (`browser`, `css`, `html`, `javascript`, `scm` and `shell`) :tada: :balloon: :brazil: 

This new release is now available in the course catalogue in the LMS and the 6 courses (in Portuguese) have been assigned to the current cohort in SPL.

Next week we'll continue with the rest (projects and main readme) :muscle: 

Thanks @rafaelbcerri and @MaiaRojas for the huge effort :1st_place_medal: 

cc/ @CaroLaboratoria @diegovelezg @lalogf @rocioalberdi @chamodev

**Comment by lupomontero** [comment]
I'm closing this issue as the initial integration has now been completed :tada: 

From now on the remaining content to be translated will be translated directly on `master`, the same as future content.

We will now wait for PRs with translated versions of the remaining projects and topics :wink: 

:muscle: :brazil:
