### ISSUE TITLE
project(data-lovers): Add BID open data sources

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#848]
I'm opening this issue as a followup to conversations I've had in person with @mujerdehojalata :wink: 

It would be a nice addition to include open data sources made available by @EL-BID (via https://data.iadb.org/) in our [`data-lovers` project](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers).

For context, this is the second project our students tackle in our 6-month-long Bootcamp, roughly 1 month into the program. For more context check: https://github.com/Laboratoria/curricula-js#etapa-1-common-core

This would imply:

- [ ] Curating/selecting 1 or more _collections_
- [ ] Converting such collections to JSON
- [ ] Normalizing and sanitizing data
- [ ] Adding the data files to [`src/data`](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers/src/data)
- [ ] Adding info about data source and collections in [`README.md`](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers#2-resumen-del-proyecto)
- [ ] Update `tree` output in [technical considerations section](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers#7-consideraciones-t%C3%A9cnicas)
- [ ] Adding commented script tag(s) in [`src/index.html`](https://github.com/Laboratoria/curricula-js/blob/master/projects/02-data-lovers/src/index.html)

cc/ @shirley-startary @Jonhks @mikenieva

**Comment by lupomontero** [comment]
@betsyvies, te animarías a retomar esto?

**Comment by lupomontero** [comment]
Relacionado: #873

**Comment by betsyvies** [comment]
Hola team! Les comento que he estado buscando varios set de datos en el [catálogo de datos del BID](https://data.iadb.org/DataCatalog/Dataset) pero no encontraba una data interesante que tenga datos de años actuales. Luego encontré este [data set ](https://mydata.iadb.org/Education/Learning-Improvement-Information-Center-Regional-I/sqwh-9zsr)con datos de los exámenes PISA. Pero no sé que tanto queramos este tema para las estudiantes.
Este es el API Endpoint https://mydata.iadb.org/resource/sqwh-9zsr.json

@mujerdehojalata Talvez conoces una set de datos más actual u otra página del BID para encpntrarlo. 
@Laboratoria/coaches @lupomontero @Laboratoria/product-managers

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue en favor de la propuesta de @betsyvies en #1040
