### ISSUE TITLE
project(cipher): Quitar expectativas de habilidades quizás irrelevantes para este proyecto

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#858]
Continuando más de un thread dentro del [spreadsheet de la rúbrica](https://docs.google.com/spreadsheets/d/1Tviny8HzskBKP0HDKXoSClqyHsvQTO0XsWnyKWZGvJA), quizás tenga sentido simplificar las expectativas de habilidades desarrolladas en el proyecto, en particular con respecto al linter (`eslint`) y uso de funciones/modularidad, que dado el boilerplate, la expectativa actual se cumple sin hacer nada... :thinking: 

Podríamos obviar dichas habilidades para este proyecto y así concentrarnos en lo que consideramos los objetivos principales de aprendizaje. Por el contrario, otra opción sería subir la expectativa, de tal manera que en vez de quitarlas, exigiríamos un nivel quizás más alto que requiera que tengan que _hacer_ algo.

Cómo lo ven?

cc/ @juanjordan @RuthSalvador @nerdale @lizzie136 @rafaelbcerri

**Comment by adolivaresl** [comment]
(Uuupssss, casi se nos pasa el issue :( no habíamos podido responder antes porque entre tantas cosas con el ongoing se nos fue del radar, mil disculpas por eso.)
En SCL creemos que aumentar las expectativas no es buena idea ya que sería abrumarlas “más” ¿Por qué? porque son personas que se están enfrentando, muchas de ellas, por primera vez a programar, lo cual ya de por sí es abrumante y caótico, por ejemplo en el caso de eslint aumentarles el nivel de requisito puede traer a futuro frustración en el momento en que ellas deban decidir con cual base trabajar (airbnb, google etc) pues en cipher solo deben fijarse en los errores que aparece en la terminal, eso podemos forzarlo en el día a día como parte del aprendizaje y no como una habilidad evaluada en sí. En lo que sí estamos de acuerdo es que no tiene mucho sentido evaluar aquellos puntos en dónde se cumplen automáticamente el logrado al ser elementos dados desde el mismo boilerplate, pareciera crear más falsas expectativas en ellas por una configuración previa que un aprendizaje innato.

**Comment by lupomontero** [comment]
Gracias por los comentarios @adolivaresl :yellow_heart: 

Estoy de acuerdo en que tiene más sentido _quitar_ habilidades (las que ya soluciona el boilerplate) que aumentar expectativas en este primer proyecto.

**Comment by gaposx** [comment]
@lupomontero , @adolivaresl :

¿Cómo verían el tema de eliminar otras habilidades, por ejemplo `Uso de funciones / modularidad` la cual suele tener un valor por defecto al usar los archivos y sugerencias del README/boilerplate?
