### ISSUE TITLE
project(data-lovers): More open data sources?

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/bootcamp#873]
¿Alguno de estos datasets podría servir para dar más libertad-creatividad [al proyecto](https://github.com/Laboratoria/bootcamp/tree/master/projects/02-data-lovers)?
https://www.kaggle.com/datasets

gracias @belencito27 

cc @lupomontero @Laboratoria/bootcamp-coaches

**Comment by lupomontero** [comment]
Como punto de partida, me parece buena idea considerar nuevas fuentes de datos. De hecho tenemos otro [issue abierto con la propuesta/idea de agregar fuentes de datos abiertas del BID](https://github.com/Laboratoria/bootcamp/issues/848).

Teniendo en cuenta que actualmente estamos curando, convirtiendo a JSON y preprocesando las demás fuentes de datos, si alguien se anima a proceder con esto, la idea sería segir los mismos pasos detallados en el otro issue:

- [ ] Curating/selecting 1 or more _collections_
- [ ] Converting such collections to JSON
- [ ] Normalizing and sanitizing data
- [ ] Adding the data files to [`src/data`](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers/src/data)
- [ ] Adding info about data source and collections in [`README.md`](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers#2-resumen-del-proyecto)
- [ ] Update `tree` output in [technical considerations section](https://github.com/Laboratoria/curricula-js/tree/master/projects/02-data-lovers#7-consideraciones-t%C3%A9cnicas)
- [ ] Adding commented script tag(s) in [`src/index.html`](https://github.com/Laboratoria/curricula-js/blob/master/projects/02-data-lovers/src/index.html)

**Comment by diegovelezg** [comment]
Quizás @belencito27 quiera hacer su primera contribución oficial a Laboratoria ;)

**Comment by belencito27** [comment]
Hola a todos,

De nada.. un gusto!

El Bid incluso liberó data en el marco de una competencia kaggle que les
puede servir para los dos propósitos.  Acá el link
https://www.kaggle.com/c/costa-rican-household-poverty-prediction

También les comparto el link a code for development, es un repositorio del
Bid de proyectos con código abierto.  https://code.iadb.org/en/tools

Saludos,

Belén

**Comment by lupomontero** [comment]
Gracias por la info @belencito27 :rocket: 

Justo hace un par de días tuvimos una charla de @mujerdehojalata en un meetup de @lima-js donde nos estuvo contando sobre el nuevo sitio web de "Código para el desarrollo" del BID :smile:

He etiquetado este issue como `help wanted`. Veamos si alguien del equipo de @Laboratoria/bootcamp-coaches se anima a echar una mano con esto :muscle:

**Comment by shirley-startary** [comment]
Hola, yo me animo a agregar más data, en algún momento platicábamos de 2 dataset divertidas  y populares, 
- [ ] Harry Potter.
- [ ] Star Wars.
Aunque igual y podemos sacar del link que compartió @diegovelezg.

**Comment by lupomontero** [comment]
Buenazo @shirley-startary :star: 

Porfa conversa con @betsyvies. Sé que ella está preparando algunos PRs sobre este proyecto y sería bueno que coordinen para no pisarse los zapatos.

**Comment by RuthSalvador** [comment]
Hola @Laboratoria/bootcamp-coaches estuve avanzando con la data de pokemon, les dejo la información del la propuesta de [json](https://drive.google.com/file/d/1EEJmx74Ym9XILXnEnxTYY7JSIxpr_CMq/view?usp=sharing) y el [research](https://docs.google.com/document/d/1ntWdvCTzeU8NCl0S6qs9Ti4FOH5UXVwroJiznG84foc/edit?usp=sharing) para el mismo. Espero puedan dar feedback de esto.

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue en favor de #848
