### ISSUE TITLE
ECMAScript versions

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#878]
Looking at the _projects_ we have in `master`, I can see that most _boilerplates_ include an `eslint` config file stating a specific ECMAScript parser version. In most cases (all but one), when stated, the required parser version is `6`, which means `ES6` aka `6th Edition - ECMAScript 2015`. This is the current state of these config files:

* `cipher`: [ES6 - 2015](https://github.com/Laboratoria/bootcamp/blob/master/projects/01-cipher/.eslintrc#L6)
* `data-lovers`: [ES6 - 2015](https://github.com/Laboratoria/bootcamp/blob/master/projects/02-data-lovers/.eslintrc#L6)
* `social-network`: [ES9 - 2018](https://github.com/Laboratoria/bootcamp/blob/master/projects/03-social-network/.eslintrc#L8)
* `social-network-frameworks`: n/a
* `md-links`: [ES6 - 2015](https://github.com/Laboratoria/bootcamp/blob/master/projects/04-md-links/.eslintrc#L6)
* `burger-queen`: interface: n/a. firebase functions [ES6 - 2015](https://github.com/Laboratoria/bootcamp/blob/master/projects/04-burger-queen/functions/.eslintrc.json#L4)
* `tic-tac-toe-rn`: n/a

**To the point. I would like to propose bringing all these config files (and accompanying `README.md` files) up to version `10` aka `10th Edition - ECMAScript 2019`**. Just over two years ago we had a [discussion in which we decided to fully embrace `ES6+`](https://github.com/Laboratoria/bootcamp/issues/108) in favour of older versions (read `ES5`). `ES6` represented a huge leap forward and meant many changes to our content, examples, ... This has now been _accomplished_, however we need to continue to look into the future (and present too). Since 2015, the TC39 has been publishing new _editions_ every year, in a more gradual manner, meaning more frequent releases and less changes per release. JavaScript is a fast evolving beast, and we have already become quite used to relatively recent features such as destructuring (2016), `async/await` (2016, 2017), rest/spread operator (2018), ... thanks to transpilers such as `babel` and native support in modern browsers (FireFox, Chrome, ...) and Node.js. In fact, I believe that it doesn't make sense to learn JavaScript today without the above mentioned features :thinking: 

***

For reference, these are the main changes in the _editions_ since `ES6`:

* **7th Edition - ECMAScript 2016**
  The 7th edition, officially known as ECMAScript 2016, was finalized in June 2016. The major standard language features include **block-scoping of variables and functions**, **destructuring** patterns (of variables), proper **tail calls**, **exponentiation operator** `**` for numbers, `async/await` keywords.
* **8th Edition - ECMAScript 2017**
  The 8th edition, officially known as ECMAScript 2017, was finalized in June 2017. Includes `async/await` constructions, which work **using generators and promises**. ECMAScript 2017 (ES2017), the eighth edition, includes features for **concurrency and atomics**, **syntactic integration with promises** (`async/await`).
* **9th Edition - ECMAScript 2018**
  The 9th edition, officially known as ECMAScript 2018, was finalized in June 2018. New features include `rest/spread` operators for variables (three dots: `...` identifier), **asynchronous iteration**, `Promise.prototype.finally()` and additions to `RegExp`.
* **10th Edition - ECMAScript 2019**
The 10th edition, officially known as ECMAScript 2019, was published in June 2019. Introduces `Object.fromEntries()`, `String.prototype.trimStart()`, `String.prototype.trimEnd()`, well-formed `JSON.stringify`, `Array.prototype.flat()`, `Array.prototype.flatMap()`, optional `try/catch` binding, revised `Function.prototype.toString()`, `Symbol.description` getter.

Source: https://en.wikipedia.org/wiki/ECMAScript#History

***

cc/ @Laboratoria/bootcamp-coaches

**Comment by lupomontero** [comment]
cc/ @raulingg

**Comment by developerVilchez** [comment]
I'm totatly agree with this. I would like to help with this upgrade not only in projects of master but also with all our resources. I would like to have this for the next cohort!!

**Comment by merunga** [comment]
@lupomontero I think that the ES version should be tied to the environment each project runs on.

For example projects that are supposed to be implemented in vanillajs, should have the most commonly supported ES version by browsers.

For md-links maybe we have to decide first which is the suggested nodejs version, and the the ES version that comes with it.

And finally for the projects with frameworks, we may have a little more freedom because we can tweak the babel configuration, but i think we depend on the versions supported/recommended by each framework.

I think all this makes it a little difficult to standardize the ES version.

**Comment by lupomontero** [comment]
Thanks for the comments :yellow_heart: 

@merunga, I think you're right wrt having to pick not only an ES version but also a Node version. Looking at [ES features supported by Node](https://node.green/#ES2018), I think we should probably _require_ Node `>= v10.9.0`, which would mean that we can assume `ES2018`, which in my view is good as a standard both for Node and the browser (taking into consideration that our DOM tests are run with jest using `jsdom` in Node).

How about bringing `cipher`, `data-lovers` and `md-links` up to `ES2018 - 9th Edition`, the same as `social-network`.

Thoughts?

**Comment by florenciasilva** [comment]
> How about bringing `cipher`, `data-lovers` and `md-links` up to `ES2018 - 9th Edition`, the same as `social-network`.
> 
I would love to help with this if it's possible 😄
