### ISSUE TITLE
Actualizar secciones de evaluación en TODOS los proyectos

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#881]
Esta sección debe actualizarse con el modelo de evaluación actual:

1. Rúbrica solo referencia
2. Feedback de proyecto
3. No hay nota
3. Objetivos de aprendizaje

**Comment by diegovelezg** [comment]
- También Wiki y Readme general de repo.
- También todo otro contenido de comunicación con las estudiantes (TBD).
- Que el MO de objetivos de aprendizaje sea explícito (Sí/no)

**Comment by lupomontero** [comment]
:warning: Necesitamos _urgentemente_ actualizar las secciones de _Evaluación_ en los proyectos. 

Desde el lado del diseño curricular y la ejecución del Bootcamp sentimos que tiene sentido reflejar de forma más fiel lo que ocurre y lo que queremos que ocurra...

Ya a día de hoy se da el caso que los últimos proyectos que se han agregado a la currícula ni siquiera incluyeron una sección de Evaluación (battleship, burger-queen-api y burger-queen-api-client), ya que hay mucha incertidumbre al respecto.

Propongo lo siguiente...

1. Adoptar mecánica de _project feedback_ inspirada en el track de JS en Lima.
2. Agregar texto con info sobre evaluación
3. Modificar los párrafos que mencionan la rúbrica
4. Mantener temporalmente las habilidades de la rúbrica actualmente listadas en los proyectos que tengan, pero dejar muy claro que son solo de referencia para autoevaluación.
5. En un futuro próximo, reemplazar habilidades de rúbrica con objetivos de aprendizaje parseables

El primer paso ...

Los pasos 2, 3 y 4 se podrían dar YA, siempre y cuando nadie tenga nada en contra. El último paso es más incierto y va demorar todavía unas semanas (o meses) :speak_no_evil: 

***

## 1. Adoptar mecánica de _project feedback_ inspirada en el track de JS en Lima

Esto implica:

* Que las estudiantes se autoevaluen ANTES de la sesión de feedback de proyecto en base a los _objetivos de aprendizaje_ listados en el README (en formato de checklist).
* Las estudiantes traen su autoevaluación a la sesión de feedback y la validan con un coach.
* Coach recomienda si pasar al siguiente proyecto, o continuar con proyecto, o quizás hacer otro proyecto chiquito, o ejercicios u otra alternativa para ayudar a alcanzar los objetivos de aprendizaje.
* Coaches dan más importancia a los objetivos de aprendizaje que a la completitud de un proyecto (features, historias de usuario, ...).

Ver texto del siguiente punto para más detalles.

## 2. Agregar texto con info sobre evaluación

Este texto iría (con modificaciones donde toque según el proyecto) al principio de la sección de _Evaluación_:

```
Durante el desarrollo del proyecto tus coaches harán seguimiento del avance de
tu equipo.

El tiempo estimado para completar el proyecto puede variar dependiendo de cómo
vayas avanzando. Asegúrate de conversar con tus coaches para que te ayuden a
planificar el proyecto y definir el alcance de lo que quieras implementar. Recuerda
que los objetivos de aprendizaje son más importantes que la completitud de tu
proyecto.

Al final del proyecto, tendrás una _sesión de feedback_ con tus coaches para
evaluar si se han cumplido los objetivos de aprendizaje esperados. Antes de esta
sesión de feedback tendrás que reflexionar y autoevaluarte con respecto a los
objetivos de aprendizaje. En la sesión de feedback validarás esa autoevaluación
con tus coaches. En caso de no haberse completado algunos objetivos podrá
ocurrir una de las siguientes:

* Si se trata de objetivos de aprendizaje que vuelven a aparecer más adelante en
  otros proyectos, simplemente quedarán anotados como _pendiente_ en los
  siguientes proyectos y podrás continuar con el siguiente proyecto.
* En caso contrario tus coaches te recomendarán cómo continuar para coneguir los
  objetivos de aprendizaje, pudiendo ser a través de continuar con el proyecto,
  hacer ejercicios enfocados en los temas necesarios, etc, ...

Recuerda que cada una aprende a su ritmo y lo importante es ir obteniendo las
habilidades asociadas a los objetivos de aprendizaje de forma gradual. Tus
coaches y compañeras están ahí para apoyarte.
```

## 3. Modificar los párrafos que mencionan la rúbrica

Actualmente dice:

```
NOTA: Esta sección incluye una lista de habilidades que se podrán tener en
cuenta a la hora de evaluar el proyecto. Los niveles esperados son _sugerencias_
así como _guías_ en el diseño curricular, pero no reglas absolutas.

Te aconsejamos revisar [nuestra rúbrica](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vRktPN4ilZtkRN5tUb3DVhgeihwlzk63_-JI3moA-bXpKDbHDioAK2H3qbrwWNb0Ql4wX22Tgv7-PDv/pubhtml)
para ver la descripción detallada de cada _habilidad_ y cada _nivel_. Te
recomendamos también que trates de aplicarte la rúbrica a tí misma y/o a los
proyectos de tus compañeras a lo largo del Bootcamp para ir viendo tu evolución.
```

Propongo cambiarlo a:

```
NOTA: A continuación se incluye una lista de habilidades más abstractas que
recomendamos que tengan en cuenta a la hora de auto-evaluarse. Los niveles
esperados son _sugerencias_ así como _guías_ en el diseño curricular, pero no
reglas absolutas.

Te aconsejamos revisar [nuestra rúbrica](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vRktPN4ilZtkRN5tUb3DVhgeihwlzk63_-JI3moA-bXpKDbHDioAK2H3qbrwWNb0Ql4wX22Tgv7-PDv/pubhtml)
para ver la descripción detallada de cada _habilidad_ y cada _nivel_. Te
recomendamos también que trates de aplicarte la rúbrica a tí misma y/o a los
proyectos de tus compañeras a lo largo del Bootcamp para ir viendo tu evolución.
```

## 4. Mantener temporalmente las habilidades de la rúbrica

Aquellas actualmente listadas en los proyectos que tengan, pero dejar muy claro que son solo de referencia para autoevaluación. De esta forma no impactaríamos de forma tan radical al equipo del LMS que actualmente está usando esta data en la interfaz de _project feedback_.

## 5. En un futuro próximo, reemplazar habilidades de rúbrica con objetivos de aprendizaje parseables

En un **futuro** próximo, en cuanto podamos _parsear_ los objetivos de aprendizaje de la sección que corresponde, finalmente podremos reemplazar completamente las listas de habilidades de la rúbrica con los objetivos de aprendizaje que hagan referencia al trabajo que actualmente está haciendo el squad de objetivos de aprendizaje.

***

Thoughts? Se agradecen sugerencias y comentarios.

cc/ @Laboratoria/bootcamp-coaches @chamodev @diegovelezg @CaroLaboratoria @lalogf

**Comment by nerdale** [comment]
Me parece súper @lupomontero sólo cambiaría algunas cosas de concepto

> ## 2. Agregar texto con info sobre evaluación
> Este texto iría (con modificaciones donde toque según el proyecto) al principio de la sección de _Evaluación_:
> 
> ```
> Durante el desarrollo del proyecto tus coaches harán seguimiento del avance de
> tu equipo.
> 
> El tiempo estimado para completar el proyecto puede variar dependiendo de cómo
> vayas avanzando. Asegúrate de conversar con tus coaches para que te ayuden a
> planificar el proyecto y definir el alcance de lo que quieras implementar. Recuerda
> que los objetivos de aprendizaje son más importantes que la completitud de tu
> proyecto.
> 
> Al final del proyecto, tendrás una _sesión de feedback_ con tus coaches para
> evaluar si se han cumplido los objetivos de aprendizaje esperados. Antes de esta
> sesión de feedback tendrás que reflexionar y autoevaluarte con respecto a los
> objetivos de aprendizaje. En la sesión de feedback validarás esa autoevaluación
> con tus coaches. En caso de no haberse completado algunos objetivos podrá
> ocurrir una de las siguientes:
> 
> * Si se trata de objetivos de aprendizaje que vuelven a aparecer más adelante en
>   otros proyectos, simplemente quedarán anotados como _pendiente_ en los
>   siguientes proyectos y podrás continuar con el siguiente proyecto.
> * En caso contrario tus coaches te recomendarán cómo continuar para coneguir los
>   objetivos de aprendizaje, pudiendo ser a través de continuar con el proyecto,
>   hacer ejercicios enfocados en los temas necesarios, etc, ...
> 
> Recuerda que cada una aprende a su ritmo y lo importante es ir obteniendo las
> habilidades asociadas a los objetivos de aprendizaje de forma gradual. Tus
> coaches y compañeras están ahí para apoyarte.
> ```
> 
Al final del proyecto, tendrás una _sesión de feedback_ con tus coaches para ~evaluar~ analizar si se han cumplido los objetivos de aprendizaje esperados.  Antes de esta sesión de feedback tendrás que reflexionar ~y autoevaluarte con~ respecto a los objetivos de aprendizaje alcanzados. En la sesión de feedback validarás esa reflexión ~esa autoevaluación~ con tus coaches. En caso de no haberse completado algunos objetivos podrá ocurrir una de las siguientes posibilidades:

> ## 3. Modificar los párrafos que mencionan la rúbrica
> Actualmente dice:
> 
> ```
> NOTA: Esta sección incluye una lista de habilidades que se podrán tener en
> cuenta a la hora de evaluar el proyecto. Los niveles esperados son _sugerencias_
> así como _guías_ en el diseño curricular, pero no reglas absolutas.
> 
> Te aconsejamos revisar [nuestra rúbrica](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vRktPN4ilZtkRN5tUb3DVhgeihwlzk63_-JI3moA-bXpKDbHDioAK2H3qbrwWNb0Ql4wX22Tgv7-PDv/pubhtml)
> para ver la descripción detallada de cada _habilidad_ y cada _nivel_. Te
> recomendamos también que trates de aplicarte la rúbrica a tí misma y/o a los
> proyectos de tus compañeras a lo largo del Bootcamp para ir viendo tu evolución.
> ```
> 
> Propongo cambiarlo a:
> 
> ```
> NOTA: A continuación se incluye una lista de habilidades más abstractas que
> recomendamos que tengan en cuenta a la hora de auto-evaluarse. Los niveles
> esperados son _sugerencias_ así como _guías_ en el diseño curricular, pero no
> reglas absolutas.
> 
> Te aconsejamos revisar [nuestra rúbrica](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vRktPN4ilZtkRN5tUb3DVhgeihwlzk63_-JI3moA-bXpKDbHDioAK2H3qbrwWNb0Ql4wX22Tgv7-PDv/pubhtml)
> para ver la descripción detallada de cada _habilidad_ y cada _nivel_. Te
> recomendamos también que trates de aplicarte la rúbrica a tí misma y/o a los
> proyectos de tus compañeras a lo largo del Bootcamp para ir viendo tu evolución.
> ```

NOTA: A continuación se incluye una lista de habilidades más abstractas que recomendamos tengan en cuenta a la hora de ~auto-evaluarse~ analizar y reflexionar sobre tu evolución. 

No sé si pasa en otras sedes, pero acá los niveles los estamos dejando, sería bueno saber si alguien los usa para mantener esto en los readme o definitivamente sacarlos.

## 
No se me ocurre como más cambiarlo, pero hablar de no evaluamos y después que en el readme hable de evaluación me hace cortocircuito :cry:

**Comment by juanjordan** [comment]
Hola! estoy de acuerdo con lo que plantea @nerdale en el caso que justamente se esté mencionando. @lupomontero creo que más fácil es verlo ya en un PR con el `diff` que se le va a agregar, incluso comparando ramas con un ejemplo a un proyecto.

**Comment by mfdebian** [comment]
Me sumo a las palabras de @nerdale, hay una contradicción con respecto a lo que les decimos a la estudiantes y lo que luego ocurre con respecto al tema de la **evaluación**. Me parece genial en todo caso el ir cambiando el contenido de los README's para que vayan reflejando de mejor manera lo que queremos visibilizar.

La única parte con la que tengo duda es cómo vamos a discernir de manera concreta y basada en información (más que por instinto) cuándo una estudiante deberá seguir o entregar un proyecto si es que ya vamos de alguna manera dejar de lado o difuminar un poco ese deadline de entrega de proyectos.

Un ejemplo:
Un Squad de estudiantes está en su 3er sprint de  `Social-Network`, y les ha ido bien con las partes que tienen que ver con modularidad, funciones, SPA, responsiveness, etc... Pero no han logrado entender bien cómo escoger, ponerse de acuerdo o cómo manejar la estructura de datos de la app.

Podríamos decirle que trabajaran otro sprint más para esto (¿Y por lo tanto presentan su proyecto después que los demás squads? Bueno probablemente en esta práctica ya no esté tan definido _el día de las presentaciones_) o podríamos también decirles que entreguen (presenten) lo que tienen y que pasen a `md-links` ya que en ese proyecto también se trabajan (y quizás de manera más explícita) las estructuras de datos.

En ese caso, a mi parecer podrían presentar lo que lleven hasta ese momento, y pasar a `md-links`, pero me causa un poco de duda el hecho de que esa decisión la estaría tomando con mucha intuición; Quizás justo ese ejemplo es muy concreto, pero enverdad me preocuparía más cuando sean casos más ambiguos, donde no sabríamos bien cómo escoger, cuáles serían los factores que pesan más ahí. No sé, sólo lo pongo para expresar mi opinión, creo que también deberíamos tener muy definido cuándo se han cumplido los objetivos (¿mínimos requeridos?) para pasar al siguiente proyecto o no. ¿Qué opinan? De cualquier forma pienso que al hacer eso damos un mejor seguimiento de cómo lo hacemos hasta el día de hoy, así que me sumo.

**Comment by FabianBravoA** [comment]
Totalmente de acuerdo con lo que dice @nerdale , deberíamos dejar de usar "evaluación" en todas partes.

Por otro lado, deberíamos hacer una buena revisión al lenguaje de la rúbrica, dado que queremos que sea clave la introspección de ellas respecto de sus habilidades. Por ejemplo son muy pocas las que entienden "asintótico" o el verdadero significado de que un algoritmo sea eficiente. Tampoco conocen muchas estructuras de datos, o tienen una buena idea de qué es una de ellas a pesar de haber ocupado algunas. Y así varios ejemplos que deberíamos explicar de una mejor manera a las estudiantes o ver bien si lo que estamos exigiendo tiene sentido en términos del bootcamp.

**Comment by diegovelezg** [comment]
Va mi feedback:

1. No veo problema en usar **"evaluación"**. Lo que no queremos es usar nota/calificación. La autoevluación y la del equipo de formación me parece que es real y necesaria. No queremos, sin embargo, que eso se refleje en un único "indicador" (nota/calificación).

2. No creo que sea necesario repetir en toooooooooooooooooooooooooodos los readmes lo mismo sobre la "evaluación" 😜. Sï creo que debe estar súper bien descrito y detallado en el repositorio general del BC (TBD)



> ⚠️ Necesitamos _urgentemente_ actualizar las secciones de _Evaluación_ en los proyectos.
> 
> Desde el lado del diseño curricular y la ejecución del Bootcamp sentimos que tiene sentido reflejar de forma más fiel lo que ocurre y lo que queremos que ocurra...
> 
> Ya a día de hoy se da el caso que los últimos proyectos que se han agregado a la currícula ni siquiera incluyeron una sección de Evaluación (battleship, burger-queen-api y burger-queen-api-client), ya que hay mucha incertidumbre al respecto.
> 
> Propongo lo siguiente...
> 
> 1. Adoptar mecánica de _project feedback_ inspirada en el track de JS en Lima.

Yala desde la reun de CDMX (acordadísimo y siendo implementado)
> 2. Agregar texto con info sobre evaluación

Lo dicho: creo que no es necesario para cada proyecto pero sí como algo general del BC. Podríamos _linkear_ si es necesario (me parece más eficiente porque DRY). 
> 3. Modificar los párrafos que mencionan la rúbrica

Creo que esa referencia general a la rúbrica debería ser parte de la misma sección de "evaluación" de 3 y no algo específico de cada proyecto.
> 4. Mantener temporalmente las habilidades de la rúbrica actualmente listadas en los proyectos que tengan, pero dejar muy claro que son solo de referencia para autoevaluación.}

En desacuerdo. Creo que me gustaría romper la relación rúbrica-proyecto.
> 5. En un futuro próximo, reemplazar habilidades de rúbrica con objetivos de aprendizaje parseables
> 
> El primer paso ...
> 
> Los pasos 2, 3 y 4 se podrían dar YA, siempre y cuando nadie tenga nada en contra. El último paso es más incierto y va demorar todavía unas semanas (o meses) 🙊
> 
> ## 1. Adoptar mecánica de _project feedback_ inspirada en el track de JS en Lima
> Esto implica:
> 
> * Que las estudiantes se autoevaluen ANTES de la sesión de feedback de proyecto en base a los _objetivos de aprendizaje_ listados en el README (en formato de checklist).
> * Las estudiantes traen su autoevaluación a la sesión de feedback y la validan con un coach.
> * Coach recomienda si pasar al siguiente proyecto, o continuar con proyecto, o quizás hacer otro proyecto chiquito, o ejercicios u otra alternativa para ayudar a alcanzar los objetivos de aprendizaje.

Idealmente debería ser 100% decisión de la estudiante después de autoevaluaciónn y conociendo los proyectos disponibles (validada/consensuada por/con coach). Si aceptáramos la propuesta de información- conocimiento-micro habilidad/habilidad-competencia, no deberías poder validar una micro habilidad o habilidad (actuales objetivos de aprendizaje) fuera del contexto de un proyecto.
> * Coaches dan más importancia a los objetivos de aprendizaje que a la completitud de un proyecto (features, historias de usuario, ...).

Creo que debería ir a la parte general de evaluación del repo.
> 
> Ver texto del siguiente punto para más detalles.
> 
> ## 2. Agregar texto con info sobre evaluación
> Este texto iría (con modificaciones donde toque según el proyecto) al principio de la sección de _Evaluación_:
> 
> ```
> Durante el desarrollo del proyecto tus coaches harán seguimiento del avance de
> tu equipo .
> 
> El tiempo estimado para completar el proyecto puede variar dependiendo de cómo
> vayas avanzando. Asegúrate de conversar con tus coaches para que te ayuden a
> planificar el proyecto y definir el alcance de lo que quieras implementar. Recuerda
> que los objetivos de aprendizaje son más importantes que la completitud de tu
> proyecto.
> 
> Al final del proyecto, tendrás una _sesión de feedback_ con tus coaches para
> evaluar si se han cumplido los objetivos de aprendizaje esperados. Antes de esta
> sesión de feedback tendrás que reflexionar y autoevaluarte con respecto a los
> objetivos de aprendizaje. En la sesión de feedback validarás esa autoevaluación
> con tus coaches. En caso de no haberse completado algunos objetivos podrá
> ocurrir una de las siguientes:
> 
> * Si se trata de objetivos de aprendizaje que vuelven a aparecer más adelante en
>   otros proyectos, simplemente quedarán anotados como _pendiente_ en los
>   siguientes proyectos y podrás continuar con el siguiente proyecto.
> * En caso contrario tus coaches te recomendarán cómo continuar para coneguir los
>   objetivos de aprendizaje, pudiendo ser a través de continuar con el proyecto,
>   hacer ejercicios enfocados en los temas necesarios, etc, ...
> 
> Recuerda que cada una aprende a su ritmo y lo importante es ir obteniendo las
> habilidades asociadas a los objetivos de aprendizaje de forma gradual. Tus
> coaches y compañeras están ahí para apoyarte.
> ```
> 
> ## 3. Modificar los párrafos que mencionan la rúbrica
> Actualmente dice:
> 
> ```
> NOTA: Esta sección incluye una lista de habilidades que se podrán tener en
> cuenta a la hora de evaluar el proyecto. Los niveles esperados son _sugerencias_
> así como _guías_ en el diseño curricular, pero no reglas absolutas.
> 
> Te aconsejamos revisar [nuestra rúbrica](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vRktPN4ilZtkRN5tUb3DVhgeihwlzk63_-JI3moA-bXpKDbHDioAK2H3qbrwWNb0Ql4wX22Tgv7-PDv/pubhtml)
> para ver la descripción detallada de cada _habilidad_ y cada _nivel_. Te
> recomendamos también que trates de aplicarte la rúbrica a tí misma y/o a los
> proyectos de tus compañeras a lo largo del Bootcamp para ir viendo tu evolución.
> ```
> 
> Propongo cambiarlo a:
> 
> ```
> NOTA: A continuación se incluye una lista de habilidades más abstractas que
> recomendamos que tengan en cuenta a la hora de auto-evaluarse. Los niveles
> esperados son _sugerencias_ así como _guías_ en el diseño curricular, pero no
> reglas absolutas.
> 
> Te aconsejamos revisar [nuestra rúbrica](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vRktPN4ilZtkRN5tUb3DVhgeihwlzk63_-JI3moA-bXpKDbHDioAK2H3qbrwWNb0Ql4wX22Tgv7-PDv/pubhtml)
> para ver la descripción detallada de cada _habilidad_ y cada _nivel_. Te
> recomendamos también que trates de aplicarte la rúbrica a tí misma y/o a los
> proyectos de tus compañeras a lo largo del Bootcamp para ir viendo tu evolución.
> ```
> 

Después propongo cambios/sugerencias.
> ## 4. Mantener temporalmente las habilidades de la rúbrica
> Aquellas actualmente listadas en los proyectos que tengan, pero dejar muy claro que son solo de referencia para autoevaluación. De esta forma no impactaríamos de forma tan radical al equipo del LMS que actualmente está usando esta data en la interfaz de _project feedback_.
> 

Desacuerdo. Creo que solamente va a causar innecesaria confusión a nuestras estudiantes.
> ## 5. En un futuro próximo, reemplazar habilidades de rúbrica con objetivos de aprendizaje parseables
> En un **futuro** próximo, en cuanto podamos _parsear_ los objetivos de aprendizaje de la sección que corresponde, finalmente podremos reemplazar completamente las listas de habilidades de la rúbrica con los objetivos de aprendizaje que hagan referencia al trabajo que actualmente está haciendo el squad de objetivos de aprendizaje.
> 
> Thoughts? Se agradecen sugerencias y comentarios.
> 
> cc/ @Laboratoria/bootcamp-coaches @chamodev @diegovelezg @CaroLaboratoria @lalogf

**Comment by lupomontero** [comment]
Gracias a todxs por los comentarios :black_heart: :star: 

***

@nerdale:

Entiendo la confusión con el uso del término _evaluación_, pero creo que estoy de acuerdo con @diegovelezg en que nos guste o no al final es una _evaluación_, ... lo que es importante es que también existe una autoevaluación, y que no existe el concepto de nota o examen en un sentido tradicional. Si reemplazamos _evaluación_ por _análisis_ me parece que no es del todo sincero... y reemplazando _autoevaluación_ por _reflexión_ me parece también menos claro... en este caso creo que esperamos que lxs coaches evaluen los objetivos de aprendizaje, partiendo de la autoevaluación de la estudiante, de feedback y ahí recomiende cómo continuar.

Sigo abierto a la posibilidad de cambiar el término por otra cosa con menos connotación de modelo tradicional, pero todavía no estoy convencido de qué terminología sea más _correcta_... :thinking: 

***

@juanjordan:

>  creo que más fácil es verlo ya en un PR con el diff

PR en camino... :hammer: 

***

@mfdebian:

> [...] cómo vamos a discernir de manera concreta y basada en información (más que por instinto) cuándo una estudiante deberá seguir o entregar un proyecto [...]

Creo que tu reflexión es algo que se preguntan muchxs coaches y creo que hay un nivel de incertidumbre que nunca podremos despejar, :cold_sweat: ... y siempre será una de las decisiones difíciles que toca tomar como coach. Al mismo tiempo, el _squad_ de _objetivos de aprendizaje_ está trabajando para reemplazar la rúbrica deprecada con una serie de micro-habilidades más granulares que esperamos podamos reducir a algo como _conoce, X, entiende X y puede aplicar X en contexto_? Básicamente algo que podamos responder con un booleano. Personalmente tengo mucha fe en lo que se está trabajando. Recientemente varios proyectos han sido actualizados con sugerencias en esta línea.

Como dice @diegovelezg, en un mundo ideal sería la propia estudiante la que toma la decisión, y lxs coaches están ahí para asesorar en esas decisiones y ayudarles entender si realmente conocen, entienden y puden usar X, Y o Z.

***

@FabianBravoA:

> [...] son muy pocas las que entienden "asintótico" o el verdadero significado de que un algoritmo sea eficiente [...]

Me da la impresión que te refieres a la rúbrica que hemos acordado queda deprecada por ahora. Desde hace unas semanas @juanjordan está liderando una iniciativa que llamamos el _squad_ de objetivos de aprendizaje y venimos trabajando en un reemplazo de la rúbrica actual, que justo estamos en proceso de deprecar.

***

@diegovelezg:

> No creo que sea necesario repetir en toooooooooooooooooooooooooodos los readmes lo mismo sobre la "evaluación" stuck_out_tongue_winking_eye. Sï creo que debe estar súper bien descrito y detallado en el repositorio general del BC (TBD)

:+1: 

> Desacuerdo. Creo que solamente va a causar innecesaria confusión a nuestras estudiantes.
> (Respuesta a punto 4 - Mantener temporalmente las habilidades de la rúbrica)

**Esto creo que ya no es un issue porque tengo confirmación de @chamodev de que el LMS puede funcionar sin necesidad de que los proyectos hagan referencia a la rúbrica deprecada**. Con lo cual podemos Evitar los puntos `3` y `4` :smile:
