### ISSUE TITLE
Electivo en el common-core orientado a entrenar el skill pixel perfect

### ISSUE THREAD

**Issue by developerVilchez** [Laboratoria/bootcamp#886]
Por aquí solicito su feedback sobre lo que sería tener un proyecto en el common core orientado exclusivamente a poner en práctica el skill de pixel perfect y responsive-web-design. 
Os leo atentamente!!
@Laboratoria/bootcamp-coaches 
@diegovelezg 
@CaroLaboratoria

**Comment by lupomontero** [comment]
Me parece una idea interesante... aunque no me queda muy claro cómo podríamos manejar _electivos_ dentro del common core (estoy abierto a escuchar ideas). En principio yo me había imaginado un _electivo_ hacia el final (como los demás electivos), y dado el tema, creo que podría tener sentido ofrecerlo tanto a las estudiantes del track de Front-end como UX.

Thoughts?

**Comment by diegovelezg** [comment]
Tampoco lo entiendo muy bien en el contexto del CC

¿"electivo" o "alternativo" o "adicional"? 🤔

**Comment by gaposx** [comment]
Como contexto, entiendo que esta solicitud de feedback viene de la ejecución de [data-lovers con LIM010](https://github.com/Laboratoria/LIM010-data-lovers). En ese proyecto se dió el diseño de una pantalla para que sea replicada de manera exacta (pixel perfect). Ya que este skill no es parte de los OA de DL, creo que si podríamos intentar generar un mini proyecto electivo donde se lo considere. 
Tal como menciona Lupo, este electivo podría ser usado para UXD o FED. Incluso en casos excepcionales de CC.

**Comment by juanjordan** [comment]
Hola 👋🏻, gracias @developerVilchez por empezar este hilo, creo que todavía no tenemos un proyecto en el Bootcamp que desarrolle solamente habilidades de estructura y presentación de un Sitio Web, pero me gustaría mencionar un par de puntos sobre el término `pixel perfect`.

![MV5BMTY0ODgzMzg3OV5BMl5BanBnXkFtZTgwNzQ3NDM0NzE@ _V1_UY268_CR9,0,182,268_AL_](https://user-images.githubusercontent.com/45951334/66152314-da54c600-e5de-11e9-8e9a-1a86e1d7abaa.jpg)

En Desarrollo Web y más específico en Diseño Web me parece que es un error hablar de un diseño Pixel Perfect, recuerdo que cuando la idea de _Responsive Web Design_(RWD) recién aparecía era incompatible con Pixel Perfect, dado el número infinito de pantallas y resoluciones donde se tiene que mostrar el sitio web.

Con el tiempo he visto aparecer y desaparecer este término, va y viene, me parece por la connotación _marketera_ que tiene: si una empresa solo busca la "excelencia" pues que sus diseños tengan _perfect_ en el nombre es lo mínimo que se puede pedir.

Creo que en Laboratoria tenemos que hacer notar estos términos y cómo afecta a la cultura de los lugares donde trabajamos y donde nuestras estudiantes van a trabajar.

Me animaría incluso a decir que algo Perfecto es incompatible con la cultura de Laboratoria, dado que siempre estamos en constante mejora y nos hacemos llamar un Work In Progress. Algo Perfecto es que está terminado.

Me gustaría compartir artículos sobre este tema que pude ver en su momento pero ya no los encuentro, comparto algunos más contemporáneos que revisé para confirmar el estado actual de la industria al respecto:
- https://blog.prototypr.io/perfect-design-a-myth-5dddf75b5c24
- https://shkspr.mobi/blog/2018/11/the-myth-of-the-pixel-perfect-grid/
- https://www.linkedin.com/pulse/rethinking-pixel-perfect-myth-brian-sullivan

Dicho esto, sí estaría de acuerdo en tener un proyecto que se enfoque en la parte de diagramación,  desarrollo web semántico y responsive web design, inclusive uno aparte para _Accessibility_. Lo cual nos hará descubrir (y a las estudiantes) que el diseño superior es aquel que se puede adaptar al contexto.

Con respecto al _timing_, creo que puede ser en cualquier momento del Bootcamp.

**Comment by lupomontero** [comment]
Estoy de acuerdo con el comentario de @juanjordan con respecto al uso del término _pixel perfect_ (legado de un pasado unresponsive), y quizás concentrarnos en la _habilidad_ de _adaptar_ un diseño pre-existente (ie: un bitmap o vectores) al navegador, manteniendo un alto grado de fidelidad, pero siempre teniendo en cuenta que existen muchos tamaños y formatos de pantalla (responsive).

Esto es un tema de diagramación, maquetado, arquitectura de información, accesibilidad y fidelidad de la interfaz con respecto a una _identidad visual_ bien definida.

Después de pensarlo un rato, en mi experiencia, me atrevería a decir que es mucho más importante que un diseño se adapte al contexto de forma _usable_ y _predecible_ antes de tratar de replicar un diseño fijo para un tamaño de pantalla concreto en un dispositivo en particular.

***

> En ese proyecto se dió el diseño de una pantalla para que sea replicada de manera exacta (pixel perfect).

@gaposx, nos podrías compartir ese _diseño de pantalla_ que les dieron a las estudiantes para tener más contexto?

Thoughts?

**Comment by gaposx** [comment]
Creo que el uso del término pixel perfect depende mucho del contexto o del concepto al cual lo relacionemos. La intención del skill a desarrollar se conecta con el concepto que menciona Lupo; sobre de fidelidad de la interfaz con respecto a los entregables de diseño, y tal vez debemos encontrar una mejor forma de llamarlo. Este tema es algo que las estudiantes de FED y UXD van a enfrentar en sus trabajos con los diferentes equipos de diseño o desarrollo.

@lupomontero : el link que compartimos en el README del proyecto: https://www.figma.com/file/awZfJWfpAioeanwhlcrsjSjc/Data-lovers?node-id=1%3A2

**Comment by merunga** [comment]
en lima el [readme de social-network](https://github.com/laboratoria/lim010-social-network#tecnolog%C3%ADas-html5-y-css3sass) viene con unos bitmaps que ellas deben maquetar a nivel de estructura mobile y desktop, con la libertad de cambiar fuentes y colores.

Parte de la sesion de feedback al terminar el proyecto se basa en que la maquetacion respete esas imagenes

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue para continuar la conversación en #1025.
