### ISSUE TITLE
Incluir SCM (git y github) como objetivo de aprendizaje para la trivia

### ISSUE THREAD

**Issue by betsyvies** [Laboratoria/bootcamp#897]
Hola @Laboratoria/bootcamp-coaches! Pido su apoyo para ver si es una opción agregar SCM (git y github) como objetivo de aprendizaje para la trivia. Como se comentó anteriormente en los chapters, hay un equipo liderando el árbol de objetivos y en cuanto a los OA de la Trivia más específicamente lo estamos liderando @lupomontero y yo. Así que nos sería de mucha ayuda sus opiniones y comentarios. 

Dejo adjunta una de las entrevistas que hice a las estudiantes con respecto al tema:
- ¿Cuéntame que te gusto más de la etapa de selección?
Lo que más me gusto fue el pre trabajo y la información, porque creé algo.
- ¿Cuéntame cómo te sentiste con los nuevas tecnologías que tenías que aprender en pre-admisión?
Abrumada porque tenía que aprender mucho en tan poco tiempo y lo que aprendí en el pre-work ya me había olvidado, me fue complicado aprender, pero sé que en el mundo tech es necesario y también lo será cuando estas se actualicen. Es fastidioso pero útil.
- ¿Qué opinarias si agregamos git y github como OA en la trivia?
Sería más complicado, el proyecto fue wau y agregarle algo más sería mucho más. 
- ¿Qué opinarias si antes de preadmisión las acompañamos virtualmente con estos OA?
De ser así, estaría bueno. La espera a que nos llamen sería menos angustiante y sabríamos los temas que veríamos durante la semana ya no sería sorpresa. También sería útil encontrar en el LMS temas como ágil y organización.

**Comment by gaposx** [comment]
Me pregunto cuál es la hipótesis que nos lleva a incluir SCM en pre-admisión. 
A primera vista, me preocupa el tiempo que tienen para ejecutarlo versus los OA actuales. Como la estudiante comenta en la entrevista, agregarle otro SCM como OA (lo cual implica entender e instalar cosas para que lo logren) podría hacer que se sientan más abrumadas durante la semana.

**Comment by shirley-startary** [comment]
La misma preocupación que @gaposx, ¿Cuál es el objetivo que aprendan SCM?, tomando en cuenta que son muy pocos días de la semana de preadmisión que realmente empiezan a codear o a trabajar en el proyecto.

**Comment by lupomontero** [comment]
Gracias @betsyvies por abrir el issue y @gaposx y @shirley-startary por sus comentarios :yellow_heart: 

Creo que la intención es hacer que el proceso de admisión (proyecto de pre-admisión en este caso) sea lo más parecido al Bootcamp como _experiencia_ para la estudiante. Pero dada las limitaciones de tiempo, por el momento creo que optaría por dejar SCM fuera de la trivia a menos que podamos ampliar el tiempo de pre-admisión.

Qué piensan?

cc/ @rocioalberdi @diegovelezg @CaroLaboratoria @Laboratoria/bootcamp-coaches

**Comment by mfdebian** [comment]
+1 A los comentarios de @gaposx y @shirley-startary. En función del tiempo, creo que sería difícil agregar ahora SCM; En la forma en la que está ahora ya las postulantes sienten que es demasiada información para consumir en unos pocos días; Por mi experiencia en PAs diría que es mejor no agregar otro OA de este "calibre" si es que no les vamos a dar más tiempo para poder lograr asimilarlo.

**Comment by betsyvies** [comment]
Gracias a todos por comentar. :yellow_heart: 

Como comento @lupo, la intención es hacer que el proyecto de pre-admisión sea lo más parecido al Bootcamp, esto sin limitar o complicar el autoaprendizaje de las postulantes. Creo que todos coincidimos en que agregar SCM como OA al proyecto en tampoco tiempo complicaría el autoaprendizaje de un gran porcentaje de las postulantes, pero nos estamos olvidando del pequeño grupo que termina el proyecto antes del deadline y al cual probablemente podríamos estar limitando su autoaprendizaje. Dicho esto, paso a proponer el SCM como parte del hacker edition (parte opcional), ya que, el autoaprendizaje es una de nuestras habilidades base y es lo que buscamos en nuestras postulantes. 

Ojo: Que una postulante utilice SCM para su proyecto no quiere decir que ingresará al bootcamp, eso depende de la suma de diferentes habilidades.

cc/ @rocioalberdi @diegovelezg @CaroLaboratoria @Laboratoria/bootcamp-coaches

**Comment by lupomontero** [comment]
@betsyvies: a mi me parece bien. Creo que el siguiente paso sería enviar tu PR a este repo :wink:
