### ISSUE TITLE
Borrar proyecto bq-node ahora que ya tenemos burger-queen-api?

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#900]
tl;dr

Qué le parece si quitamos `bq-node` del [catálogo de proyectos](https://github.com/Laboratoria/bootcamp/tree/master/projects)?

***

Ahora que tenemos la nueva versión del proyecto `burger-queen-api` (junto con `burger-queen-client`), me queda la duda de si debamos mantener tanto `bq-node` como `burger-queen-api` en el catálogo de proyectos... :thinking: Ambos proyectos son muy parecidos, ... de hecho `burger-queen-api` es una evolución de `bq-node`...

Creen que tenga valor mantener ambos proyectos?

Al mismo tiempo, me hago la misma pregunta con respecto a `burger-queen` (con firebase) y `burger-queen-client`, ... aunque en ese caso caso creo que si hay una diferencia en objetivos de aprendizaje (_serverless_ en el caso del `burger-queen` original).

cc/ @merunga @Laboratoria/bootcamp-coaches

**Comment by merunga** [comment]
@lupomontero creo q podriamos "deprecar" `bq-node` y en unos meses lo volamos.

luego, creo q `burger-queen` y `burger-queen-api-client` si necesitan seguir conviviendo, porque si no hay `burger-queen-api`, no tiene sentido `burger-queen-api-client`
