### ISSUE TITLE
Agregar script de despliegue en boilerplates?

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#903]
Teniendo en cuenta que en muchos proyectos sugerimos que desplieguen a GitHub Pages quizás tenga sentido en los primeros proyectos agregar un `npm-script` de despliegue (`deploy`) usando el módulo [`gh-pages`](https://www.npmjs.com/package/gh-pages). Así evitaríamos que desplieguen en `master` y que después haya que navegar a la carpeta `src/` para ver la página o app.

Ver: https://github.com/Laboratoria/bootcamp/pull/885#discussion_r339654722

cc/ @Laboratoria/bootcamp-coaches

**Comment by shirley-startary** [comment]
Me gusta la idea, y esto me lleva a pensar que como objetivo de aprendizaje del cipher/dataLovers también sea "Entender la estructura o función del package.json".

**Comment by lupomontero** [comment]
Si nadie se opone, me lanzo con un PR (es un cambio trivial).

Esto afectaría a los siguientes proyectos: `trivia`, [`cipher`](https://github.com/Laboratoria/bootcamp/tree/master/projects/01-cipher), [`card-validation`](https://github.com/Laboratoria/bootcamp/tree/master/projects/01-card-validation), [`data-lovers`](https://github.com/Laboratoria/bootcamp/tree/master/projects/02-data-lovers) y [`social-network`](https://github.com/Laboratoria/bootcamp/tree/master/projects/03-social-network).

**Comment by merunga** [comment]
@lupomontero si ya va a estar en todos los proyectos de CC, quizas estaria bueno que **no** estuviera en `social-network`
