### ISSUE TITLE
Portuguese translation of main repo's README 🇧🇷

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#911]
Now that the information about project assessment and feedback has been moved to [the main README](https://github.com/Laboratoria/bootcamp/blob/master/README.md) instead of each individual project README we need to have at least the text in [the _evaluación_ heading](https://github.com/Laboratoria/bootcamp#evaluaci%C3%B3n), and ideally the whole readme would also be translated into portuguese.

cc/ @rafaelbcerri @JulianaAmoasei @paclaraujo

**Comment by juanjordan** [comment]
Worked on #960
