### ISSUE TITLE
project(social-network): Add Portuguese translation 🇧🇷

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#913]
I believe the [`social-network`](https://github.com/Laboratoria/bootcamp/tree/master/projects/03-social-network) project has already been used in Sao Paulo, but the translated `README-pt-BR.md` does not seem to have landed in `master` yet. It would be great to have it here :smile: 

cc/ @rafaelbcerri @JulianaAmoasei @paclaraujo

**Comment by lupomontero** [comment]
:eyes:

**Comment by paclaraujo** [comment]
This issue was resolved <3

**Comment by juanjordan** [comment]
https://github.com/Laboratoria/bootcamp/pull/944 closes this, ⭐️
