### ISSUE TITLE
project(card-validation): Add Portuguese translation 🇧🇷

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#914]
The [`card-validation`](https://github.com/Laboratoria/bootcamp/tree/master/projects/01-card-validation) project was recently added as an alternative to `cipher` and it would be great to be able to offer this project in Brazil :wink: 

cc/ @rafaelbcerri @JulianaAmoasei @paclaraujo

**Comment by rafaelbcerri** [comment]
@JulianaAmoasei você poderia ver essa tradução? (Quando der tempo)

**Comment by JulianaAmoasei** [comment]
Ok

**Comment by lupomontero** [comment]
Hi @JulianaAmoasei, any news wrt to this translation?

**Comment by juanjordan** [comment]
This is issue should've been closed by #969
