### ISSUE TITLE
project(burger-queen): Add Portuguese translation 🇧🇷

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#915]
I'm not sure whether or not the [`burger-queen`](https://github.com/Laboratoria/bootcamp/tree/master/projects/01-card-validation) project has already been used in Sao Paulo... :thinking: ... it would be great to have this translated and merged into `master` :smile_cat: 

While at it, it is probably a good a idea to also look into the recently added [`burger-queen-api`](https://github.com/Laboratoria/bootcamp/tree/master/projects/04-burger-queen-api) (back-end) and [`burger-queen-api-client`](https://github.com/Laboratoria/bootcamp/tree/master/projects/04-burger-queen-api-client) (a web front-end to this back-end) and consider translating those too.

cc/ @rafaelbcerri @JulianaAmoasei @paclaraujo

**Comment by lupomontero** [comment]
Hi @paclaraujo, any news wrt this issue?

**Comment by paclaraujo** [comment]
This issue was resolved <3

**Comment by juanjordan** [comment]
Oh! thanks @paclaraujo, https://github.com/Laboratoria/bootcamp/pull/941 closes this issue.
Let's not forget to take a look at burger-queen-api and burger-queen-api-client but we can add some other issues to have those. 🚀
