### ISSUE TITLE
Proyecto electivo Móvil Nativo (Android/IOS)

### ISSUE THREAD

**Issue by FabianBravoA** [Laboratoria/bootcamp#919]
Tomando desde lo que se conversó en reuniones y el PR que estaba antes, es que se comenzará por experimentar primero con un electivo de programación de aplicaciones nativas en móviles.

El proyecto se agregará a la parrilla ya existente de electivos y tendrá una dificultad parecida a TicTacToe, pero tomando en cuenta que será en una plataforma distinta y en un lenguaje completamente diferente a javascript, su duración estará contemplada en 3 semanas (máximo de lo que duran los proyectos en laboratoria).

Está contemplado para estar en pruebas para Enero/Febrero del 2020 con la generación SCL011 si es que no hay mayores cambios en los planes de esa generación y solo se hará con las estudiantes que tengan interés en realizar este electivo al final de su Etapa 2 de FrontEnd (última en su paso por el bootcamp).

Cualquier sugerencia, idea, comentario sobre esto es bienvenido.

**Comment by lupomontero** [comment]
Hola @FabianBravoA, alguna novedad con respecto a la propuesta de experimento para el proyecto electivo de _mobile_?

**Comment by FabianBravoA** [comment]
Tengo al menos los plazos, ya que terminando el de LabSalud comenzaré con el de Android teninendo como objetivo la generación SCL012 ahora. La SCL011 ya comenzó con los electivos y ya tiene asignado un proyecto con empresas.

**Comment by lupomontero** [comment]
Cerrado por inactividad...
