### ISSUE TITLE
Data Lovers links about research made for the datasets are broken

### ISSUE THREAD

**Issue by luucamay** [Laboratoria/bootcamp#948]
The links in the data lovers description for Pokemon, LOL, and Rick and Morty user research documents are broken and send the user to a 404 page. 

This is the [file](https://github.com/Laboratoria/bootcamp/tree/master/projects/02-data-lovers) that should be modified to solve this bug.

**Comment by juanjordan** [comment]
Thank you @luucamay for reporting this issue 🙏, I've sent a PR attempting to fix these links.
