### ISSUE TITLE
Fix Travis notifications not appearing in PRs

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#963]
Alternatively consider switching to GitHub Actions... :thinking:

**Comment by lupomontero** [comment]
@juanjordan, he vuelto a configurar la rama `master` para que _requiera_ los status checks de Travis en PRs... y parece que ya está funcionando otra vez (creo que arreglaron algo del lado de Travis).

![image](https://user-images.githubusercontent.com/110297/80991883-51b13900-8dfe-11ea-83c9-d6ba5a97c5e2.png)

Después de salvar cambios, veo que ya hay status checks en #958 y #962.

Cierro este issue por ahora, ya que parece solucionado, pero si ven que vuelve a ocurrir no duden en reabrirlo.

**Comment by juanjordan** [comment]
Genial y qué habrá sido con Travis 🤔, ojalá no se repita, gracias!
