### ISSUE TITLE
introducción a TDD

### ISSUE THREAD

**Issue by tzkmx** [Laboratoria/bootcamp#972]
Hola estimadxs laboratorians.

Me atrevo a abrir este issue buscando formas de participar tras estar leyendo de la currícula actualizada y estar en espera de seguir la participación como posible mentor y tal vez adelantando entender como servir del modo más efectivo a los esfuerzos ya hechos.

Al punto: me llama la atención que desde los primeros proyectos (luhn y César) introducen TDD con Jest, entendido como objetivos de aprendizaje y luego en data lover se vuelve una sugerencia.

Tal vez porque me falta mucho contexto del LMS y otras conversaciones que no se reflejan acá, pero no me hace demasiado sentido hacer de pruebas algo casi requerido y luego apenas sugerencia.

Por otra parte, creo que al menos habría que ayudar dándoles la primer receta. En mi poca experiencia como mentor de un par de frontend júnior en la chamba, me facilitó venderles usar prueba unitaria para un algoritmo complejo, cuando yo mismo les escribí un par de casos de prueba y les di así tanto el signature de la función como casos que su algoritmo debía cubrir.

Y de ahí, ya le fue más sencillo a mi colaboradora escribir más pruebas para más casos, empezamos a tener más comprensión concreta de código limpio. Implementar pruebas más a menudo.

Mentiría diciendo que cubrimos todo con pruebas de hecho es mínimo, pero una de ellas aún con una ingeniería detrás todo le parecía muy abstracto y hasta que las pruebas le mostraron que le **ahorraba** tiempo para algunos desafíos, pudimos avanzar en otras cosas.

De nuevo tal vez me falta mucho contexto pero este es un punto clave en el desarrollo moderno que vale mucho la pena no dejar en el aire como algo deseable pero más tema de evangelización que práctica asequible y valiosa.

**Comment by juanjordan** [comment]
Hola @tzkmx Jesus, ¡gracias por comentar! ¿podrías ser más específico del lugar donde se indica que TDD es una sugerencia en el proyecto Data-lovers? ¿Te refieres a una parte específica del README del proyecto?

Para más contexto, dentro de los criterios de aceptación mínimas del proyecto se encuentra:
> Pruebas unitarias
El boilerplate de este proyecto no incluye Pruebas Unitarias (tests), así es que tendrás que escribirlas tú para las funciones encargadas de procesar, filtrar y ordenar la data, así como calcular estadísticas.

> Tus pruebas unitarias deben dar una cobertura del 70% de statements (sentencias), functions (funciones), lines (líneas), y branches (ramas) del archivo src/data.js que contenga tus funciones y está detallado en la sección de Consideraciones técnicas.

https://github.com/Laboratoria/bootcamp/tree/master/projects/02-data-lovers#pruebas-unitarias

Muchas gracias de antemano. 🚀

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue por inactividad, pero porfa no duden en reabrirlo si lo consideran necesario.
